### ISSUE TITLE
sequence in sale order is not stable when add new items in the existing quotation

### ISSUE THREAD

**Issue by Garywei1314** [odoo/odoo#10003]
Here is the issue: for some quotations, some time after we creating them, we need to add new products to this quotation.But after we saved the modified quotation, the sequence of the new added products is not listed in the last of the sales order lines. it will random jumped insert to between some 2 existing products. The items's sequence change and change, this make it difficult to compare 2 versions of the same quotation

Hope this could be solved ASAP

And we checked from the code level found that:
 Sale order lines are sorted by the sequence, and id.
 But we find that the sequence of the new sale order line is always default value '10' after click the 'save' button in the sale order. This causes the new record appear in the front of the list if other's sequence is larger than 10.

**Comment by pedrobaeza** [comment]
This is a known issue due to the default being applied in the sequence field, but on latest version (v11), with the view refactoring, there has been a little improvement of this: when you add the line and the sales order popups the form view, when saving, the line gets automatically ordered. It doesn't happen that when the tree is editable unfortunately.

@ged-odoo is any improvement planned for this. My best bet would be to check on client side when you have in a field with widget handle and click on "Add an item", to calculate the value of that field depending on editable value (bottom, top), and decreasing/increasing the value of the min/max value of the dataset. What do you think?

**Comment by intero-chz** [comment]
@ged-odoo sorting afterwards by using the handle widget isn't the point here (@Garywei1314 please correct me if necessary). The point is the default sequence which is always the same instead of increasing it with every creation of an order line.

**Comment by ged-odoo** [comment]
well, the sequence number is in theory 'invisible' to the user, and as soon as a reordering operation is performed, every records will be assigned, if necessary, an appropriate sequence number, in such a way that the user sees what he expects.  At the end of the day, what matters is that the records are always displayed in the correct order.  Before our fixes, it could jump randomly, not anymore. So, I still think that the issue is fixed.

**Comment by intero-chz** [comment]
So IIRC the issue is fixed in v11? Is there any good solution for v10 (without rewriting JS code if possible)?

**Comment by pedrobaeza** [comment]
@intero-ch No, this is for future v12, and no, there's no possible solution before.

**Comment by pedrobaeza** [comment]
@ged-odoo I have tried runbot on master and I'm afraid it still continues the same on the main problematic: new lines added after reordering existing ones. They are added at the end, but when saving, due to the default sequence value, they are reordered to other place. See the screencast for illustrating the problem:

![peek 11-04-2018 18-43](https://user-images.githubusercontent.com/7165771/38630925-93d44bbc-3db8-11e8-8cb8-285a0ad53e3d.gif)

**Comment by ged-odoo** [comment]
@pedrobaeza ok, i see what you mean (a gif makes such a difference!).  I think that it could be argued that the web client here behaves as expected: the web client respected the default_get value received by the server for the sequence field.

We have here an incompatibility between 2 things:
1. the list view is in editable=bottom, so its job is to create a new record at the end of the page
2. the web client job has to obey the server default_get value

If we do not do 1., then the user interface would be confusing, and it would be awkward to create new sub records.  If we do not do 2., then the server loses some power: the default value for the sequence field cannot be customized by the server.

I think that if we use the widget=handle, then it is ok to reassign the sequence number as well at the creation. So, in short, I think that we can fix this, but this should be done in master

**Comment by pedrobaeza** [comment]
> I think that if we use the widget=handle, then it is ok to reassign the sequence number as well at the creation. 
Yeah, I think the same, as visual consistency is here more important than the strict ORM.

> So, in short, I think that we can fix this, but this should be done in master
Please!

Another thing you can refine is to put the "Add a line" line in the upper part when `editable="top"`, because if not, you force to scroll down to push there each time you want to add the line, and then it's scrolled up automatically to top of the list.

**Comment by intero-chz** [comment]
FYI, i tried something and it is working like a charm.

models: `sale.order` and `sale.order.line`

1. extend `sale.order` with a computed field which depends on `order_line`, let me call it `max_line_sequence`, which will compute the maximum sequence of all lines
    
```python
    @api.multi
    @api.depends('order_line')
    def _compute_max_line_sequence(self):
        for order in self:
            sequences = [l.sequence for l in order.order_line]
            if sequences:
                order.max_line_sequence = max(sequences)
            else:
                order.max_line_sequence = 0
```
2. add the field invisible to the view(s) of `sale.order`
3. get the field value into the context of order_line in the view(s) of `sale.order`
4. extend `sale.order.line` `sequence` field default by using the context value
```python
    @api.model
    def _default_sequence(self):
        max_seq = self.env.context.get('max_line_sequence', None)
        if max_seq:
            return max_seq + 1
        return 10
```

I haven't tested everything with it, but creation and line updates + handle usage (to reorder) is working.

**Comment by ged-odoo** [comment]
I just ping @sht-odoo to let him know about this...

**Comment by pedrobaeza** [comment]
Thanks, Géry, waiting for your feedback then.

**Comment by ged-odoo** [comment]
in case some of you are interested, @sht-odoo is experimenting on this issue in the branch https://github.com/odoo-dev/odoo/commits/master-handle-default-sequence-sht

**Comment by pedrobaeza** [comment]
Thanks for the follow-up!

**Comment by seb-odoo** [comment]
The issue should now be fixed on master in this commit:

https://github.com/odoo/odoo/commit/b2c1d5ede2254e13bea32451faefa28a6eddcd4c

**Comment by pedrobaeza** [comment]
That's great! I will check it and tell you back

**Comment by pedrobaeza** [comment]
Hi, @seb-odoo I have tried on runbot master branch, and this seems to be better, but I still found some issues. Following this sequence:

* Add 10 lines of the same product in invoice line.
* Reorder one of them to be the last to get all sequences reassigned. Last sequence number is 20.
* Add one extra line. This line gets sequence 20 as well.
* Save and add other extra line. It gets also 20 as sequence (I changed the widget for seeing visually the numbers):

![seleccion_022](https://user-images.githubusercontent.com/7165771/42088786-194c54cc-7b9b-11e8-8903-d1f9b0898573.png)

IMO, new lines should be 21 and 22 sequence respectively, or you will get other undesired effects like this reordering by sequence (it's not the exact reverse list):

![seleccion_023](https://user-images.githubusercontent.com/7165771/42088869-5dee6b2e-7b9b-11e8-8091-9c257a7ee2c6.png)

Can you please check my comments?

**Comment by seb-odoo** [comment]
@pedrobaeza we know about this issue, but it was a lot more work to resolve it.

If we just increment by 1 every time, there will be an issue if the following existing elements have the same sequence too (which can happen if there are multiple pages, current limit for new page is 40 but you can change it to test).

What I mentioned in one of the comments in the code should be that for every new element added we need to increment every following element by 1, even all of those that are on the following pages (at least until there is a gap in the numbering).

However, this solution would be costly to implement for big sale orders (or other views).

There are strategies to improve that kind of problem (for example initially incrementing by more than 1 to leave gaps), but we don't want to focus on that. The current solution is a compromise that should be good enough for everyone.

We currently don't support reordering the sequence column when there is a handle field.

**Comment by seb-odoo** [comment]
This seems to be a good idea, but I need to investigate it before promising anything. Right now have I have a higher priority task, but I'll keep it in mind and hopefully have a look when I'm done.

Thanks for all your reviews and feedback!

**Comment by intero-chz** [comment]
What about shifting the functionality onto the server side? I mean the default methods are called anyway. Is there no way to get the maximum sequence of a list into the context to use it in default methods?

**Comment by dhannyz** [comment]
@intero-chz 
If you had to, you could try something in the create method paired with your context for setting the initial default
Likely to be bad on performance however

```python
    @api.model
    def create(self, vals):
        next_seq = 1
        sale = self.env['sale.order'].browse(vals.get('sale_id', False))
        if sale:
            next_seq = max(sale.order_line.mapped('sequence') or [0]) + 1
        vals['sequence'] = next_seq
        return super(SaleOrderLine, self).create(vals)
```
Then there's the issue of accounting for sequences that are changed from their default prior to creation, perhaps check if their val.get['sequence'] is different to the computed default

**Comment by intero-chz** [comment]
@dhannyz but there is one problem with that approach. It's only working when clicking the save button. That's not the a user would work with an order. Thanks for the approach anyway!

**Comment by pedrobaeza** [comment]
@seb-odoo did you have time for checking the proposal I made in https://github.com/odoo/odoo/issues/10003#issuecomment-401326951?

**Comment by seb-odoo** [comment]
@pedrobaeza I'm getting there. I merged all of my big tasks, now I can focus on the bug fixes and small improvements like this one.

**Comment by pedrobaeza** [comment]
Great! Let me know if you want me to review anything.

**Comment by augustodinizl** [comment]
I've roughly addapted this ( [https://github.com/augustodinizl/odoo-addons/tree/11.0/sale_order_line_sequence](url) ) to prevent these behavior and it worked

**Comment by seb-odoo** [comment]
PR merged

**Comment by pedrobaeza** [comment]
Thanks!

**Comment by droidosergioh** [comment]
Hello @seb-odoo  and @pedrobaeza  I do not understand why this thread is closed. I have updated to last version but I am still facing the issue.... (new elements go to second position and sale order lines change the original order). Do I need to do something special besides of update the modules? I am using v11

**Comment by pedrobaeza** [comment]
This is solved in v12, not in v11.

**Comment by droidosergioh** [comment]
Ok @pedrobaeza , Is there a way to solve it for v11? In the case yes, which files should I modify?

**Comment by pedrobaeza** [comment]
I'm afraid not, as the underlying changes are very huge (JS framework is not the same).

**Comment by droidosergioh** [comment]
@pedrobaeza Then I do not consider that this bug is fixed for v11... this is a quite huge problem for many companies. There could be any other solution?

**Comment by pedrobaeza** [comment]
This is never going to be solved in v11, due to stability policy. Go to 12.0, or the good news is that we have backported in OCB: https://github.com/OCA/OCB/pull/855
