### ISSUE TITLE
The Frontend translation is limited (or buggy) when the website default language is not english

### ISSUE THREAD

**Issue by rruebner** [odoo/odoo#10095]
Hi all,
#### Impacted Versions:
- 9.0
#### Steps to reproduce
1. Open a runbot v9 instance
2. Install a second language
3. Go to Website Admin -> Configuration
4. Change the default language from english to the second language
5. Open any frontend page, change the language to englisch and click on translate:
   - the green markers are missing
   - the main navigation labels can’t be translated
   - if you are on a blog post page the blog title and subtitle can’t be translated
6. The points above work when english is the website default language
#### Expected behavior

The translation should work the same way for a non english default language like it works for the english default language.

**Comment by Fl0rianFischer** [comment]
@rruebner I created a pull request to fix the blog title and subtitle problem
https://github.com/odoo/odoo/pull/10828

**Comment by Yajo** [comment]
In v8 there's an additional funny bug:

0. Install 2 additional languages for the website.
0. Disable English for the website.
0. Set lang 1 as default for website.
0. Go edit a page, event, blog post, etc.
0. Translate to lang 2. OK.
0. Go back to lang 1 version and add a new block.
0. Translate again to lang 2. New block does not appear there!

**Comment by rafaelbn** [comment]
I think this issue has been resolved in v9 but not in v8

**Comment by JKE-be** [comment]
Many fix has been done  in 2 years...

Please check again and ping me or @rdeodoo  if not yet fixed...
