### ISSUE TITLE
l10n_cl: Invoice print returns: AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by jocarren** [odoo/odoo#108492]
I'm running Odoo v15 in docker. The Chilean localization has this error.

Impacted versions: 15

Steps to reproduce: Try to print an invoice.

Current behavior: Odoo does not render the document in web view nor in pdf.

Expected behavior: Invoice is printed in pdf and web view.

Video/Screenshot link (optional): 
![imagen](https://user-images.githubusercontent.com/23640344/208968447-09263d02-e162-4792-b167-c8f86be10f9e.png)

LOGS:

```
Error to render compiling AST
AttributeError: 'bool' object has no attribute 'split'
Template: l10n_cl.custom_header
Path: /t/div/div/div[2]/div/div/div[1]/div/h6/strong/span[2]
Node: <span t-esc="o.company_id.partner_id._format_dotted_vat_cl(o.company_id.partner_id.vat)"/>
```
```

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_cl_custom_header_2738
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_cl/models/res_partner.py", line 46, in _format_dotted_vat_cl
    vat_l = vat.split('-')
AttributeError: 'bool' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 2134, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 2065, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/ir_actions_report.py", line 50, in _render_qweb_pdf
    return super()._render_qweb_pdf(res_ids=res_ids, data=data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 824, in _render_qweb_pdf
    html = self_sudo.with_context(context)._render_qweb_html(res_ids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 865, in _render_qweb_html
    return self._render_template(self.report_name, data), 'html'
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 601, in _render_template
    return view_obj._render_template(template, values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1718, in _render_template
    return self.browse(self.get_view_id(template))._render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 28, in _render
    return super(IrUiView, self)._render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1726, in _render
    return self.env[engine]._render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 55, in _render
    result = super(IrQWeb, self)._render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 258, in _render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_report_invoice_with_payments_2627
  File "<template>", line 2, in body_call_content_2625
  File "<template>", line 3, in foreach_2624
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_cl_report_invoice_document_2665
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_external_layout_2708
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 333, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_external_layout_standard_2725
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 338, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'bool' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_l10n_cl_custom_header_2738
  File "/usr/lib/python3/dist-packages/odoo/addons/l10n_cl/models/res_partner.py", line 46, in _format_dotted_vat_cl
    vat_l = vat.split('-')
AttributeError: 'bool' object has no attribute 'split'

Error to render compiling AST
AttributeError: 'bool' object has no attribute 'split'
Template: l10n_cl.custom_header
Path: /t/div/div/div[2]/div/div/div[1]/div/h6/strong/span[2]
Node: <span t-esc="o.company_id.partner_id._format_dotted_vat_cl(o.company_id.partner_id.vat)"/>
```

Seems like there is an issue with the attrubute 'split' in 'vat_l'

https://github.com/odoo/odoo/blob/27dc6ef8971201b0bb9e5e0376cb666145811dee/addons/l10n_cl/models/res_partner.py#L46

Another person has the same issue in [Windows](https://www.odoo.com/es_ES/forum/accounting-6/facturacion-error-de-servidor-de-odoo-rpc-error-204209)

**Comment by jocarren** [comment]
Thank you so much to everyone involved in this fix. I'll be testing and reporting as soon as the nightly builds are released, probably tomorrow.

**Comment by niyasraphy** [comment]
hi @jocarren ,
can you close the issue, as it is resolved in the core.
thanks

**Comment by jocarren** [comment]
Hello again. Tested against latest nightly build and the problem persists. 

![imagen](https://user-images.githubusercontent.com/23640344/211078919-fadf40de-6eac-465f-b5be-e7e87e4d61db.png)

```Error when render the template
AttributeError: 'bool' object has no attribute 'split'
Template: l10n_cl.custom_header
Path: /t/div/div/div[2]/div/div/div[1]/div/h6/strong/span[2]
Node: <span t-esc="o.company_id.partner_id._format_dotted_vat_cl(o.company_id.partner_id.vat)"/>
```
Te VAT is actually defined for the client. 

I believe the issue is when the view tries to divide the VAT in two parts: 
VAT (RUT): 11.111.111-6
Splits in 11.111.111 and 1
The attribute "split" doesnt seem to be defined wich causes the error.
