### ISSUE TITLE
Odoo CDN is broken

### ISSUE THREAD

**Issue by aek** [odoo/odoo#12587]
Impacted versions: Online
Steps to reproduce: Open the Odoo Forum at https://www.odoo.com/forum/help-1
Current behavior: A lot of errors in the browser console related to the load of the odoocnd resources, due to those errors you couldn't see a lot of icons and the user experience is drastically affected.
Errors in the browser console tested with chrome says for example:

> Font from origin 'https://odoocdn.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.odoo.com' is therefore not allowed access.

Expected behavior:
No errors and resources loaded normally. 

Video/Screenshot link (optional):
![screenshot from 2016-06-27 03 03 59](https://cloud.githubusercontent.com/assets/404966/16376184/dfe17d0c-3c13-11e6-84b1-446eec7343c7.png)

**Comment by aek** [comment]
I noticed that odoocdn.com is using cloudflare-nginx. I had a similar case once and I solved adding this to my nginx server block, for your case

> add_header X-Frame-Options "ALLOW https://www.odoo.com/";

**Comment by odony** [comment]
@aek The problem should be fixed, we forced a refresh of CloudFlare's cache, the Cross-Origin headers were missing in some regions. If you force a refresh in your browser (ctrl+F5) the fonts should work.

**Comment by aek** [comment]
Still not working after a refresh with ctrl+F5(already tested), not even in an incognito window and confirmed in firefox too

**Comment by Yenthe666** [comment]
It is all fine at my side now.

**Comment by aek** [comment]
Still nothing, the issue remains at my end

**Comment by aek** [comment]
The issue continue, I cannot see the font icons. I tried everything but not sucess

**Comment by aek** [comment]
It's working finally, thanks

**Comment by aek** [comment]
And now it's not working again. Sorry for posting in a closed issue but I can't reopen it and I don't wanna create another one for the same. Maybe this is helpful to alert about something that it's missing or need a fix in the CD workflow of Odoo or something

**Comment by odony** [comment]
@aek we haven't changed anything on our side since my last comment, you are perhaps experiencing glitches in CloudFlare's cache servers, or problems in your browser's handling of CORS.
In order to verify this, please look at the headers you receive when your browser loads the fonts, as shown in this picture. It is worth trying in different browsers/computers/internet providers if you have access to more than one. You could also look at the `CF-RAY` response header to detect which cloudflare cluster is handling your request (if you look at my example, it's the one in BRUssels):

![debug_fonts](https://cloud.githubusercontent.com/assets/2039870/16481437/8f0b04da-3eab-11e6-9d5c-1e3e490a446d.png)

**Comment by aek** [comment]
I done those steps that you suggested and the interesting part is that I can't see any access-control-allow-origin response header but also there is some requests against odoocdn.com that returns ok, but others like in the image have errors
![screenshot from 2016-06-30 10 54 50](https://cloud.githubusercontent.com/assets/404966/16498740/f77b9902-3eb1-11e6-867e-9a1a1c4ac0cc.png)
![screenshot from 2016-06-30 10 55 14](https://cloud.githubusercontent.com/assets/404966/16498750/009bb210-3eb2-11e6-99f6-2ce96f265f33.png)
![screenshot from 2016-06-30 10 55 34](https://cloud.githubusercontent.com/assets/404966/16498749/009b398e-3eb2-11e6-8352-61330b2f3069.png)

There is no coors header but still some files are loaded and others no. My Cloudflare cluster seems to be the one from Los Angeles, California(LAX)

**Comment by odony** [comment]
@aek Thanks for the screenshots. The very reason you can't load the fonts is because of the missing "access-control-allow-origin" response header. So now I have more questions for you ;-)

1. You didn't show/say if the "Origin" header is indeed passed in the "Request headers" (otherwise the Response cannot have the "access-control-allow-origin" header). Is that what you meant with "no coors headers"??

2. Could you also report the exact version of Chrome and of your OS, so we can attempt to reproduce with the same config?

3. Did you/Could you try with different browsers, e.g. with Firefox?

4. Your many "ERR_NETWORK_CHANGED" errors in the console seem to indicate network problems. Are you on a physical computer directly connected to a broadband connection? I'm asking because there are Chrome users reporting similar generic errors when connected through a VPN, or when running on certain virtual machines/environments. Look e.g. [here](http://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome), or [here](http://www.incrediblelab.com/fix-err-network-changed-windows/) or google this error message. Some people also report success after disabling all Chrome extensions, but apparently you are testing in incognito mode with no extensions, so that probably won't help much.

Thanks!

**Comment by aek** [comment]
Sorry @odony  I miss the notification about your last comments. Thanks for have a look at it. It started to work some days latter from my last comment. And it's pointless to answer those question now since I don't get the errors anymore, but the relevant ones are that I use a laptop running Ubuntu and connected to a wifi and I test it on Firefox too. 
Seems to me that was simply a Cloudflare LAX miss-configuration or not updated properly since the responses are the ones that get errors. I know that Chrome extensions could lead to errors too but Firefox had the same problem.
Anyway it's solved now, thanks

**Comment by odony** [comment]
@aek Thanks for the update, considering the issue finally closed then!

**Comment by beshoynabeih** [comment]
@odony I have the same problem
