### ISSUE TITLE
[9.0] Cannot select Employee name in Payslip form if Interface is in Arabic

### ISSUE THREAD

**Issue by alaa9jo** [odoo/odoo#13281]
Impacted versions: 9.0c

Steps to reproduce:
* Make sure you have installed module HR

1) Create a new employee with name "احمد حسن" 
2) Go to Payslip screen
3) Before clicking on Create, click on your profile and change your preference language from English to Arabic then save
4) Click on "انشاء" / "Create" to create a new payslip
5) Click on Employee field "الموظف" then select "احمد حسن"

<img width="596" alt="screen shot 2016-08-24 at 2 49 28 pm" src="https://cloud.githubusercontent.com/assets/1232772/17930175/8c04108c-6a0d-11e6-85b0-0c13550711f2.png">

Current behavior:

Once you click on "احمد حسن" an error occurs:

```
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 6066, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/openerp/models.py", line 5923, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/addons/hr_payroll/hr_payroll.py", line 699, in onchange_employee
    self.name = _('Salary Slip of %s for %s') % (employee_id.name, tools.ustr(ttyme.strftime('%B-%Y')))
TypeError: not all arguments converted during string formatting
```

I think this has something to do with employee name in arabic on arabic interface, I can't reproduce it if I switch to English Interface

Expected behavior:

I should be able to select that employee on Arabic interface

Video/Screenshot link (optional):

@Yenthe666 , What do you think of this issue?  Could you let someone have a look into this one? Thanks !

**Comment by Yenthe666** [comment]
@mart-e this one is for you :wink:

**Comment by mart-e** [comment]
I think I fixed the translation at https://www.transifex.com/odoo/odoo-9/translate/#ar/hr_payroll/59103213 but to check with an arabic speaking person :wink:

**Comment by alaa9jo** [comment]
Sorry for my late reply

It seems the fix didn't work, I fetched the latest updates from repo 9.0 , restarted odoo and forced refresh my browser but I still see the same issue

```
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 888, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/openerp/models.py", line 6066, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/odoo/odoo-server/openerp/models.py", line 5923, in _onchange_eval
    method_res = method(self)
  File "/odoo/odoo-server/addons/hr_payroll/hr_payroll.py", line 699, in onchange_employee
    self.name = _('Salary Slip of %s for %s') % (employee_id.name, tools.ustr(ttyme.strftime('%B-%Y')))
TypeError: not all arguments converted during string formatting
```

**Comment by mart-e** [comment]
@alaa9jo you need to refresh your translations too.
In debug mode (top right > about Odoo > active the dev mode), you can reload the translations with force overwrite.

![selection_032](https://cloud.githubusercontent.com/assets/564822/18045013/e8ec93a2-6dd0-11e6-9cb4-98393868519c.png)

**Comment by alaa9jo** [comment]
Oh Thanks @mart-e 👍
