### ISSUE TITLE
[10.0] PayPal payment acquirer in eCommerce causes server error with live paypal, works in sandbox

### ISSUE THREAD

**Issue by saulih** [odoo/odoo#13834]
**Impacted versions**: 10.0

**Steps to reproduce**: 
- create a ecommerce web store with paypal payment acquirer enabled
- paypal account settings: autoreturn on, payment data transfer off, encoding utf-8 (as instructed by documentation), autoreturn address www.mydomain.com/shop/confirmation
- odoo paypal acquirer settings: IPN on, "Authorize & capture the amount and confirm the SO on acquirer confirmation"
- complete checkout process and payment

**Current behavior**: 
- upon returning from PayPal Odoo raises an exception and user gets server error 500

```
File "/usr/lib/python2.7/dist-packages/odoo/addons/payment_paypal/controllers/main.py", line 70, in paypal_dpn
    return werkzeug.utils.redirect(self._return_url)
File "/usr/lib/python2.7/dist-packages/odoo/addons/payment_paypal/controllers/main.py", line 44, in paypal_validate_data
    paypal_urls = tx.acquirer_id._get_paypal_urls(tx.acquirer_id.environment or 'prod')
AttributeError: 'NoneType' object has no attribute 'acquirer_id'
```

**Expected behavior**:
- payment should be registered, sales order approved and user brought to order confirmation page

With a sandbox paypal account the process works, although it seems sandbox payments behave a little differently from live.

I managed to get the payment process go thru with a live paypal account with following modifications to payment_paypal/controllers/main.py:

**Original**:

```
    @http.route('/payment/paypal/dpn', type='http', auth="none", methods=['POST', 'GET'], csrf=False)
    def paypal_dpn(self, **post):
        """ Paypal DPN """
        _logger.info('Beginning Paypal DPN form_feedback with post data %s', pprint.pformat(post))  # debug
        return_url = self._get_return_url(**post)
        self.paypal_validate_data(**post)
        return werkzeug.utils.redirect(return_url)
```

**Modified**:
when paypal payment is completed the user is returned to /payment/paypal/dpn rather than /shop/confirmation, and it's a GET request so the original code crashes when it can't validate nonexisting POST data.

```
    @http.route('/payment/paypal/dpn', type='http', auth="none", methods=['POST', 'GET'], csrf=False)
    def paypal_dpn(self, **post):
        """ Paypal DPN """
        if post:
            _logger.info('Beginning Paypal DPN form_feedback with post data %s', pprint.pformat(post))  # debug
            return_url = self._get_return_url(**post)
            self.paypal_validate_data(**post)
        else:
            _logger.info('No PayPal DPN data, redirecting to order confirmation')  # debug

        return werkzeug.utils.redirect("/shop/confirmation")
```

Only issue remaining after this is that user's cart doesn't get emptied after returning to order confirmation page, related quotation gets confirmed into sales order but items remain in the cart.

**Comment by smartupdo** [comment]
This happened to me as well.

**Comment by muntean** [comment]
I have this issue, too.

**Comment by saulih** [comment]
I tested using '/shop/payment/validate' as redirect link from paypal and it does clear the shopping cart, but user doesn't see an order confirmation. Instead it just brings them back to the store front.

Could Odoo techs please weigh in on this?

**Comment by lolziac** [comment]
I can confirm this issue is happening with me also. :(

**Comment by aristobulo-eezee** [comment]
maybe @Yenthe666 can help you

**Comment by mart-e** [comment]
Hello,

It is indeed a bug in the version 10 of code. It was fixed at d29c40e1e1c1ae0d505d27159bccab2e8dd31083

**Comment by Yenthe666** [comment]
Woha good job Martin, even ahead of me 😉

**Comment by saulih** [comment]
Thanks for the fix @mart-e 

Odoo no longer crashes upon returning from PayPal, SO goes into fully paid state but couple issues still remain: 
 - user is returned to website front/home page instead of an order confirmation page
 - ordered items still show up in the cart (however the user can't double order, the cart is cleared if user tries to check out)

**Comment by mart-e** [comment]
@saulih please keep one bug per issue. These seems unrelated and should be discussed separately.
Thanks

**Comment by ITISAG** [comment]
hi Saulih, hi mart-e 
We still see the issue that Saulih has raised in the last comment from 13Dec2016. Please point us to a solution for the remaining topics  (we dont know where you had opened a new issue, but the PayPal integration is unusable therefore). We have a customer with a live shop that is going nuts.

**Comment by saulih** [comment]
@ITISAG, check out #14727 .

**Comment by jleaders** [comment]
I saw the same issue on Authorize.NET
https://github.com/odoo/odoo/issues/15930
