### ISSUE TITLE
Renamed method breaks some features

### ISSUE THREAD

**Issue by sylvain-garancher** [odoo/odoo#13865]
The `_handle_renaming` method of `stock.warehouse` has been renamed to `_update_name_and_code`, and an "alias" has been added, to automatically forward calls to the old name to the new name.

This makes the "calling the old method name" part work.
However, the overrides of this method were not renamed accordingly. As the new code calls the new name, the overrides are not called anymore. This makes the warehouse handling renaming partially broken.

I didn't check, but the `_run_move_create` method of the model `procurement.order`, overriden in the `sale_stock` module, probably suffers from the same issue.

**Impacted versions:** 10.0

**Steps to reproduce:**
Rename a warehouse

**Current behavior:**
Not all rules/routes are renamed

**Expected behavior:**
All linked rules/routes are renamed

**Additional information:**
Change that breaks the renaming handling : https://github.com/odoo/odoo/blob/10.0/addons/stock/models/stock_warehouse.py#L600
At least two modules overriding this method have to be fixed :
https://github.com/odoo/odoo/blob/10.0/addons/mrp/models/stock_warehouse.py#L121
https://github.com/odoo/odoo/blob/10.0/addons/purchase/models/stock.py#L127

**Comment by JKE-be** [comment]
WIP: https://github.com/odoo-dev/odoo/commit/44d4003f7f51d3472b0f38ada5261c4a2159a6cc

**Comment by sylvain-garancher** [comment]
I have mixed feelings about your WIP.

Reimplementing the methods, with a clear log line, seems to be a good idea. Even if I'd prefer to raise an error, as these methods are known to be broken, and I don't like the idea of hiding known bugs behind simple warnings in the log.
On the other hand, for modules that override using the old name, this won't help to detect the issue, as this override will often not be called.

Finally, I think that removing the aliases of renamed methods, keeping a comment somewhere to let the developers know how to convert their overriden method to the new name/arguments, is a better solution.
If someone has a traceback after upgrading... well, he'll know that he has a bug to fix.
This is better than discovering by chance that his datas are silently corrupted after several months, isn't it ?

**Comment by gdgellatly** [comment]
@sylvain-garancher you might want to test the fix.  I discovered this problem a few years ago in v7, where the issue was never responded to and we fixed almost identically to this.  You are presuming that

```
old_func = new_func
```
and 
```
def old_func
   return self.newfunc()
```
are identical.  I do not think they are.

**Comment by sylvain-garancher** [comment]
@gdgellatly Yes, I just wanted to say that this change didn't fix the issue of "not being warned about overriding a renamed method" :)

But, after a good night's sleep... removing the alias will not be better than replacing it by a method, as this will not help to let people know that the method shouldn't be overriden/declared anymore.

The only way to really warn about a broken module would be to prevent these method names from being used... but I don't know if it is possible.

**Comment by gurneyalex** [comment]
My take on this: a better way of handling would be to flag the method as removed in the first model definition by using a decorator for instance. Then the class machinery of Model (or maybe the underlying metaclass) would be able to detect inheriting model definition which define the removed method and this could produce an exception to prevent the installation of the addon attempting to override a removed method. 

The decorator would be kept for 1 or 2 LTS versions and then removed. 

This way of doing things is inspired from the way things are handled in cubicweb through the use of `logilab.common.deprecation` http://cubicweb.readthedocs.io/en/3.23/_modules/logilab/common/deprecation/ (code is LGPL so you can safely use it in Odoo core).

**Comment by JKE-be** [comment]
I think that we are debating about retro compatibility between version... What is not really the problem with this issue...

These 'alias' function should be just dropped. Odoo politic (not mine) is simple (it is not the debate here), no retro compatibility between version; but no changes in stable version.

So, we don't want support today the old function name.
But we cannot break the stable version, and make the instance crashed if somebody pull the code now.

So the warning is a _best effort_ to maybe draw the attention, but we don't want to support override of these old method.
In next versions, all these function will be just dropped, and if you still make some call to these old name, it should crash.

So, practically:
    - call old name will works in saas-11/saas-12/v10
    - overrides old function, have no effect
    - In saas-14, old function will be no more callable and that will crash if you call it.

**Comment by gurneyalex** [comment]
it's not really about retro compatibility, more about providing information for people who are migrating code that an api was removed. 

In this case, in saas-14, nothing will crash because the issue is that noone is calling the methods. 

I'm aware of the work overhead. Still i think it would be a great helper, including for people working internally at odoo.

**Comment by JKE-be** [comment]
@gurneyalex I'm really agree with you that migration between version is painful, and it is why every developer should think 2 times before to rename a function or a field without reason, just by beauty. 
Odony is the first to yell when he see it ;)

But in this issue, we just need to rename the 3/4 old overrides that have been not renamed to make standard odoo code working.
The other issue was to try to support (with a bad way, since it is quiet and not overridable), the old name. The warning added is always 'quite' but better that nothing.

And yes, it will be nice to have a 'How to migrate', or 'Technical release note' for migration... but that ask many time, and i'm not sure that Odoo have resource actually to do it... But it will be great for every body... Employee, Community, Developer,  ... I have no doubt about it.
