### ISSUE TITLE
[17.0]  "Create new Skills" button cause error. (Misnaming field name in the js code)

### ISSUE THREAD

**Issue by sakesun** [odoo/odoo#140859]
Impacted versions: 17

Steps to reproduce:
1. Visit Employee page when there is no Skills defined
2. There will be message "There are no skills defined in the libray. Why not try adding some ?"
3. Try clidk "Create new Skills"

Current behavior:
  There will be an error popup

Expected behavior:
  There should be no error popup

The error is caused by the mis-naming field in 
https://github.com/odoo/odoo/blob/17.0/addons/hr_skills/static/src/fields/skills_one2many/skills_one2many.js

`this.actionService` should all be replaced to just `this.action`

**Comment by vava-odoo** [comment]
Hi @sakesun 
Thanks for reporting.
It was fixed with https://github.com/odoo/odoo/pull/141132.
Cheers

**Comment by sakesun** [comment]
@vava-odoo I still see both this.action and this.actonService in the file:

https://github.com/odoo/odoo/blob/17.0/addons/hr_skills/static/src/fields/skills_one2many/skills_one2many.js

Why both is needed ?

**Comment by vava-odoo** [comment]
As was said [here](https://github.com/odoo/odoo/pull/141208#issuecomment-1795222877), `this.action` is not needed anymore and will be removed later.
