### ISSUE TITLE
[10.0c]Can not create inventory adjustment in multi-company mode?

### ISSUE THREAD

**Issue by jorsea** [odoo/odoo#14577]
Impacted versions:
Version 10.0c (Community Edition)

Steps to reproduce:

Configuration of the two companies A and B, A is the initial system of the company, B is a new company, B's parent company is A. 

Current behavior:
Can not create inventory adjustment in the B company?

Expected behavior:

Video/Screenshot link (optional):

I found the problem, please confirm:

 Location_id field definition   in   stock.inventory  of  V9.0c:
<`'location_id': fields.many2one('stock.location', 'Inventoried Location', required=True, readonly=True, states={'draft': [('readonly', False)]}),`>

V10.0c:
<location_id = fields.Many2one(
        'stock.location', 'Inventoried Location',
        readonly=True, required=True,
        states={'draft': [('readonly', False)]},
        default=lambda self: getattr(self.env.ref('stock.warehouse0', raise_if_not_found=False) or self.env['stock.warehouse'], 'lot_stock_id').id)>

**Because the default value. V9.0c is good, V10.0c can not be created. Please confirm, thanks?**

**Comment by mlaitinen** [comment]
Does 8955d15e9d92faa0e691fd432c0a644c246cf7ba fix your problem?

**Comment by DarkoNikolovski** [comment]
This fix should be added in [mrp.repair](https://github.com/odoo/odoo/blob/10.0/addons/mrp_repair/models/mrp_repair.py#L17) as well. Because the same issue happens there also.

**Comment by sle-odoo** [comment]
repair was also fixed with the rev cbee332bb129bf7e47ef5fbbf5ee898d963b57cd

thank you

**Comment by bunhin** [comment]
I have refresh the code with git pull, but why the error still happening (simillar case)  set up multi company and entry inventory adjustment this error still there now.
Please help to get the solution works
