### ISSUE TITLE
Webclient limits file uploads to 25 Mb

### ISSUE THREAD

**Issue by dreispt** [odoo/odoo#14824]
Impacted versions:
8.0 - 10.0

Steps to reproduce:
On a file field, upload a file larger than 25 Mb.

Current behavior:
A balloon warning message is given and the upload is not done.

Expected behavior:
Allow to perform the upload, at least on specific fields.

Video/Screenshot link (optional):
---

I traced this to a [hardcoded](https://github.com/odoo/odoo/blob/e91a8d428ff0ca953a7ed2967d3be3f518f05b49/addons/web/static/src/js/views/form_widgets.js#L1061) limit on the webclient.
Is there any technical reason for this limit?
Could we remove or override it, at least on specific cases, such as allowing an option on binary fields customizing this limit?

**Comment by Yenthe666** [comment]
Hmm +1.
I've encountered this before too. I'd personally would like to see it configurable under settings where you could set the maximum file size as you please.
 @mart-e can you give us some input?

**Comment by nhomar** [comment]
Limit this must be in nginx side not in app side, at least one specific model need such limit, I think this should be customizable per model or not wired (with a simple regex in nginx this is feasible).

**Comment by LeartS** [comment]
I doubt Odoo will work on this: it's a "bug" that affects only a small percentage of users, and it's trivial to solve with a customisation for those who really need it; while coming up with a general, "correct" solution would require much discussion and time. (as evinced by the fact that in 3 comments, there are already different opinions on what would be the correct way to set a max size 😛).

Maybe we could have better luck with a PR directly?

**Comment by Yenthe666** [comment]
@LeartS PR's always work better, Odoo likes them. The thing, however, is that if Odoo does not want to change the behaviour and you make a PR it'll be closed without mucher further dicussion.
So it is better to know that a PR would be accepted or has a chance before spending time on building it.

**Comment by nhomar** [comment]
It does not matter which way you pick, by any mean can be wired in the code (that's my opinion).

If odoo say "configurable" I use that, nginx "I use that" but "make a module" really piss me off.!

**Comment by dreispt** [comment]
I miss a comment from the R&D team here...

**Comment by Yenthe666** [comment]
So do I. I guess I'll just have to bother more people..
@mart-e, @JKE-be and @odony can any of you guys supply us with feedback please?

**Comment by Yenthe666** [comment]
@antonylesuisse I had a chat with Martin and this is probably for you he said.

**Comment by amigrave** [comment]
Back in time (2012), this limit was added because uploading a file bigger than ~30M would freeze chrome and/or firefox. This might be not relevant anymore today... should be tested.

**Comment by dreispt** [comment]
I just made a test on Firefox, uploading a 95 Mb attachment, and it worked great!

**Comment by amigrave** [comment]
Fixed in 402379a48a31bc486145e81d8dae2910ae446b48

**Comment by aristobulo-eezee** [comment]
Sadly you forgot to check everything
https://github.com/odoo/odoo/blob/10.0/addons/website_slides/controllers/main.py is still capped at 25 Mb
(/cc @amigrave )

**Comment by aristobulo-eezee** [comment]
also 
https://github.com/odoo/odoo/blob/10.0//addons/website_slides/static/src/js/slides_upload.js#L89

**Comment by aristobulo-eezee** [comment]
Check: https://github.com/odoo/odoo/issues/13223

**Comment by yucer** [comment]
> Is there any technical reason for this limit?

By the way, which is the maximum size allowed by **psycopg2.Binary** or **postgresql** ? 

Which would be the technical limit once Odoo doesn't impose one ?
