### ISSUE TITLE
[10.0] Severe performance issues on _inherits models

### ISSUE THREAD

**Issue by Cedric-Pigeon** [odoo/odoo#18511]
On large recordsets I got some severe performance issues while browsing through an inherits relation.
For example I have a batch process exporting a csv file with products variants:

I have to export 50.000 products.

If I do :
`variant.categ_id` It takes a very long time to get the result.

If I do:
`variant.product_tmpl_id.categ_id` The result is immediate

The problem is that the global perfomance of the application is impacted by this problem.

For example my POS takes more than 15 minutes to load. Because I have 26.000 products and the compute price method uses a lot browsing through the inherits such like `product.cated_id`, `product.uom_id` and they all takes a huge time to compute.

Same issue in this case.

If I do :
`variant.price` It takes a very long time to get the result.

If I do:
`variant.product_tmpl_id.price` The result is immediate

Could you help me ?

Simple way to reproduce:

1/ Create a new database and install sale module
2/ Launch following script through odoo shell :

```python
# -*- coding: utf-8 -*-
import logging

_logger = logging.getLogger(__name__)
self = self  # noqa

nb_product = 50000

i = 0
while i < nb_product:
    prod = self.env['product.template'].create({'name': 'product_%s' % i})
    i += 1
    if i % 1000 == 0:
        self.env.cr.commit()
        _logger.info("%s Products Created" % i)
```

2/ Launch following script through odoo shell :
```python
# -*- coding: utf-8 -*-
import logging

_logger = logging.getLogger(__name__)
self = self  # noqa


products = self.env['product.product'].search([])

for product in products:
    # Immediate response
    _logger.info('Category Template %s' % product.product_tmpl_id.categ_id)
    # Lagging response
    _logger.info('Category Variant %s' % product.categ_id) 
    break
```

**Comment by Cedric-Pigeon** [comment]
@rco-odoo Any idea about that ?

**Comment by Cedric-Pigeon** [comment]
OPW-760716

**Comment by Yenthe666** [comment]
@odony could you take the time to enlighten this? I'm curious about this too. Since you're very good in explaining performance problems and ORM topics I'd love to hear back from you.

**Comment by xmo-odoo** [comment]
@Cedric-Pigeon can you give #18644 a try? It should fix the issue.

**Comment by Cedric-Pigeon** [comment]
@xmo-odoo I made some quick tests and it looks very promising. I will do further indeep tests today and will keep you informed.

**Comment by Cedric-Pigeon** [comment]
@xmo-odoo For many2one, one2many and simple fields this fix is perfect. Unfortunatly I still have some issues with many2many. For some reasons it doesn't prefetch.
