### ISSUE TITLE
Cannot uninstall web_studio

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#19159]
Impacted versions: 10.0 ee

Steps to reproduce:
1. Install web_studio
2. Uninstall it

Current behavior:
```
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/module/wizard/base_module_upgrade.py", line 76, in upgrade_module
    odoo.modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/modules/loading.py", line 393, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/module/module.py", line 424, in module_uninstall
    self.env['ir.model.data']._module_data_uninstall(modules_to_remove)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/ir/ir_model.py", line 1350, in _module_data_uninstall
    undeletable += unlink_if_refcount(item for item in to_unlink if item[0] == 'ir.model.fields')
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/addons/base/ir/ir_model.py", line 1326, in unlink_if_refcount
    if field.name in models.LOG_ACCESS_COLUMNS and field.model in self.env and self.env[field.model]._log_access:
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/fields.py", line 972, in determine_value
    record._prefetch_field(self)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3066, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3010, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/models.py", line 3134, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/runbot/extra/runbot/static/build/258853-10-0-47cda5/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_model_fields.track_visibility does not exist
LINE 1: ...pe" as "ttype","ir_model_fields"."name" as "name","ir_model_...
                                                             ^
```

Expected behavior:

Module should be uninstalled.

Video/Screenshot link (optional):

Seems related to #19158, although stack trace is very different.

@Tecnativa

**Comment by Yenthe666** [comment]
@ged-odoo who is responsible for Odoo studio? This is indeed not okay.

**Comment by madhavcoder** [comment]
which os you are using that is also imp

**Comment by Yajo** [comment]
Linux, but OS doesn't matter here AFAIK... You can reproduce in runbot.

**Comment by Yenthe666** [comment]
Exactly - this has no relevance to this bug. It is reproducable on any OS.

**Comment by ged-odoo** [comment]
@Elkasitu is looking at uninstall problems.  He will take care of this

**Comment by Elkasitu** [comment]
Can't seem to reproduce in runbot, but the bug was reported 8 days ago and I introduced a fix 4 days ago that fixed these kind of issues in c5df78f

**Comment by Yenthe666** [comment]
It has indeed been fixed in the meanwhile - can't reproduce it anymore.

**Comment by Yajo** [comment]
Yeah, you're right @Elkasitu, although #19158 is still failing, maybe you can take a look at it
