### ISSUE TITLE
The email subject is empty when the text is in Greek

### ISSUE THREAD

**Issue by goutoudis** [odoo/odoo#20713]
Hi.

If the email subject is in Greek language, for example:
`Πρόσκληση της ${object.company_id.name} για σύνδεση στο Odoo`
which is his translation of: 
`${object.company_id.name} invitation to connect on Odoo`

I suggest the following change,
from:
https://github.com/odoo/odoo/blob/11a8728c743b3251912ea45dc57c960aa36bf1fe/odoo/addons/base/ir/ir_mail_server.py#L307
to:
`msg['Subject'] = encode_header_param(subject) `

Thanks

**Comment by Yenthe666** [comment]
Hi @goutoudis,

Why do you suggest this? Could you give more context and reasoning on why you would want to do this please?

**Comment by goutoudis** [comment]
Hi @Yenthe666 ,

The problem is the subject of email is empty when the text of subject is in Greek language.
The steps to produce the problem:
1. Install only the Greek language.
2. Invite new user with email
3. The subject of email is empty when i read it from my email client (Microsoft Outlook)

Here is a part of email headers:

Message-Id: <614782355116140.1509953375.274321317672729-openerp-21-res.users@192.168.1.3>
Subject: 
From: My Test Company <info@yourcompany.com>
Reply-To: My Test Company <info@yourcompany.com>`

If you make the change i suggest, the result is: 

Message-Id: <715374301050372.1509953564.611482381820679-openerp-22-res.users@192.168.1.3>
Subject: =?utf-8?b?zqDPgc+Mz4POus67zrfPg863IM+EzrfPgiBNeSBUZXN0IENvbXBhbnkgzrPOuc6xIM+Dz43Ovc60zrXPg863IM+Dz4TOvyBPZG9v?=
From: My Test Company <info@yourcompany.com>
Reply-To: My Test Company <info@yourcompany.com>

The subject id OK.

Thanks

**Comment by cuijinlin** [comment]
@goutoudis thanks!

i get the same error"The email subject is empty" in chinese with v11..
and then i change to:
msg['Subject'] = encode_header_param(subject)
The email subject is work well now.

**Comment by cuijinlin** [comment]
@goutoudis @Yenthe666 
it seem  "64    Header(header_text, 'utf-8')"  change to " return Header(header_text, 'utf-8')", work well now...

**Comment by celm1990** [comment]
I get same error, the email subject is empty. Language spanish Ecuador

**Comment by Yenthe666** [comment]
@xmo-odoo probably for you as it is encoding related.

**Comment by xmo-odoo** [comment]
Wow thanks for the ping @Yenthe666 

Yeaaah looks like @cuijinlin was on point here, `encode_header` would probably work better if it actually returned its value rather than encode it in the aether. Should be fixed in v11.

**Comment by fotisp** [comment]
Hello,

This is not fixed for Greek languages in v11, we have to keep a fork of the the 11.0 branch just for this change @goutoudis fix works but it is not in v11

**Comment by pedrobaeza** [comment]
Another issue, #27853, suggests that this problem may still exists.

**Comment by xmo-odoo** [comment]
@fotisp @pedrobaeza I just tested on the latest revision of the v11 branch, the user invitation email is properly sent with the correct headers:
```
Content-Type: multipart/mixed; boundary="===============2233268061515572807=="
MIME-Version: 1.0
Message-Id: <538953460779451.1539853304.131850004196167-openerp-6-res.users@yuricon-5.local>
Subject: =?utf-8?b?zqDPgc+Mz4POus67zrfPg863IM+EzrfPgiBNeSBDb21wYW55IM6zzrnOsSDPg8+Nzr3OtM61z4POtyDPg8+Ezr8gT2Rvbw==?=
From: My Company <info@yourcompany.com>
Reply-To: My Company <info@yourcompany.com>
To: ddd@kfdjsd.fr
Date: Thu, 18 Oct 2018 09:01:46 -0000
```
And the subject decodes to what's expected (assuming the translations are correct, I don't read greek):
> Πρόσκληση της My Company για σύνδεση στο Odoo

So the email subsystem issue seems to be fixed.
