### ISSUE TITLE
[11.0] Hr_Payslip: Error when contract.resource_calendar_id has declared a "Global Leaves"

### ISSUE THREAD

**Issue by elperrofarelo** [odoo/odoo#21343]
Impacted versions: 
[11.0]
Steps to reproduce: 
1- Introduce a Global Leave in contract.resource_calendar_id and fill up the contract. Create a pay slip, then in Worked Days the name for this global leave is empty. When we tray to save the pay slip comes following error: 
ERROR: null value in column "name" violates not-null constraint
2 - As well the Number of days calculated for a holiday period are wrong calculated if there is a Global Leave in between
Current behavior:

Expected behavior:

Video/Screenshot link (optional):

**Comment by RomainLibert** [comment]
Hello @elperrofarelo 
It seems that hr_payroll does not support global leaves
But fear not, this PR should fix it (https://github.com/odoo/odoo/pull/28956)

**Comment by Yenthe666** [comment]
@tivisse and @RomainLibert I believe you forgot to update the `.pot` file to make the new term translatable?
