### ISSUE TITLE
widget="selection" crashes editable list views - recent regression?

### ISSUE THREAD

**Issue by gdgellatly** [odoo/odoo#21547]
Impacted versions: 11.0

Steps to reproduce:
Have an editable list view with widget="selection" for an M2O field.
Create works just fine I think, mostly anyway, the problem is with edit (edit any field).  But it also can just spontaneously crash on load sometimes.
Removing widget="selection" everything works.
With widget="selection" traceback

I couldn't find an exact copy of this scenario in core, but in debug, if you go to Workorders list view in MRP, and edit it to be editable="bottom", it will insta reproduce as widget="selection" is in that tree.

The code that is crashing for me is a custom module written a few months ago that had been working fine, so I'm assuming it is a recent regression, but I don't visit that part very much.

Current behavior:
Error:
Uncaught TypeError: Cannot read property '0' of undefined

http://localhost:8076/web/static/src/js/fields/relational_fields.js:1994
Traceback:
TypeError: Cannot read property '0' of undefined
    at Class._renderEdit (http://localhost:8076/web/static/src/js/fields/relational_fields.js:1994:53)
    at Class._render (http://localhost:8076/web/static/src/js/fields/abstract_field.js:353:25)
    at http://localhost:8076/web/static/src/js/fields/abstract_field.js:187:25
    at http://localhost:8076/web/static/lib/jquery/jquery.js:3276:89
    at fire (http://localhost:8076/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://localhost:8076/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://localhost:8076/web/static/lib/jquery/jquery.js:3275:77)
    at Function.each (http://localhost:8076/web/static/lib/jquery/jquery.js:383:58)
    at Object.<anonymous> (http://localhost:8076/web/static/lib/jquery/jquery.js:3272:56)
    at Function.Deferred (http://localhost:8076/web/static/lib/jquery/jquery.js:3332:30)

Expected behavior:
Not that.  Its no major, easy to workaround with no create and no edit options.

@ged-odoo 

Video/Screenshot link (optional):

**Comment by jeroen7s** [comment]
any updates on this? is there a way to work around this?

**Comment by mge-odoo** [comment]
Sorry I forgot this issue. I'll take a look as soon as I have time (probably after the Odoo Experience).

**Comment by mge-odoo** [comment]
Hi @gdgellatly 

I have analysed the issue and it won't be solved in 11.0 as it implies a (too) big refactoring for a stable version.

The issue comes from the fact that the attribute `_fetchSpecialData` on widgets is not used for list datapoints (in the list view in this case). So all widgets using this attribute cannot be set in a multiple records view. The rational behind this is to avoid a lot of (useless) rpcs: one by widget by record (line) would be deadly. The correct solution would be to able to batch all `_fetchSpecialData` functions (both in JS and python) but as I said, this is a too big refactoring.

We will probably try to change this for the future version (@ged-odoo).

@gdgellatly were right about the workaround, it seems the best solution to me.

Regards,

Martin

**Comment by pedroslopez** [comment]
It seems this is still an issue on v12... will this be fixed? I see PR #27290 but has not been merged
