### ISSUE TITLE
Rounding / Formatting in Email Templates

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#22214]
Impacted versions: 
- v11

Steps to reproduce:
- Create a quotation amounting to 3,00 € net plus 19% Vat
- Amount total is 3,57 €
- Send this quotation by email

Current behavior:
- Email content is: "Here is the order confirmation [...] amounting in 3.5700000000000003 EUR" 

Expected behavior:
- Email content is: "Here is the order confirmation [...] amounting in 3.57 EUR"

Note:
- Same behavior with invoices, confirmations, etc. 
- Also, the separator and number of decimals is not as expected for currencies (e.g. 2.345,20 € will be displayed as 2345,2 €)

**Comment by Yenthe666** [comment]
Hi @haconsult,

Thanks for the bug report! I was having this at a customer too but it doesn't seem to happen all the time. Thanks to you I found a reproducable & reportable report:
![image](https://user-images.githubusercontent.com/6352350/34931655-1bffb71a-f9d0-11e7-8ab4-5a2f51e27b3e.png)
I've reported this with an official bug report. OPW 805370

Regards,
Yenthe

**Comment by haconsult** [comment]
Sorry, closed by accident.

**Comment by danger89** [comment]
I know transifex.com contains the translated strings, but the origin (English) string is stored within this repo?

**Comment by danger89** [comment]
@haconsult Could you test my change in my PR, which adds a round function to addons/account/models/account_invoice.py file? 

Or download the [patch file](https://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/22247.patch).

**Comment by Yenthe666** [comment]
@danger89 absolutely not a fix for the issue. 
1) Odoo uses their own rounding function (float_round) 
2) You should use a widget instead of a `round()`

I've made an OPW so Odoo will fix this anyways.

**Comment by danger89** [comment]
@Yenthe666 Take a look at the **new** Python 3 round function, maybe that could be a new float_round implementation?

**Comment by Yenthe666** [comment]
@danger89 that call is up to Odoo itself honestly. @mart-e for your interest.

**Comment by Yenthe666** [comment]
Hi @haconsult and @danger89,

It looks like the issue has been fixed in the meanwhile!
E-mail template:
![image](https://user-images.githubusercontent.com/6352350/35047013-fa8e86fe-fb98-11e7-8767-6bc03abc34bb.png)
Sale order:
![image](https://user-images.githubusercontent.com/6352350/35047024-028be6ee-fb99-11e7-8149-1b2b420ffd35.png)


Can you guys double check too?

**Comment by danger89** [comment]
@Yenthe666 
Well it is NOT fixed the Dutch language (I don't know about English). But I hoped they didn't solved this in the template actually.. because.., since now we need to update ALL translations.

![image](https://user-images.githubusercontent.com/628926/35056761-0dc46df0-fbb3-11e7-9642-aea1ec460946.png)

**Comment by Yenthe666** [comment]
Hmm, I'll double check in Dutch tommorow. I was in English so perhaps I've missed it because of that. ;)

**Comment by Yenthe666** [comment]
Ah yes, it is still present in Dutch..

**Comment by danger89** [comment]
Yea so I can change that directly. I'm a reviewer in transifex for the Dutch language. Just say what needs to be done..

**Comment by Yenthe666** [comment]
@danger89 don't handle it in the email templates. It should be handled on the Python side. It is probably a context or something missing :)

**Comment by haconsult** [comment]
Hi all,

Pleas note there was a [similar issue](https://github.com/odoo/odoo/issues/20784#issuecomment-347774424) in the stock (and possibly other?) modules. These have been addressed, e.g. the according pdf reports all work perfect now. To my understanding this issue here can only be fixed in the email templates and it's translations.

Regards, 
Helge

**Comment by hugho-ad** [comment]
Hi @Yenthe666 

Which is the status of the ticket 805370 related to this issue?

**Comment by Yenthe666** [comment]
Official response from Odoo S.A:

"
Hello,

I would suggest to modify the corresponding email template as done in https://github.com/odoo/odoo/pull/22510 (targets master branch).
Using "format_amount" will round and format correctly the amount. Unfortunately, we avoid changing this in stable since it breaks the translations.

See https://screenshots.firefox.com/pXvmS7ivuhZzayui/localhost for result.

Regards,
Nicolas"

**Comment by mart-e** [comment]
Fixed in master at https://github.com/odoo/odoo/commit/ee8e3d694002278f1ab8aedb431a12a05d39471f
