### ISSUE TITLE
[10.0] TypeError: odoo.define is not a function (empty CSS/JS assets)

### ISSUE THREAD

**Issue by thanglt0209** [odoo/odoo#22317]
Impacted versions:
Impacted versions: Odoo 10.0-20180115
Steps to reproduce:
A had build odoo 10 by Docker-compose.
one day,  odoo web container can't see filestore. I had create new web container and copy old file store to container volume and restore database. 
Current behavior:
It seem work. I  use the chrome incognito tab to log in. It work. But when i use normal tab  i get error Uncaught TypeError: odoo.define is not a function
Expected behavior:
I think it have old cookies so i had cleared cookies of this site. But it seem don't work
My logs is seem fine.
![image](https://user-images.githubusercontent.com/10916115/35075944-37984e04-fc39-11e7-8ced-41444d82c3d8.png)

Video/Screenshot link (optional):
incognito tab:
![image](https://user-images.githubusercontent.com/10916115/35075850-c7b6b184-fc38-11e7-9420-65c4f3058907.png)
Normal Tab:
![image](https://user-images.githubusercontent.com/10916115/35075898-fd118dae-fc38-11e7-8dfc-ca555966da3d.png)

**Comment by Elkasitu** [comment]
Could have something to do with the MIME-type issue @d-fence

**Comment by d-fence** [comment]
@thanglt0209 if you use windows as a client, it's probably related to this bug : https://github.com/odoo/odoo/issues/21319

It was fixed here in 10.0: https://github.com/odoo/odoo/commit/17c9208889d91d4302797d8f72a6ebc4968ff2e4

But unfortunately, the docker image is not yet up to date. There will be an update soon but I cannot give a date. There is a quick fix in the issue I mentioned above.

**Comment by thanglt0209** [comment]
@d-fence I had update docker image. But it still get error. maybe because i have not clear the browser cache yet.
Thanks everyone.
