### ISSUE TITLE
[9.0] Failed to read the 'rules' property from 'CSSStyleSheet':

### ISSUE THREAD

**Issue by thomas15v** [odoo/odoo#22517]
Impacted versions:
- 9.0
- Other odoo versions also act weird if you right click on a menu (tested community).

Steps to reproduce:
- In google chrome try to open your user preferences. Firefox does not seem to be impacted.
- Trying to edit any model
- Sometimes happens with wizards

Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/2163941/35387802-81adf3ca-01d1-11e8-8ec6-1951a8e426e7.png)
[![Screenshot from Gyazo](https://gyazo.com/2f1cf12a5d7848786394f5c614607a2c/raw)](https://gyazo.com/2f1cf12a5d7848786394f5c614607a2c)

**Comment by Yenthe666** [comment]
Hi @thomas15v,

Thanks a lot for your report.
I've just tried this on the latest Odoo 9 (community) on Chrome and Firefox and it seems to work fine.
Can you reproduce it on an official test instance (runbot.odoo.com)
Do you have custom plugins added that modify CSS?
Is your Odoo on the latest source code?
Which version of Chrome are you using?

Regards,
Yenthe

**Comment by thomas15v** [comment]
Forgot to mention that you need chrome Chrome 64.0.3282.119 akka the latest version. Updated rolled in yesterday.

**Comment by Yenthe666** [comment]
Seems to work fine at my end. CC @ged-odoo as it is JS related.

**Comment by thomas15v** [comment]
Just tried with a fresh google chrome without any addons, same problem. I actually knew about this bug a while longer since I use chrome beta, but I didn't thought it would make it to the stable version.

Also we have this error on every odoo version, when right clicking a link (menuitem in community).
[![Screenshot from Gyazo](https://gyazo.com/cc7a812992737aa92c3bb634abec08bf/raw)](https://gyazo.com/cc7a812992737aa92c3bb634abec08bf). 
I am not sure if they are related, but since it is happening with the same chrome version I think it might.

**Comment by cmarrero** [comment]
I can confirm the error with chrome 64

**Comment by jakubhruby** [comment]
#metoo
on ArchLinux
Firefox has not this problem

**Comment by ged-odoo** [comment]
difficult to say, but my first guess is that the addeventlistener crash is related to chrome, not odoo's code.  However, I don't know for  the other crash with cssstylesheet.

**Comment by ged-odoo** [comment]
does it happen for version 10/11?

**Comment by thomas15v** [comment]
- cssstylesheet: Only odoo 9
- Eventlister: On all versions (but I can't make it happen again since today, probably the extension that caused it is updated)

**Comment by travs-w** [comment]
Also having this problem on version 9. Confirmed to happen when trying to "Send by Email" on Invoices with Chrome v64.0.3282.119.

**Comment by aek** [comment]
Seems that basically, the issue is related to an empty CSS stylesheet introduced dynamically here:
[https://github.com/odoo/odoo/blob/9.0/addons/mail/static/src/js/announcement.js#L16
](url) in the format of:
```JS
_ab_location: function(dbuuid) {
    return _.str.sprintf('https://services.openerp.com/openerp-enterprise/ab/css/%s.css', dbuuid);
},
```
That js file does not introduce any useful feature for clients and it's returning an empty response - at least for non-enterprise database uuid - it's causing this issue with the chrome 64. That js file or the code it contains was removed for new versions of Odoo. Mostly that's the reason that you couldn't reproduce it in new versions

Still could be helpful to better catch the error here:
[https://github.com/odoo/odoo/blob/9.0/addons/web_editor/static/src/js/transcoder.js#L16](url)
to avoid this situation in the future

The most simple solution could be that Odoo S.A fix the CSS response of that file to at least one CSS Rule for that Ghost file
Another one could be simple extend (or manually find) the view record for mail assets to remove the line:
` <script type="text/javascript" src="/mail/static/src/js/announcement.js"/>`
Like this:
```xml
<template id="mail_assets_backend" name="mail assets" inherit_id="mail.assets_backend">
    <xpath expr="//script[@src='/mail/static/src/js/announcement.js']" position="replace"/>
</template>
```
I have tested that template extension to remove the inclusion of the announcement.js file and it seems like solving the issue at least in the detected scenario of the empty CSS file.

Talking about the solution for web_editor/static/src/js/transcoder.js you will need to remove the load of the original file and replace it with your fixed version. But I think that it won't be necessary if the previous patch fix completely the situation

Best Regards

**Comment by KottmannM** [comment]
I have the same problem with odoo 9 enterprise.

**Comment by wim-a** [comment]
We also have the same problem with Odoo 9 Enterprise.

**Comment by jithinkr12345** [comment]
Do we got any fix for this issue???

**Comment by MouTio** [comment]
It appears that there is a CSS resource which is missing and in Firefox is treated as a warning, but in Chrome is treated as an exception.

If you show the console of both browsers, you will see the messages.
Try to enter to "Preferences" or to edit a random user.

This is the error shown by Firefox console in runbot:
Can't read the css rules of: https://services.openerp.com/openerp-enterprise/ab/css/ddf53f40-028e-11e8-ab9c-a4bf011da6d8.css

**Comment by MouTio** [comment]
Okay, the solution is to change the code of **transcoder.js** located in **web_editor/static/src/js**:

The property "rules" is not well checked. 

This line is wrong (around line number 16):
`if (sheets[i].rules) {`

It has to be changed to this:
`if (sheets[i].hasOwnProperty('rules')){`

and the code will work fine in Chrome browser.

Please, verify it, @Yenthe666 @ged-odoo

**Comment by wim-a** [comment]
I installed this fix. Works fine. Thanks a lot.

**Comment by ThomasBinsfeld** [comment]
Same issue. @MouTio fix seems to work fine :+1:

**Comment by Yenthe666** [comment]
My co-worker created an official ticket for this with the number 813371

**Comment by MouTio** [comment]
@Yenthe666 What is an 'official ticket'?
Is it the same as PR?
I created my first PR to fix this bug:

https://github.com/odoo/odoo/pull/22603

**Comment by Yenthe666** [comment]
@MouTio an official bug report is one reported through odoo.com/help with your enterprise license key. It means that the issue moves up the list and gets a high(er) rating.

**Comment by remi-filament** [comment]
I have the same issue on Odoo CE v10 - I have created PR #22679 to address this issue on v10

**Comment by treviser** [comment]
I have the same issue on Odoo CE v11

**Comment by Yenthe666** [comment]
@ged-odoo any feedback? A dozen or so people are reporting this already.

**Comment by ronniescs** [comment]
I have the same issue on Odoo Ent v10

**Comment by mevivek4u** [comment]
I had the same issue with odoo9, but solved using the code given by @MouTio

**Comment by travs-w** [comment]
Agreed. The fix given by @MouTio resolves the problem on my end as well.

**Comment by ged-odoo** [comment]
issue fixed in 9.0 and 10.0.  Thank you everyone for your contribution/research/time/comments.

**Comment by treviser** [comment]
@ged-odoo Do you plan to fix it for 11.0 too, can I provide some help?

**Comment by aryeharmon** [comment]
still an issue Version 64.0.3282.119 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by treviser** [comment]
I'm using the same Google version as @aryeharmon on Ubuntu 17.10.

**Comment by thomas15v** [comment]
How do you make the issue happen in 11?

**Comment by jakubhruby** [comment]
@thomas15v for me it happens when I try to click "edit" website button on a page where there is no space for adding snippets. The code is on https://github.com/odoo/odoo/blob/11.0/addons/web_editor/static/src/js/widgets/widgets.js#L410

**Comment by Yenthe666** [comment]
@ged-odoo still reproducable at my end on Odoo V9 with Chrome 64.0.3282.140 too:
![image](https://user-images.githubusercontent.com/6352350/35902661-5cbf7c5e-0bdc-11e8-987b-18ae17988a3a.png)
I can trigger it from settings > email templates > opening an e-mail template and then clicking on the preview button.

**Comment by alexisheloir** [comment]
I also add to patch /web_editor/static/src/js/widgets.js l.552 to get the web editor widget working with the latest release of chrome.

        if (sheets[i].hasOwnProperty('rules')) {
            rules = sheets[i].rules;

**Comment by Yenthe666** [comment]
@treviser, @thomas15v and @jakubhruby can you still reproduce it? It seems to been fixed at my end as of today.

**Comment by lukebranch** [comment]
FWIW i've also run into this all of a sudden on a stable version 9.0 deployment. This deployment has been coasting along smoothly with no changes other than occasional odoo-server updates for around 12 months.

I will pull the latest code and confirm if this fixes the issue as well.

**Comment by xo2git** [comment]
@Yenthe666 /web_editor/static/src/js/widgets.js also contains this error. It is used by the front-end web editor.

`Uncaught DOMException: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
    at getCssSelectors (https://localhost/web/content/149290-d6b7fa2/web_editor.editor.js:142:89)
    at https://localhost/web/content/149290-d6b7fa2/web_editor.editor.js:145:120
    at Function._.each._.forEach (https://localhost/web/content/84972-e647506/web.assets_common.js:12:558)
    at https://localhost/web/content/149290-d6b7fa2/web_editor.editor.js:145:77
    at https://localhost/web/content/84972-e647506/web.assets_common.js:47:553
    at Class.init (https://localhost/web/content/149290-d6b7fa2/web_editor.editor.js:145:349)
    at Class.init (https://localhost/web/content/84972-e647506/web.assets_common.js:2537:371)
    at new Class (https://localhost/web/content/84972-e647506/web.assets_common.js:2535:65)
    at Class.init (https://localhost/web/content/149290-d6b7fa2/web_editor.editor.js:14:1468)
    at Class.prototype.(anonymous function) (https://localhost/web/content/84972-e647506/web.assets_common.js:2534:559)`

**Comment by certiz** [comment]
I applied first MouTio  solution and it fixed the problem partially, but it keep happening in some places. After  that I installed aek solution and it finish fixing the problem and know is working fine. 

I recommend to use both solutions for a complete fix.

Thank you guys for your great help

**Comment by MouTio** [comment]
@certiz @lukebranch @Yenthe666 

The solution is the same, but in different files. The bug was in more places but I only fixed it in the place where it crashed for me.

Now, it appears that they have fixed it in a stylish way, handling the exception with a try-catch:

a6e66131ce5b676ccc888ec5b1011d0946dc3907

If there is no more places with this bug, this issue is solved and it can be closed.

**Comment by jeremybramwell** [comment]
Just found this issue when researching my own bug caused by chrome's change to throw an error when trying to access cssRules/rules on sheets that are from a different origin.   I was going to try using .hasOwnProperty('rules') as a fix but it seems like all stylesheets return false for this.  I guess rules is an inherited property.   

So just a heads up that while it may prevent the exception that change may be breaking something else.

**Comment by gmarcon** [comment]
Same issue with Odoo CE 10.0-20171227 and Chrome 66.0.3359.181 (Official Build) (64-bit)

**Comment by determin1st** [comment]
You can put it in try...catch block to suppress browser warning and check that .rules property

**Comment by determin1st** [comment]
i dont even know what odoo is! just stucked in this notification. how to get out) backend is over, forget it! the future is for browser side

**Comment by jpaulin** [comment]
@ged-odoo I had similar error in Chrome with Odoo 10. Came down to removing a extension called **Loom** (video record / screen cap extension). When Loom was removed, Odoo no longer crashed.

**Comment by DanteMA** [comment]
Where is "web_editor/static/src/js" located?, Im using meteor framework and have searched manually in my project folders but with no avail.

**Comment by easternwawoman** [comment]
In case a noob arrives here, I fixed this prob in latest ver. Chrome by: (1) uninstalling and reinstalling LiveStyle ext in Chrome and then (2) disabling all extensions excet for LiveStyle.   The reinstall had no effect, based on usage.  Disabling extensions did create the change.  I have not turned all ext. back on so I have not pinpointed the conflict.  I did turn Google Voice on; no problem.  The other extensions were: Full page Screen Capture, CaptureCast; Checker5 Plus; Cryptonite MetaCert, Onetab and the WavesLiteApp.  Will update if I pinpoint the extension that created the conflict.

**Comment by cierek** [comment]
Are you sure you are running the latest release? I have customers running on Odoo 9 and 11 without any error since the update

**Comment by easternwawoman** [comment]
As I said in my post, I uninstalled and then reinstalled -- that reinstall was the download of latest version.  I also have the latest ver. of Chrome. While it's now syncing fine betwn Ch. browser and my IDE, it is still throwing the css files not found error: " Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules. "    I have turned back on extensions G. Voice, Checker Plus for GMail, and CSS Peeper with no impact.  Do need to turn on MetaCert and will test later on.

**Comment by pedrobaeza** [comment]
Better to start from a fresh DB.

**Comment by easternwawoman** [comment]
local server db, you mean?  If so, I use ServerPress's DesktopServer which
has a unique localhost domain ...eg... dev.cc is what we use.  Could that
be creating a conflict?  I wouldn't think so but ?

And I had DServer create a new site yesterday afternoon after the extension
change -- that's the site I'm working on this morning  is throwing the
error.  I checked other local sites here and they do the same.

Sheesh recreating db for 6 localhosted sites here would be a royal PIA
...and a hit of nonbillable time...  :-(

**Comment by pedrobaeza** [comment]
Well, I'm suggesting a method to try to debug the problem. First, to see if in a fresh DB, there's no problem. If so, then the problem is in the data inside the DB, and you get a way to work on.

**Comment by traviswaelbro** [comment]
Alternatively, if this is only an issue on your local setup, you should be able to just use Firefox and not have any issue. At least in my experience with this issue, the problem only happens in Chrome.

**Comment by easternwawoman** [comment]
Thanks for the help.

I'm not clear on why a fresh DB yesterday would be any different from one
today.   The CSS style error has been occurring for some time with other
local sites.  I just stopped using LiveStyle.   Retried recently  when
there was some time.  The extensions disabled caused it LiveS to work
again.

I had ServerPress deploy a new site yesterday afternoon after the extension
disable on the other site caused LiveS to work.

That SP deployment does create a new DB.

Style error persisted but LiveS does the updating betwn browser and
Sublime.  So, it's usable/does what I need it to do despite this:

*Error in event handler for runtime.onMessage: SecurityError: Failed to
read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules at
findStyleSheets
(chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/content-script.js:1014:12)
at
chrome-extension://diebikgmpmeppiilkaijjbdgciafajmg/scripts/content-script.js:1052:13*

Anyway, I think I'll just use this as it is and over time start looking at
what else is available.

I'm sinking in quicksand here from crazy workload; the ROI from fussing
with it is a business expense that's not worth it.  If I do find some free
time..maybe I'll fuss with it.  Dunno.  Just wanted to report this here.

I greatly appreciate you reaching out and taking from your time a moment to
help.  It's really been a sweet tool.

**Comment by easternwawoman** [comment]
TY.. will keep that in mind.  I don't like doing dev work in Firefox but
that's good to know.    Have a great day!
