### ISSUE TITLE
Domain operators `not ilike` and `!=` do not work as expected

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#22879]
Impacted versions: 9-11

## `not ilike`

Steps to reproduce:

1. Go to customers
2. Add an advanced filter: "Email - doesn't contain - example"

Current behavior: Customers without email don't appear.

Expected behavior: Customers without email should appear.

## `!=`

Steps to reproduce:

1. Go to customers
2. Add an advanced filter: "Email - is not equal to - example"

Current behavior: Customers without email disappear.

Expected behavior: Customers without email should still be there.

@Tecnativa

**Comment by gustavovalverde** [comment]
Have we all gotten this far with this?

**Comment by Yenthe666** [comment]
Euhh, wow, tested and does seem to be the case. We must be missing something here, no? 😕

**Comment by Yajo** [comment]
I imagine it must be the SQL "feature" of not validating any `NULL` value. I guess there should be a `COALESCE(field, '')` for doing these kind of tests in text fields.

I fixed downstream with this piece of code in a specific domain:

```python
from odoo.osv.expression import NEGATIVE_TERM_OPERATORS
# [... things ...]
        if operator in NEGATIVE_TERM_OPERATORS:
            domain = ["|", ("my_str_field", "=", False)] + domain
```

Quite ugly though.

**Comment by Yenthe666** [comment]
@odony and @xmo-odoo this is absolutely interesting for you two.

**Comment by andrp92** [comment]
This issue persist, and it's happening not only with email, but with products as well... any updates on this one ?

**Comment by andrp92** [comment]
PLEASE.!! we need this to be fixed ASAP.!! @Yenthe666 @odony @xmo-odoo

**Comment by gustavovalverde** [comment]
Any updates here?

**Comment by Yenthe666** [comment]
Sorry guys but no. I can't do much more than ping and bring it under the attention of the right people either. :(
Many are swamped with work for the V12 release.

**Comment by xmo-odoo** [comment]
It's true that this behaviour is unexpected (and not in line with `=` and `ilike`), after discussing with @odony we're definitely not going to change that in existing releases, and it's a bit too late in the v12 cycle for @odony's taste, so I'm going to change it in master.

Note that if you're aware of the issue (basically `!=` or `not ilike` on any non-required text field) you can work around it by tacking an "or <field> is not set".

**Comment by pedrobaeza** [comment]
@xmo-odoo does a patch for solving this arrived in master for v13 or is it still pending?

**Comment by pedrobaeza** [comment]
Possible fix in #33959

**Comment by alreadytakenn** [comment]
while i use 'not ilike' in xml, Odoo still throw this:
"Domain requirement,not ilike,1 uses an unsupported operator"
![图片](https://user-images.githubusercontent.com/47807894/59729380-d50e7e00-9270-11e9-8ce7-b64949423221.png)
