### ISSUE TITLE
[11] ODOO's Assets not loading, thus can't print, add product line to sales order (or any other view), call table many2one…

### ISSUE THREAD

**Issue by FlyingPigSolutions** [odoo/odoo#23468]
Impacted versions: 11 (production since 01.01.2018)
Ubuntu 16.04.3 x64 4 GB Memory / 30 GB Disk

Steps to reproduce:
(I assume it will, because the problem happened straight after this upgrade)
Installing Odoo 11 on Ubuntu 16.04.3 x64 1 GB 1 vCPU then upgrading to 4 GB 2 vCPU
(on March 1RST, 6PM42)

> I am quite not sure how this can be related. But the fact is that I have this blocking issue now.
> Back then, we also archived a user, realizing that it actually delete it. But I can't expect neither that could be related.

Current behavior:
Load Table to access table many2one, add products to sales order, Print etc…

Expected behavior:
Not loading table, js error, css error, icons not appearing, Qweb2 error

![screen shot 2018-03-05 at 11 53 15](https://user-images.githubusercontent.com/36439846/36971395-f9cd3236-206b-11e8-95b7-c761bd44d288.png)
![screen shot 2018-03-05 at 11 53 35](https://user-images.githubusercontent.com/36439846/36971396-f9eac940-206b-11e8-97c3-518db0f1780b.png)
![screen shot 2018-03-05 at 11 53 45](https://user-images.githubusercontent.com/36439846/36971397-fa05e572-206b-11e8-8a15-fafc88a38f7c.png)
![screen shot 2018-03-05 at 11 54 44](https://user-images.githubusercontent.com/36439846/36971461-2f5cd032-206c-11e8-926f-b73953fb6459.png)
![screen shot 2018-03-05 at 11 54 54](https://user-images.githubusercontent.com/36439846/36971463-2f7e338a-206c-11e8-86be-c75bb96e9ccf.png)
![screen shot 2018-03-05 at 11 55 21](https://user-images.githubusercontent.com/36439846/36971464-2f9d5f58-206c-11e8-9845-788e88c4d2a8.png)
![screen shot 2018-03-05 at 11 55 37](https://user-images.githubusercontent.com/36439846/36971465-2fba6f4e-206c-11e8-828e-7cec85a194a4.png)
<img width="148" alt="screen shot 2018-03-05 at 11 55 43" src="https://user-images.githubusercontent.com/36439846/36971466-2fd856f8-206c-11e8-8d50-64fe83c78f93.png">

My odoo 11 was working perfectly fine and after printing 27 invoices documents, we got an error:
Wkhtmltopdf error

Looking online I understand it is a lack of ram on our server.
We were initially working on Ubuntu 16.04.3 x64 1 GB Memory

So I updated our server to 4 GB Memory. That solved the printing issue but I realise now that we have an other issue.

From the web window localhost:8069/web?debug=assets I understand the issue seems to be elsewhere as assets are not loading correctly anymore.
Please note that buttons (save, new etc…) are still working.
So we can create products, contact to a certain extent but when we need to add line or access a table many2one it is not loading, thus not possible to do.

I updated python to version 3.5

I just happen to read a similar issue saying that it could be coming from python 3.5 although I do not understand why it comes now.
So I installed version 3.6.3 and pointed to the late version using:
`sudo update-alternatives --config python3
`
Please note that When I switch into developper mode, the page is blank:
`localhost:8069/web?debug=assets
`
I read online that switching to developper mode was solving this issue.
Well it doesn't in that case. Anyway that wouldn't be a solution neither.

Hello @Yenthe666 I am asking for your light on this.
I have read a couple of post that might be related to this, although it didn't bring me a solution.
I dunno. You might know better.
Thank you for your help.

**Comment by Yenthe666** [comment]
@FlyingPigSolutions do you have custom code or inherited the JS? Have you tried a -u all to reload all of the assets & files again?
P.S: What do you mean with "I  assume it will, because the problem happened straight after this upgrade"?

**Comment by FlyingPigSolutions** [comment]
hi @Yenthe666 
No custom codes.
can you precise the commande -u all to reload the asset.
I am afraid I am not familiar with it yet.

**Comment by FlyingPigSolutions** [comment]
I meant, the issue happened straight after upgrading our ubuntu server from 1GB to 4GB. So I assumed something went wrong from this change although I do not understand how it could be linked.

**Comment by FlyingPigSolutions** [comment]
@Yenthe666 While I tried to find online an answer, I ran this:
```
root@server-name:/# ./odoo.py -u all
-bash: ./odoo.py: No such file or directory
```
to refresh all i get this reply on ubuntu. Any idea?
Meanwhile I restarted the server and I can't get connection anymore:
`  File "/odoo/odoo-server/odoo/sql_db.py", line 404, in __exit__
    self.close()
  File "/odoo/odoo-server/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 288, in close
    return self._close(False)
  File "/odoo/odoo-server/odoo/sql_db.py", line 318, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
`
I use `/etc/init.d/odoo-server start ` and `/etc/init.d/odoo-server stop `
restart doesn't seem working

I even shutdown our server to see if that could have an effet rebooting everything with `sudo shutdown -h now `

I restarted the postgresql in case with `sudo /etc/init.d/postgresql restart `
then `sudo systemctl start odoo-server `

Not a change. Still can't connect back.

I am sure it is not much, but it blocks me so much. Drives me crazy.

I give a `sudo systemctl status odoo-server ` and it is active

To check services I ran `service --status-all `
with following result:
` [ + ]  acpid
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  atd
 [ - ]  bootmisc.sh
 [ - ]  checkfs.sh
 [ - ]  checkroot-bootclean.sh
 [ - ]  checkroot.sh
 [ + ]  console-setup
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  dbus
 [ + ]  grub-common
 [ - ]  hostname.sh
 [ - ]  hwclock.sh
 [ + ]  irqbalance
 [ + ]  iscsid
 [ + ]  keyboard-setup
 [ - ]  killprocs
 [ + ]  kmod
 [ - ]  lvm2
 [ + ]  lvm2-lvmetad
 [ + ]  lvm2-lvmpolld
 [ + ]  lxcfs
 [ - ]  lxd
 [ + ]  mdadm
 [ - ]  mdadm-waitidle
 [ - ]  mountall-bootclean.sh
 [ - ]  mountall.sh
 [ - ]  mountdevsubfs.sh
 [ - ]  mountkernfs.sh
 [ - ]  mountnfs-bootclean.sh
 [ - ]  mountnfs.sh
 [ + ]  networking
 [ ? ]  odoo-server
 [ + ]  ondemand
 [ + ]  open-iscsi
 [ - ]  open-vm-tools
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  postgresql
 [ + ]  procps
 [ + ]  rc.local
 [ + ]  resolvconf
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ - ]  sendsigs
 [ + ]  ssh
 [ + ]  sysstat
 [ + ]  udev
 [ + ]  ufw
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ + ]  unattended-upgrades
 [ + ]  urandom
 [ - ]  uuidd
 [ - ]  x11-common
`

My odoo-server got [ ? ]

**Comment by Yenthe666** [comment]
Hmm, there have been more quite similar issues about the psycopg2.. @xmo-odoo do you happen to have any idea?

**Comment by FlyingPigSolutions** [comment]
@Yenthe666 Thanks you answering.
I have indeed saw a similar issue online.
Is it possible that it could be related to commande `/etc/init.d/odoo-server`, `service` and/or command `systemctl`

> Can you enlighten me on this:
How to refresh the assets using the command `-u all`.

I saw you refer to this on an other post, but on my ubuntu it doesn't come out as expected.
I am sure i am doing something wrong.

```
root@server-name:/# ./odoo.py -u all
-bash: ./odoo.py: No such file or directory

```

**Comment by Yenthe666** [comment]
Hey,

For V10 it is odoo-bin instead of odoo.py. Plus I don't think you are running Odoo as your root user, you probably have a user such as "odoo" for this.

**Comment by FlyingPigSolutions** [comment]
Morning @Yenthe666 
thanks for your feedback
For the V10 I figured indeed it would be different.
What about V11? Seems it is not working with odoo-bin.
I'll dig a bit more in the meantime. Thanks
Let me know if you have a clue too

**Comment by FlyingPigSolutions** [comment]
Result for `/odoo/odoo-server/odoo-bin -u all`
```
root@NAME:~# /odoo/odoo-server/odoo-bin -u all
Running as user 'root' is a security risk.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/odoo/odoo-server/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/odoo/odoo-server/odoo/cli/server.py", line 175, in run
    main(args)
  File "/odoo/odoo-server/odoo/cli/server.py", line 124, in main
    odoo.tools.config.parse_config(args)
  File "/odoo/odoo-server/odoo/tools/config.py", line 334, in parse_config
    odoo.netsvc.init_logger()
  File "/odoo/odoo-server/odoo/netsvc.py", line 95, in init_logger
    resetlocale()
  File "/odoo/odoo-server/odoo/tools/translate.py", line 1183, in resetlocale
    for ln in get_locales():
  File "/odoo/odoo-server/odoo/tools/translate.py", line 1152, in get_locales
    lang = locale.getdefaultlocale()[0]
  File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

**Comment by FlyingPigSolutions** [comment]
ValueError: unknown locale: UTF-8

Then I ran: `export LC_ALL=en_US.UTF-8 `

**Comment by FlyingPigSolutions** [comment]
I ran once more the command `/odoo/odoo-server/odoo-bin -u all
`

**Comment by FlyingPigSolutions** [comment]
> Results:


```
Running as user 'root' is a security risk.
2018-03-06 07:07:07,599 10241 INFO ? odoo: Odoo version 11.0
2018-03-06 07:07:07,600 10241 INFO ? odoo: addons paths: ['/root/.local/share/Odoo/addons/11.0', '/odoo/odoo-server/odoo/addons', '/odoo/odoo-server/addons']
2018-03-06 07:07:07,601 10241 INFO ? odoo: database: default@default:default
2018-03-06 07:07:07,612 10241 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Exception in thread odoo.service.httpd:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/odoo/odoo-server/odoo/service/server.py", line 253, in http_thread
    self.httpd = ThreadedWSGIServerReloadable(self.interface, self.port, app)
  File "/odoo/odoo-server/odoo/service/server.py", line 106, in __init__
    handler=RequestHandler)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/odoo/odoo-server/odoo/service/server.py", line 116, in server_bind
    super(ThreadedWSGIServerReloadable, self).server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

2018-03-06 07:07:07,853 10241 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2018-03-06 07:07:07,988 10241 WARNING ? odoo.addons.base.res.res_currency: The num2words python library is not installed, l10n_mx_edi features won't be fully available.

```

**Comment by FlyingPigSolutions** [comment]
> I refreshed my page localhost:8069 but no change. Still got assets missing.
I am not sure from there if I have to restart the server to take effects.

**Comment by FlyingPigSolutions** [comment]
I open a new window terminal to check my logs live when I refresh my webpage using command:
`tailf /var/log/odoo/odoo-server`

My log shows: `POST /longpolling/poll HTTP/1.1" 200` with assets not correctly loaded

**Comment by FlyingPigSolutions** [comment]
> 2018-03-06 07:07:07,988 10241 WARNING ? odoo.addons.base.res.res_currency: The num2words python library is not installed, l10n_mx_edi features won't be fully available.
I run command to install it and update the rest:
`pip3 install Babel decorator docutils ebaysdk feedparser gevent greenlet html2text Jinja2 lxml Mako MarkupSafe mock num2words ofxparse passlib Pillow psutil psycogreen psycopg2 pydot pyparsing PyPDF2 pyserial python-dateutil python-openid pytz pyusb PyYAML qrcode reportlab requests six suds-jurko vatnumber vobject Werkzeug XlsxWriter xlwt xlrd`

**Comment by Yenthe666** [comment]
@FlyingPigSolutions your command actually failed for the -u all as your output is `[Errno 98] Address already in use`. You should first stop the service. Something along the lines of:
sudo service odoo-server stop
sudo su odoo
./odoo-bin -u all

**Comment by FlyingPigSolutions** [comment]
Thank @Yenthe666 

> For new at this like me I will describe a little my step by step. Maybe it can help others later.

So I run command `sudo service odoo-server stop `
I run command `sudo service odoo-server status ` (to check that server is indeed stopped)
then, I run `sudo su odoo ` to change user
then, I run `./odoo-bin -u all`

> Results:
```
Traceback (most recent call last):
  File "./odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "/odoo/odoo-server/odoo/cli/command.py", line 60, in main
    o.run(args)
  File "/odoo/odoo-server/odoo/cli/server.py", line 175, in run
    main(args)
  File "/odoo/odoo-server/odoo/cli/server.py", line 124, in main
    odoo.tools.config.parse_config(args)
  File "/odoo/odoo-server/odoo/tools/config.py", line 334, in parse_config
    odoo.netsvc.init_logger()
  File "/odoo/odoo-server/odoo/netsvc.py", line 95, in init_logger
    resetlocale()
  File "/odoo/odoo-server/odoo/tools/translate.py", line 1183, in resetlocale
    for ln in get_locales():
  File "/odoo/odoo-server/odoo/tools/translate.py", line 1152, in get_locales
    lang = locale.getdefaultlocale()[0]
  File "/usr/lib/python3.5/locale.py", line 558, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python3.5/locale.py", line 486, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

I run command `locale`

> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> LANG=en_US.UTF-8
> LANGUAGE=
> LC_CTYPE=UTF-8
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=

So I run commands: 
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

```

Results:

> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=en_US.UTF-8

Then I run again: `./odoo-bin -u all`

Results this time is running. It takes a while and got likes like this:

> 2018-03-06 07:47:10,528 11451 INFO YOU_DATABASE_NAME odoo.modules.loading: loading mail/views/mail_message_subtype_views.xml

Just got one error:

> 2018-03-06 07:46:00,290 11451 ERROR ? werkzeug: Error on request:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
>     execute(self.server.app)
>   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 168, in execute
>     application_iter = app(environ, start_response)
>   File "/odoo/odoo-server/odoo/service/server.py", line 252, in app
>     return self.app(e, s)
>   File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
>     return application_unproxied(environ, start_response)
>   File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
>     result = handler(environ, start_response)
>   File "/odoo/odoo-server/odoo/http.py", line 1297, in __call__
>     self.load_addons()
>   File "/odoo/odoo-server/odoo/http.py", line 1319, in load_addons
>     m = __import__('odoo.addons.' + module)
>   File "/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
>     exec(open(modfile, 'rb').read(), new_mod.__dict__)
>   File "<string>", line 5, in <module>

**Comment by Yenthe666** [comment]
@JKE-be didn't you recently fixed something along these lines with the rb rights on files?

**Comment by FlyingPigSolutions** [comment]
When it looked finished, i opened a new terminal window and run command `sudo service odoo-server start`
Go to my `localhost:8069` page and refresh
Oh god !
All is blank now…
![screen shot 2018-03-06 at 08 55 17](https://user-images.githubusercontent.com/36439846/37020494-39b9f48c-211c-11e8-9d70-4c5a7ce45425.png)

> The process looked finished though...

**Comment by Yenthe666** [comment]
@FlyingPigSolutions also post a screenshot of when you run it with `?debug=assets` in the URL and when you have the developer console of your browser open.

**Comment by JKE-be** [comment]
No recent changes about it, imho
Last trace back is not complete

**Comment by FlyingPigSolutions** [comment]
> On the `?debug=assets` (localhost:8069?debug=assets)
It reduced the number of errors from 275 to 159 now

![screen shot 2018-03-06 at 09 01 03](https://user-images.githubusercontent.com/36439846/37020783-5a1bdf0a-211d-11e8-992b-d8892d5a877e.png)
![screen shot 2018-03-06 at 09 01 27](https://user-images.githubusercontent.com/36439846/37020784-5a355160-211d-11e8-94b5-50ec12cda9b7.png)
![screen shot 2018-03-06 at 09 01 35](https://user-images.githubusercontent.com/36439846/37020785-5a4e0930-211d-11e8-9b03-9b3b0db85862.png)

**Comment by FlyingPigSolutions** [comment]
I'll try restarting the service and postgresql see if that makes a change

**Comment by JKE-be** [comment]
Which os !? Windows?

**Comment by FlyingPigSolutions** [comment]
I run command:
1# `sudo service odoo-server stop`
2# `sudo /etc/init.d/postgresql restart`
> [ ok ] Restarting postgresql (via systemctl): postgresql.service.
3# `sudo service odoo-server start`

Then refresh web
Not changing anything :/

**Comment by FlyingPigSolutions** [comment]
@JKE-be I run the web on Safari and Mac OS High Sierra

> Was working fine till 1rst of March (for 2 month).
> Server is on Ubuntu 16.04.3 x64 4 GB Memory / 30 GB Disk
> Assets went missing when we upgraded from 1 GB to 4 GB, although I am not sure it could be related but that it is only change that has been made and we suddenly got assets missing, right after it.

**Comment by JKE-be** [comment]
Serveur is running with nginx? 
Seems like your nginx don’t serve correct mime type according to the error in screenshot 

Jeremy Kersten

**Comment by FlyingPigSolutions** [comment]
@Yenthe666 NOPE it doesn't.
I expected you ask me this. Should have mentioned earlier, my bad.

> I intended it later but Not yet

> root@NAME:~# nginx --version
> The program 'nginx' can be found in the following packages:
>  * nginx-core
>  * nginx-extras
>  * nginx-full
>  * nginx-light
> Try: apt install <selected package>
>

**Comment by FlyingPigSolutions** [comment]
@Yenthe666 @JKE-be I read somewhere that by destroying the folder /static/ it will regenerates the link of the assets.
What do you think about this option?
Although I have a back up I can revert to anytime I prefer to ask your opinion. I never did it before so.

**Comment by FlyingPigSolutions** [comment]
@JKE-be Right... I thought so. That would have been to simple. Thanks 👍 
mimetype… Ic I'll dig into that.
Have you faced that kind of issue before? Any clue?

**Comment by JKE-be** [comment]
no, except on some windows that had a wrong registry

**Comment by FlyingPigSolutions** [comment]
@JKE-be Thanks 
Could this be a solution: [set mimetype on js and css assets #20731](https://github.com/odoo/odoo/pull/20731/files)? According to some comments it would. What do you think?
Although i don't understand as it was working fine before.
Maybe I should just reinstall the Odoo 11 from scratch but I have to check how to not loose my datas as we were in production for 2 month now :/

**Comment by JKE-be** [comment]
do you receive my mail ? I don't see it on github...

**Comment by FlyingPigSolutions** [comment]
hi @JKE-be 
I am not checking my mail now. Trying to solve this issue :/
Did you sent me one? You have my mail?
Let me check the static and revert to you here

**Comment by FlyingPigSolutions** [comment]
BTW I tried to reinstall the ODOO, see if it could turn things back, following guidelines from @Chris001:

> To be safe, you really should save a backup file containing your data currently stored in the odoo database, and upload it to a secure cloud account on a different machine than the odoo server, doing this will protect your data, in case of an unexpected event occurs:
> sudo pg_dump -U user_name database_name > backup_file
> This install script only installs (or reinstalls) the app and all its required dependencies + optional nginx web server + secure LE HTTPS cert.
> To answer your question, when you run the install script again, your data should remain untouched, the only thing updated on the database is the normal "database schema update" to match the new version of the Odoo code.
> Depending on if your odoo_install.sh is new enough, you can update itself to the newest version, in just one command: ./odoo_install.sh --self-update
> EDIT: You can also upgrade only the odoo code, with: ./odoo_install.sh --upgrade

But didn't produce any effective results.
So still digging into the mimetype

**Comment by JKE-be** [comment]
No, I don't have your email, I was replying by mail to notifications@github.com, but my mail doesn't show in this thread ;)

quoted in my previous post

waiting for your static file, but that seems to be your config and not odoo the problem, so you should post it on forum.odoo.com.

Btw, waiting your result for the mimetype of your static file.

**Comment by FlyingPigSolutions** [comment]
> @JKE-be : Can you try to access to a static file and provide the headers ?

```
GNU nano 2.5.3               File: res_config_settings.js                                      

odoo.define('base.settings', function (require) {
"use strict";

var core = require('web.core');
var config = require('web.config');
var FormView = require('web.FormView');
var FormController = require('web.FormController');
var FormRenderer = require('web.FormRenderer');
var view_registry = require('web.view_registry');

var QWeb = core.qweb;

var BaseSettingRenderer = FormRenderer.extend({
    events: _.extend({}, FormRenderer.prototype.events, {
        'click .tab': '_onSettingTabClick',
        'keyup .searchInput': '_onKeyUpSearch',
    }),

    init: function () {
        this._super.apply(this, arguments);
        this.activeView = false;
        this.activeTab = false;
    },

    start: function () {
        this._super.apply(this, arguments);
        if (config.device.isMobile) {
            core.bus.on("DOM_updated", this, function () {
                this._moveToTab(this.currentIndex || this._currentAppIndex());
            });
        }
    },

    /**
     * enable case insensitive search in jQuery contains function
     *
     * @private
     */
    _activeCaseInsensitiveSearch: function () {
        $.expr[':'].contains = function (a, i, m) {
            return $(a).text().toUpperCase()
                .indexOf(m[3].toUpperCase()) >= 0;
        };
    },
    /**
     * initialize modules list.
     * remove module that restricted in groups
     * data contains
     *  {
     *     key: moduel key
     *     string: moduel string
     *     imgurl: icon url
     *  }
     *
     * @private
     */

```

**Comment by FlyingPigSolutions** [comment]
> No, I don't have your email, I was replying by mail to notifications@github.com, but my mail doesn't show in this thread ;)
Didn't have to reply. So embarrassing lol :P my bad

**Comment by FlyingPigSolutions** [comment]
@JKE-be Could the strict mode be related?

**Comment by JKE-be** [comment]
Header from http layer ;) 

$ curl -I http://127.0.0.1:8069/web/static/tests/boot_tests.js

> HTTP/1.0 200 OK
> Date: Tue, 06 Mar 2018 15:33:26 GMT
> Etag: "wzsdm-1520008636-471-634717522"
> Cache-Control: max-age=604800, public
> Expires: Tue, 13 Mar 2018 15:33:26 GMT

> > Content-Type: application/javascript


> Content-Length: 471
> Server: Werkzeug/0.10.4 Python/3.5.2
>

**Comment by FlyingPigSolutions** [comment]
Not sure that is what you are asking for @JKE-be :

here is the log calling for our `localhost:8069/web/static/test/boot_tests.js`

```
2018-03-06 16:00:42,045 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:42] "GET /web/static/tests/boot_tests.js HTTP/1.1" 200 -
2018-03-06 16:00:43,186 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "POST /web/dataset/call HTTP/1.1" 200 -
2018-03-06 16:00:43,266 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "POST /website/translations HTTP/1.1" 200 -
2018-03-06 16:00:43,378 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:00:43,445 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "POST /web/dataset/call_kw/web_tour.tour/get_consumed_tours HTTP/1.1" 200 -
2018-03-06 16:00:43,579 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "GET /website/static/src/xml/website.xml HTTP/1.1" 200 -
2018-03-06 16:00:43,703 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:43] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:00:44,026 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:44] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.ttf?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:00:44,277 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:00:44] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.svg?v=4.7.0 HTTP/1.1" 200 -
```

An other different from your example : `localhost:8069/web/static/test/boot_tests.js`

```
2018-03-06 16:03:11,560 1581 INFO SERVER NAME werkzeug: 165.227.137.131 - - [06/Mar/2018 16:03:11] "POST /xmlrpc/2/object HTTP/1.0" 200 -
2018-03-06 16:03:32,789 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:32] "GET /web/static/tests/views/view_dialogs_tests.js HTTP/1.1" 200 -
2018-03-06 16:03:33,094 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "POST /web/dataset/call HTTP/1.1" 200 -
2018-03-06 16:03:33,164 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "POST /website/translations HTTP/1.1" 200 -
2018-03-06 16:03:33,271 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:03:33,343 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "POST /web/dataset/call_kw/web_tour.tour/get_consumed_tours HTTP/1.1" 200 -
2018-03-06 16:03:33,462 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "GET /website/static/src/xml/website.xml HTTP/1.1" 200 -
2018-03-06 16:03:33,576 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:03:33,882 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:33] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.ttf?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:03:34,160 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:34] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.svg?v=4.7.0 HTTP/1.1" 200 -
2018-03-06 16:03:43,044 1581 INFO Server.Name werkzeug: 80.26.222.163 - - [06/Mar/2018 16:03:43] "POST /longpolling/poll HTTP/1.1" 200 -

```

**Comment by FlyingPigSolutions** [comment]
@JKE-be Gosh I am tired. Here it goes:

HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Set-Cookie: session_id=62cad877e8acd374a7185cd1977871cb409a0351; Expires=Mon, 04-Jun-2018 17:13:46 GMT; Max-Age=7776000; HttpOnly; Path=/
Content-Length: 8533
Server: Werkzeug/0.10.4 Python/3.5.2
Date: Tue, 06 Mar 2018 17:13:46 GMT

**Comment by chris001** [comment]
Bingo. 
@JKE-be guessed right, 
The bug is `Werkzeug` is returning `Content-Type: text/html; charset=utf-8` to the browser, for the javascript files.  
The browser needs to receive `Content-Type: application/javascript; charset=utf-8` to display the page correctly, see IETF requirements for javascript mime type.
Reference: https://tools.ietf.org/html/rfc4329

**Comment by FlyingPigSolutions** [comment]
Thanks @JKE-be @chris001 
Now that you say it is indeed in front of my nose 👍 

> Content-Type: text/html; charset=utf-8

I was checking with `mimetype dialog.js` command if it was read correctly but I guess the information sent is not.

now that said, I am not clear where to make the change.
I looked into `/etc/mime.types` and javascript looks fine.
Well I must get it wrong for sure lol otherwise I won't be stucked there

**Comment by chris001** [comment]
Why is odoo 11 using such an ancient dusty version of `werkzeug` package, 0.10.4 it's 2 years old?!
The latest version 0.14.1 has fixed about 100 bugs compared to 0.10.4. 
Many fixed bugs refer to MIME types, which is the cause of this issue.
@FlyingPigSolutions 
Upgrade `werkzeug` to the current version 0.14.1 should probably fix this MIME-type issue.
* https://github.com/pallets/werkzeug/issues
* https://pypi.python.org/pypi/Werkzeug
* https://www.palletsprojects.com/p/werkzeug/
* http://werkzeug.pocoo.org/docs/0.14/changes/

**Comment by FlyingPigSolutions** [comment]
Thanks @JKE-be @chris001 
Now that you say it is indeed in front of my nose 👍 

> Content-Type: text/html; charset=utf-8

I was checking with `mimetype dialog.js` command if it was read correctly but I guess the information sent is not.

**Comment by FlyingPigSolutions** [comment]
yes you are right @chris001 
Ok I'll do and let you know.

**Comment by FlyingPigSolutions** [comment]
So I run command `pip install -U Werkzeug`

> Collecting Werkzeug
>   Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
>     100% |################################| 327kB 2.4MB/s 
> Installing collected packages: Werkzeug
>   Found existing installation: Werkzeug 0.10.4
>     Uninstalling Werkzeug-0.10.4:
>       Successfully uninstalled Werkzeug-0.10.4
> Successfully installed Werkzeug-0.14.1

**Comment by FlyingPigSolutions** [comment]
Hi @chris001 
Ok the issue is persistant.

I downloaded and reboot server in case using command:
`sudo service odoo-server stop`
`sudo shutdown -h now`

Then start it again.

When to my localhost:8069 and refreshed. I empty the cash too in case.

The issue being there still,
I run command `curl -I http://localhost:8069/web/static/tests/views/view_dialogs_tests.js`

> HTTP/1.0 200 OK
> Content-Type: text/html; charset=utf-8
> Set-Cookie: session_id=99a3ed895fb99bc8ac51431892ce0d9a3328c327; Expires=Mon, 04-Jun-2018 19:12:48 GMT; Max-Age=7776000; HttpOnly; Path=/
> Content-Length: 8589
> Server: Werkzeug/0.14.1 Python/3.5.2
> Date: Tue, 06 Mar 2018 19:12:48 GMT

Still got this little friend there:
> Content-Type: text/html; charset=utf-8

**Comment by FlyingPigSolutions** [comment]
did I missed something?

**Comment by chris001** [comment]
On my server, odoo 11, which was installed using my "Big Update" version of the script `odoo_install.sh`:
```
curl -I http://localhost:8069/web/static/tests/views/view_dialogs_tests.js
HTTP/1.0 200 OK
Date: Tue, 06 Mar 2018 19:29:08 GMT
Etag: "wzsdm-1519702772-7757-1606420635"
Cache-Control: max-age=604800, public
Expires: Tue, 13 Mar 2018 19:29:08 GMT
**Content-Type: application/javascript**
Content-Length: 7757
Server: Werkzeug/0.14.1 Python/3.5.2
```

**Comment by FlyingPigSolutions** [comment]
wow I see.
Well how can i update my version with yours then 👍 ?

**Comment by chris001** [comment]
1. Take backup of your data, to be safe. 👍 
`sudo pg_dump -U user_name database_name > backup_file`
2. Run my install script over your existing installation. Should work just fine.
```
cd ~ 
rm odoo_install.sh 
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh 
chmod +x odoo_install.sh 
./odoo_install.sh
```
3. Read about the command line options:
`./odoo_install.sh --help`
4. Highly recommended: install with command line option Nginx web server + free LE HTTPS cert 👍 
```
./odoo_install.sh --nginx --email=you@youremail.com --domain=yourdomain.com
```

**Comment by FlyingPigSolutions** [comment]
haha you were faster than me. Was looking for your message back then in the other post.
Ok I'll try that now. Thanks a millions @chris001 👍

**Comment by FlyingPigSolutions** [comment]
> df: /home/odoo: No such file or directory
> Odoo Installer version 2018-02-26a
> by Yenthe Van Ginneken and Chris Coleman (EspaceNetworks).
> System Memory detected: 2000 MB
> Free space on /home/odoo : 
> Installing: Odoo 11.0 Community to /home/odoo/odoo-server
> ---- 1. Stop odoo server (if running) ----
> ---- 2. Update operating system ----
> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
> ---- 3. Installing Nginx + LE HTTPS cert (email: name@mydomain.com domain: mydomain.com ) ----
> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
>

**Comment by chris001** [comment]
Your ubuntu server is busy self-updating packages in the background (`apt` + `dpkg`).  
Wait 2 min until it completes, then run again.

**Comment by FlyingPigSolutions** [comment]
I am too impatient then. Thanks

**Comment by FlyingPigSolutions** [comment]
now it seemed going smooth.

Just got failed authorisation issue:

> Running post-hook command: systemctl start nginx
> Failed authorization procedure. DOMAIN.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://DOMAIN.com/.well-known/acme-challenge/CNo9vWD79pVfTKHR3JLAHZug3pSttMzyCr6p_j08HWE: "
> 
> <!doctype html>
> 
> <!--[if IE 7]><html class="n"

**Comment by FlyingPigSolutions** [comment]
besides that authorisation issue that don't block me right now to access to our localhost:8069, should I restart the server to update the service?
Coz I still have on .js file:

> Content-Type: text/html; charset=utf-8

**Comment by FlyingPigSolutions** [comment]
After installation, when I run command `sudo service odoo-server status` i get this:

FAILED STATUS 👎 

> ● odoo-server.service - odoo-server (Odoo 11.0 Community)
>    Loaded: loaded (/etc/systemd/system/odoo-server.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2018-03-06 20:37:44 UTC; 1s ago
>   Process: 11761 ExecStart=/usr/bin/python3 /home/odoo/odoo-server/odoo-bin -c /etc/odoo/odoo-server.conf (code=exit
>  Main PID: 11761 (code=exited, status=1/FAILURE)
> 
> Mar 06 20:37:43 NAME odoo-server[11761]:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py",
> Mar 06 20:37:43 NAME odoo-server[11761]:     import OpenSSL.SSL
> Mar 06 20:37:43 NAME odoo-server[11761]:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, 
> Mar 06 20:37:43 NAME odoo-server[11761]:     from OpenSSL import rand, crypto, SSL
> Mar 06 20:37:43 NAME odoo-server[11761]:   File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 118, in 
> Mar 06 20:37:43 NAME odoo-server[11761]:     SSL_ST_INIT = _lib.SSL_ST_INIT
> Mar 06 20:37:43 NAME odoo-server[11761]: AttributeError: module 'lib' has no attribute 'SSL_ST_INIT'
> Mar 06 20:37:44 NAME systemd[1]: odoo-server.service: Main process exited, code=exited, status=1/FAILURE
> Mar 06 20:37:44 NAME systemd[1]: odoo-server.service: Unit entered failed state.
> Mar 06 20:37:44 NAME systemd[1]: odoo-server.service: Failed with result 'exit-code'.
> 

I still had locale issues that you mentioned in your other post.
I tried to solved it with command:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

Then i run command `./odoo_install.sh --self-update`

**Comment by FlyingPigSolutions** [comment]
Thanks for your help @chris001 

> I'll continue digging tomorrow. It's late here.
> Enjoy your day forward

**Comment by chris001** [comment]
For your LE HTTPS cert error, it seems most likely the problem is with challenge validation over IPv6.  
* Check your IPv6 records for your domain.  They must either be work ie your server reachable over IPv6 on ports 80 http and 443 https (best), or the IPv6 records removed (less preferable).

**Comment by JKE-be** [comment]
@FlyingPigSolutions 

About werkzeug, it is because Debian is limited to 0.11 (https://packages.debian.org/stretch/python-werkzeug)
Btw, it should work with 0.14 in your case (but that should work with 0.10 without any problem!)

Reinstall all was probably not the faster fix ;)

**Comment by FlyingPigSolutions** [comment]
@chris001 Thanks a lot !
Good news. We are back online !!! All data safe too as you can assume !
Thanks a millions guys @Yenthe666 @JKE-be @chris001

**Comment by Yenthe666** [comment]
Happy to hear it is solved! Best of luck with Odoo.

**Comment by FlyingPigSolutions** [comment]
So basically we have less error. Used to have 275. Now 38. So lots of things are back online.
Some a still missing.

**Comment by JKE-be** [comment]
Screenshot 1/2: the code doesn't match to the db...
Are you sure you reinstall the same version?

Screenshot 3: long pooling misconfigured

**Comment by FlyingPigSolutions** [comment]
I checked again doing command : `curl -I http://localhost:8069/web/static/tests/views/view_dialogs_tests.js`

> HTTP/1.0 200 OK
> Date: Wed, 07 Mar 2018 09:03:18 GMT
> Etag: "wzsdm-1520408236-9106-1606420635"
> Cache-Control: max-age=604800, public
> Expires: Wed, 14 Mar 2018 09:03:18 GMT
> Content-Type: application/javascript
> Content-Length: 9106
> Server: Werkzeug/0.10.4 Python/3.5.2
> 

I saw that the Werkzeug version is still an old one.

I ran `pip install -U Werkzeug`

> > Collecting Werkzeug
>   Downloading Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
>     100% |################################| 327kB 2.5MB/s 
> Installing collected packages: Werkzeug
>   Found existing installation: Werkzeug 0.10.4
>     Uninstalling Werkzeug-0.10.4:
>       Successfully uninstalled Werkzeug-0.10.4
> Successfully installed Werkzeug-0.14.1
> 

I'll let you know the result soon

**Comment by FlyingPigSolutions** [comment]
@JKE-be I reinstalled from @chris001 ODOO 11's version

**Comment by Yenthe666** [comment]
To be honest, this has nothing to do with bugs anymore and is all about deployment. I'm closing this bug report as it is clear multiple things are wrongly deployed/configured instead of a bug in Odoo.
Discussion can still continue though.

**Comment by FlyingPigSolutions** [comment]
ok Thanks @Yenthe666

**Comment by FlyingPigSolutions** [comment]
I am not quite clear @JKE-be regarding versions.
Do you mean that it exists different versions of ODOO 11 Community?

**Comment by JKE-be** [comment]
no ! only 1 version of v11.

So if you are sure that you was in v11, and reinstall in v11... that should be another thing.

**Comment by JKE-be** [comment]
what is the state of the module Gamification in your database ?

**Comment by FlyingPigSolutions** [comment]
100% Sure both were V11, from different source, but that shouldn't be a case right? Or could it be?

@JKE-be What do you mean by state? Not following you? How can I check it?

I have run `locate -i Gamification` and there is a couple of directory
including `/odoo/odoo-server/addons/gamification`

> Sorry I may ask dumb question time to time. I am new at this one.
> I detail everything for the next newbie that encounter the same issue one day :P

**Comment by FlyingPigSolutions** [comment]
BTW @chris001 dunno why but the locale were still not fixed.
I had to fix it again after installation.

**Comment by JKE-be** [comment]
in the backend, in your list of apps of Odoo :)

**Comment by FlyingPigSolutions** [comment]
Ohhh
now I now what it didn't ring a bell. I don't recall installing this.
Is it a requirement?
![screen shot 2018-03-07 at 19 12 36](https://user-images.githubusercontent.com/36439846/37109863-98ade58c-223b-11e8-8bb2-27250fab0eba.png)

**Comment by JKE-be** [comment]
No :/ it was not installed before so it shouldn’t !

But strangly, the error in your first screenshot is about a field from this module gamification from memory

**Comment by JKE-be** [comment]
Do you have others module in a state != than installed/not installed ?

**Comment by FlyingPigSolutions** [comment]
well I should look in the terminal for that.
Can you just confirm me that if the app is not installed, it shouldn't be in the directory list. 

Here is the screen of the app we have installed.
Basically we kept it rather simple to not mess up ODOO.
Unfortunately not all is good in odoo so we use other software as well. You can imagine.
![screen shot 2018-03-07 at 19 53 31](https://user-images.githubusercontent.com/36439846/37111906-457646ec-2241-11e8-882b-cd95ba639f50.png)

**Comment by FlyingPigSolutions** [comment]
Well would it be a bad idea to remove the directory of gamification?

**Comment by JKE-be** [comment]
No remove it is not the solution ;)

**Comment by JKE-be** [comment]
You have custom module into Odoo !?

**Comment by JKE-be** [comment]
Problem is about the field 'report_template_id' on res_company from module biztech_report_template (and not gamification)!
Check that your module is still present in your addons-path. Check your logs will help you !

If you have smthing similar to "WARNING maison.txxxx odoo.modules.graph: module biztech_report_template: not installable, skipped", the answer is NO :/

My two cents (that will not fix your bug but should probably be considered) is that :
the . in your database name is probably not the best choice, even if it should works.
Your database manager is not secure, change or set to empty your master pwd.



Good luck

**Comment by chris001** [comment]
@JKE-be 
It would be really nice to catch these exceptions and show a nice error message to to users, for example: "`Res_company` requires module `biztech_report_template`, and it's missing, please install it, click here: (link to modules page)"

**Comment by JKE-be** [comment]
@chris001 

It is already the case ... it is in WARNING in the log, or in yellow in the console.
It is not an exception, we explicitly show the WARNING to the "sysadmin".

**Comment by FlyingPigSolutions** [comment]
Hi @JKE-be Sorry didn't see you message yesterday. Was tired and went off earlier.
I'll dig into your guidelines and let you know. Today or tomorrow I'll have more time

**Comment by FlyingPigSolutions** [comment]
BTW to answer you, I have installed this template app biztech to generate nicer invoice template.
However, I had to redesign the templates from scratch as it was not coming out as expected.
Very hard to judge from the app store how things will come out.
Anyway, Maybe I should just remove it, and keep the original templates from Odoo.

**Comment by FlyingPigSolutions** [comment]
BTW @chris001 this is the message I get when I connect to our ODOO (see attache screenshot)
I don't know if that is useful.
![screen shot 2018-03-08 at 09 39 48](https://user-images.githubusercontent.com/36439846/37141263-c0e8304c-22b4-11e8-9080-74818cf2cfe2.png)

**Comment by FlyingPigSolutions** [comment]
Anyway guys I'll dig into your last hint and revert to you. Thanks again

**Comment by FlyingPigSolutions** [comment]
@JKE-be 
To answer you. Biztech app appeared installed.
![screen shot 2018-03-08 at 17 41 34](https://user-images.githubusercontent.com/36439846/37165736-a5c6bb32-22fd-11e8-8d0c-0621703eb315.png)
![screen shot 2018-03-08 at 17 41 45](https://user-images.githubusercontent.com/36439846/37165739-a5f19f82-22fd-11e8-9939-426ccc563559.png)
But as you guessed there is an error in the log.
FIRST, on the log it shows : module not found

> 2018-03-08 16:41:39,209 8844 WARNING db.Name odoo.modules.module: module biztech_report_template: module not found
> 2018-03-08 16:41:39,211 8844 WARNING db.Name odoo.modules.module: module biztech_report_template: module not found
> 

SECOND, I got this error keeping going on.
I think its a matter of directory with /home/ that was not set like this in my first install:

> Contexte de l'erreur :
> Vue `res.partner.form`
> [view_id: 112, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]
> 2018-03-08 17:23:57,238 8844 INFO db.Name werkzeug: 80.26.222.163 - - [08/Mar/2018 17:23:57] "POST /web/dataset/call_kw/res.partner/load_views HTTP/1.1" 200 -
> 

> 2018-03-08 16:46:58,569 8483 ERROR db.Name odoo.http: Exception during JSON request handling.
> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/home/odoo/odoo-server/odoo/http.py", line 689, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/odoo/odoo-server/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/odoo/odoo-server/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/home/odoo/odoo-server/odoo/http.py", line 933, in __call__
>     return self.method(*args, **kw)
>   File "/home/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo/odoo-server/addons/bus/controllers/main.py", line 37, in poll
>     raise Exception("bus.Bus unavailable")
> Exception: bus.Bus unavailable

I see also this :

> ValueError: Le champ `report_template_id` n'existe pas
Meaning: Field "report_template_id" does not exist.

For sure.
There is now 2 paths now created:
1# /odoo/odoo-server/addons
2# /home/odoo/odoo-server/addons

So as biztech is installed, i guess it in #1 and not in #2 (the new one) 

> drwxr-xr-x  24 root root  4096 Mar  7 07:20 ./
> drwxr-xr-x  24 root root  4096 Mar  7 07:20 ../
> drwxr-xr-x   2 root root  4096 Mar  7 07:27 bin/
> drwxr-xr-x   4 root root  4096 Mar  7 07:34 boot/
> drwxr-xr-x  17 root root  3600 Mar  7 07:20 dev/
> drwxr-xr-x 103 root root  4096 Mar  7 07:39 etc/
**> drwxr-xr-x   3 root root  4096 Mar  7 07:34 home/**
> lrwxrwxrwx   1 root root    33 Feb 23 06:21 initrd.img -> boot/initrd.img-4.4.0-116-generic
> lrwxrwxrwx   1 root root    33 Jan 23 06:36 initrd.img.old -> boot/initrd.img-4.4.0-112-generic
> drwxr-xr-x  22 root root  4096 Jan  7 18:33 lib/
> drwxr-xr-x   2 root root  4096 Jan 19 06:59 lib64/
> drwx------   2 root root 16384 Jan  5 18:12 lost+found/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 media/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 mnt/
**> drwxr-xr-x   6 odoo odoo  4096 Mar  7 07:42 odoo/**
> drwxr-xr-x   3 root root  4096 Jan  7 17:57 opt/
> dr-xr-xr-x 148 root root     0 Mar  7 07:20 proc/
> drwx------   8 root root  4096 Mar  7 07:39 root/
> drwxr-xr-x  26 root root   980 Mar  8 16:36 run/
> drwxr-xr-x   2 root root 12288 Mar  7 07:27 sbin/
> drwxr-xr-x   2 root root  4096 Nov 30 19:48 snap/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 srv/
> dr-xr-xr-x  13 root root     0 Mar  7 09:54 sys/
> drwxrwxrwt  10 root root  4096 Mar  8 17:17 tmp/
> drwxr-xr-x  10 root root  4096 Jan  5 17:58 usr/
> drwxr-xr-x  13 root root  4096 Jan  5 18:01 var/
> lrwxrwxrwx   1 root root    30 Feb 23 06:21 vmlinuz -> boot/vmlinuz-4.4.0-116-generic
> lrwxrwxrwx   1 root root    30 Jan 23 06:36 vmlinuz.old -> boot/vmlinuz-4.4.0-112-generic
> 

Just one question @JKE-be or @chris001 Can I correct the path with command `mv` for instance or may it mess up everything doing like that?

**Comment by FlyingPigSolutions** [comment]
Uninstalling the APP in question seems to pretty much solve most of the issue.

**Comment by JKE-be** [comment]
> Unfortunately not all is good in odoo so we use other software as well. You can imagine.

**Comment by FlyingPigSolutions** [comment]
> Well sincerely speaking after implanting few ERP in my life from Microsoft Dynamics to SAP and other one, ODOO is doing a pretty good work in many fields. Of course not all is perfect but as soon as it goes improving its all good.

I'll make a back up before installing our next APP, because too much risk of a broken path or anything of the sort

**Comment by FlyingPigSolutions** [comment]
Thank you very much guys again @chris001 @Yenthe666 @JKE-be 
Very much appreciated.
From what I learned I'll try to go on my own now.
If there is an other wall I'll ask you for lights again if you don't mind.

**Comment by chris001** [comment]
@FlyingPigSolutions 
Yes I think the cause of this error was the odoo_install script didn't check the previous existing Community modules path for this installed instance of odoo 11, and either delete it if it was the unmodified copy from github, or move it to the new intended destination, `/home/odoo`.
Overall, the best fix would be to make Odoo itself more resilient, and to not die so abruptly and so cryptically when it faces addons directory issues. Such as in linux, when there's a problem in PATH, the kernel doesn't panic.

**Comment by FlyingPigSolutions** [comment]
Thanks @chris001 for the details.
I'll keep with the `/home/odoo` reinstalled and I will delete I think the previous initial install that can create issues I think. 

For instance:

> root@NAME:/home# `locate pycompat.py`
> /home/odoo/odoo-server/odoo/tools/pycompat.py
> /odoo/odoo-server/odoo/tools/pycompat.py
> 
It will be much cleaner too (less confused)

**Comment by FlyingPigSolutions** [comment]
OK I made some test before removing ;

> Enough of bad stress...

So I got 2 PATH  as mentioned 
- `/home/odoo/odoo-server/addons`
- `/odoo/odoo-server/addons`

I started by changing the name to make it "hidden" let's say.
Results : BAD 👎 

If I rename the Second (initial install) with command `mv odoo odoo_OLD_install` I get lots of errors and can't get my odoo working.

> Is it possible that the odoo pick up in both path? Mystery... I'll make further test and post it here

> drwxr-xr-x  24 root root  4096 Mar 10 17:21 ./
> drwxr-xr-x  24 root root  4096 Mar 10 17:21 ../
> drwxr-xr-x   2 root root  4096 Mar  7 07:27 bin/
> drwxr-xr-x   4 root root  4096 Mar  7 07:34 boot/
> drwxr-xr-x  17 root root  3600 Mar  7 07:20 dev/
> drwxr-xr-x 103 root root  4096 Mar 10 14:57 etc/
> drwxr-xr-x   3 root root  4096 Mar  7 07:34 home/
> lrwxrwxrwx   1 root root    33 Feb 23 06:21 initrd.img -> boot/initrd.img-4.4.0-116-generic
> lrwxrwxrwx   1 root root    33 Jan 23 06:36 initrd.img.old -> boot/initrd.img-4.4.0-112-generic
> drwxr-xr-x  22 root root  4096 Jan  7 18:33 lib/
> drwxr-xr-x   2 root root  4096 Jan 19 06:59 lib64/
> drwx------   2 root root 16384 Jan  5 18:12 lost+found/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 media/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 mnt/
> drwxr-xr-x   6 odoo odoo  4096 Mar  7 07:42 odoo/
> drwxr-xr-x   3 root root  4096 Jan  7 17:57 opt/
> dr-xr-xr-x 138 root root     0 Mar  7 07:20 proc/
> drwx------   8 root root  4096 Mar  7 07:39 root/
> drwxr-xr-x  26 root root   980 Mar 10 10:22 run/
> drwxr-xr-x   2 root root 12288 Mar  7 07:27 sbin/
> drwxr-xr-x   2 root root  4096 Nov 30 19:48 snap/
> drwxr-xr-x   2 root root  4096 Jan  5 17:58 srv/
> dr-xr-xr-x  13 root root     0 Mar  7 09:54 sys/
> drwxrwxrwt  20 root root  4096 Mar 10 17:17 tmp/
> drwxr-xr-x  10 root root  4096 Jan  5 17:58 usr/
> drwxr-xr-x  13 root root  4096 Jan  5 18:01 var/
> lrwxrwxrwx   1 root root    30 Feb 23 06:21 vmlinuz -> boot/vmlinuz-4.4.0-116-generic
> lrwxrwxrwx   1 root root    30 Jan 23 06:36 vmlinuz.old -> boot/vmlinuz-4.4.0-112-generic
> 


> Could not get content for /web/static/lib/bootstrap/less/variables.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/bootstrap/less/mixins/buttons.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/bootstrap/less/mixins/clearfix.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/bootstrap/less/mixins/size.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/variables.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/utils.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web_editor/static/src/less/web_editor.variables.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/fonts.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/navbar.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/mimetypes.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/modal.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/animation.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/rainbow.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/src/less/datepicker.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web_planner/static/src/less/web_planner_common.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web_tour/static/src/less/tip.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web_tour/static/src/less/keyframes.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /stock/static/src/less/stock_traceability_report.less defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/jquery.ui/jquery-ui.css defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/fontawesome/css/font-awesome.css defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/select2/select2.css defined in bundle 'web.assets_common'.&NewLine;Could not get content for /web/static/lib/select2-bootstrap-css/select2-bootstrap.css defined in bundle 'web.assets_common'.

**Comment by FlyingPigSolutions** [comment]
I removed the APP to generate "nice" invoice and we saw it pretty much solved our issue.
We got minor bugs but still, we can continue filling up the database.
Now when we try to print an invoice (not on other documents), we got this error:

Now I'll have to dig into that.

> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
>     return compiled(self, append, new, options, log)
>   File "<template>", line 1, in template_630_213
>   File "<template>", line 2, in body_call_content_212
>   File "<template>", line 4, in foreach_211
> AttributeError: 'account.invoice' object has no attribute 'report_template_id'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 1663, in report_download
>     response = self.report_routes(reportname, docids=docids, converter='pdf')
>   File "/home/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 1612, in report_routes
>     pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_actions_report.py", line 624, in render_qweb_pdf
>     html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_actions_report.py", line 662, in render_qweb_html
>     return self.render_template(self.report_name, data), 'html'
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_actions_report.py", line 470, in render_template
>     return view_obj.render_template(template, values)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1158, in render_template
>     return self.browse(self.get_view_id(template)).render(values, engine)
>   File "/home/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 113, in render
>     return super(View, self).render(values, engine=engine)
>   File "/home/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
>     return super(IrUiView, self).render(values=values, engine=engine)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1167, in render
>     return self.env[engine].render(self.id, qcontext)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
>     return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 271, in render
>     self.compile(template, options)(self, body.append, values or {})
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
>     raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
> odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'account.invoice' object has no attribute 'report_template_id'
> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
>     return compiled(self, append, new, options, log)
>   File "<template>", line 1, in template_630_213
>   File "<template>", line 2, in body_call_content_212
>   File "<template>", line 4, in foreach_211
> AttributeError: 'account.invoice' object has no attribute 'report_template_id'
> 
> Error to render compiling AST
> AttributeError: 'account.invoice' object has no attribute 'report_template_id'
> Template: 630
> Path: /templates/t/t/t[2]/t[1]
> Node: <t t-set="r_name" t-value="o.report_template_id and o.report_template_id.report_name or o.partner_id and o.partner_id.report_template_id and o.partner_id.report_template_id.report_name or o.company_id and o.company_id.report_template_id and o.company_id.report_template_id.report_name"/>

**Comment by FlyingPigSolutions** [comment]
Got busy but wanted to confirm that removing the last code of the app put things back to normal. So when you remove an app just make sure all the code is removed too.
You can look for it by searching its name in the views in developper mode.
