### ISSUE TITLE
[11.0] Webpage: Promote Page: Optimise SEO: Description: not editable

### ISSUE THREAD

**Issue by kimasplund** [odoo/odoo#23659]
Impacted versions: 11

Steps to reproduce: think it came with latest git refresh because database created before dont have this problem.

Current behavior: The description box says "False" and is editable but does not save.
Page Title and Keyword work as expected

Expected behavior: Should save description for search engine

Video/Screenshot link (optional):
![seo2](https://user-images.githubusercontent.com/13152668/37410692-cc536146-27a9-11e8-819c-f5b64b0c92f2.png)

**Comment by rdeodoo** [comment]
Fix merged [here](https://github.com/odoo/odoo/commit/2b5bb95d430a8cfb3f6abb982f7402c33cdcc313) in v9.0.
It might take a few day to hit 11.0

**Comment by cdumont33** [comment]
Hi, i have the same issue. 
Is the last website_template.xml version 11 up to date?
Because i copy it and it still does not work.

**Comment by rdeodoo** [comment]
Hi, yes it is, I tried on runbot 11.0 and it seems to work fine
Should you experience any issue related to that, could you please open another github issue or odoo ticket?
Thank you

**Comment by nostahl** [comment]
how is this issue closed? it is still doing this even on freshly updated odoo 11 instance.

**Comment by rdeodoo** [comment]
Are you able to reproduce on runbot?
I just tried on Odoo 11.0 in the latest runbot and did not find any issue as you can see here: https://drive.google.com/file/d/1sie1kHbMsJmwph252f1Nsedesy_Spy02/view

**Comment by nostahl** [comment]
im on a fairly fresh instance of odoo 11 thats been kept up to date. thats about all i know

**Comment by rdeodoo** [comment]
Then it should work. Could you check on one of your problematic pages if the meta description tag is present (Logged in as someone who can see the Optimize SEO popup like an admin or editor)?
Something like:

> <meta name="description" [...]

If you see this tag (even empty) it should work.
If not, your code is probably not up to date as it was the issues that has now been fixed.

**Comment by nostahl** [comment]
ok i just viewed source on the homepage and did not see anything with ctrl-f  name="description"

**Comment by rdeodoo** [comment]
It looks like you have not the latest source code.
Could you check this video: https://drive.google.com/file/d/1IMmjFsxFV63oq3u73SfsN45aYJ5LaH7f/view and do the same, then verify that the template's code contains the `editable` part in the follow line:

> t-if="meta_description **or editable**"

**Comment by nostahl** [comment]
<t t-set="meta_description" t-value="main_object and 'website_meta_description' in main_object and main_object.website_meta_description or website_meta_description"/>

**Comment by nostahl** [comment]
`<t t-set="meta_description" t-value="main_object and 'website_meta_description' in main_object and main_object.website_meta_description or website_meta_description"/>
`

**Comment by nostahl** [comment]
oh a little lower i see hah
`            <meta t-if="meta_description" name="description" t-att-content="meta_description"/>
`

**Comment by nostahl** [comment]
so with "or editable" its working and retaining what i put in after saving and going back.  

something made it so it did not get the fix when updating the nightly odoo

**Comment by rdeodoo** [comment]
Alright, this is why you still have the issue, your source code is not the latest one as you can see here: https://github.com/odoo/odoo/blob/c3ea0a781132b6bb4c00e7856b2e0aa1b5c20f28/addons/website/views/website_templates.xml#L127
You are missing the **_or editable_** part that was the fix of this issue.

If you experience another issue that can be reproduced on runbot, feel free to open another issue.
Regards,
