### ISSUE TITLE
Done Inventory Adjustment document can be deleted

### ISSUE THREAD

**Issue by smartboxid** [odoo/odoo#24276]
Impacted versions: 11.0

Steps to reproduce: From Inventory-Operations-Inventory Adjustment Create new, input one product and save, Press Start Inventory and all transaction is executed, status become Validated. From List view or Form view, the document can be deleted even in Validated Status. 

Current behavior: Inventory Adjustment document can be deleted even in Validated Status, but the transaction still valid. 

Expected behavior: Inventory Adjustment document must not be able to be deleted in Validated Status.

Video/Screenshot link (optional):

**Comment by Yenthe666** [comment]
@lap-odoo this is of interest for you.

**Comment by lap-odoo** [comment]
@smartboxid Hello, I've just tried in version 11 and could not delete a validated inventory adjustment : https://drive.google.com/a/odoo.com/file/d/1DVhCCq5RQhlMM-dyXLR7njzRscAzMHz1/view?usp=drivesdk. Do you still face this issue ?

**Comment by sle-odoo** [comment]
it was fixed by https://github.com/odoo/odoo/commit/8a906f80b4120ca96afcc58331e4ef8733be28c6#diff-fc6cef81fac5ca3c30afb09ccb60ff4c

**Comment by smartboxid** [comment]
No, the error still there.

I clone odoo 11 the latest one, run it. I create new database with demonstration data option checked, install only Inventory App and go to Inventory Adj., delete Starting Inventory and bam it will be deleted. Create new Inventory Adjustment, validated and it can be deleted as well.

That's what I've tried. Thank you.

**Comment by lap-odoo** [comment]
@smartboxid I'm sorry but I can't reproduce it on runbot, did you try on a runbot ?
