### ISSUE TITLE
[11] Pos and Sale - report all channels Sales Order wrong values

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#24746]
**Impacted versions:**
11.0, tested on runbot
**Steps to reproduce:**
1. Configure TPV with Sales Channel
![image](https://user-images.githubusercontent.com/7775116/40087431-0f511f6c-5868-11e8-890a-b5f9c5091c33.png)
2. Configure Customer Taxes on products
![image](https://user-images.githubusercontent.com/7775116/40087492-5d0d9ae6-5868-11e8-9f69-3c14f1fff116.png)
3. Create a Order from POS(pos.order), Sell product configured on step 2(Coca cola in the example)
![image](https://user-images.githubusercontent.com/7775116/40087522-8956049e-5868-11e8-9ac7-095afb7a3d25.png)
4. Create a order from Sales Order(sale.order) Sell product configured on step 2(Coca cola in the example)
![image](https://user-images.githubusercontent.com/7775116/40087566-c2a563e8-5868-11e8-851f-949edb1af33d.png)
5. Go to Menu Sales/Reporting/All Sales Channels Sales Order, search product Coca Cola and compare values.
![image](https://user-images.githubusercontent.com/7775116/40087638-0007f44e-5869-11e8-8101-85d873f559ad.png)
**Current behavior:**
Order from Sales Order has total with tax included, Order from POS  has total without tax included.
**Expected behavior:**
Both orders show same totals

Sale order Query get values from field [price_total](https://github.com/odoo/odoo/blob/11.0/addons/sale/report/report_all_channels_sales.py#L40-L43) which is with taxes included.
POS query get values from field [price unit * quantity](https://github.com/odoo/odoo/blob/11.0/addons/pos_sale/report/report_all_channels_sales.py#L22-L25) which is without taxes included
Video/Screenshot link (optional):

**Comment by celm1990** [comment]
testing on master, report is better and this issue is corrected

But I found other error:

![image](https://user-images.githubusercontent.com/7775116/45465489-fa2ff800-b704-11e8-90e1-c49847b2159a.png)


This fields must be untaxed https://github.com/odoo/odoo/commit/a4d6bff197b894f70eaecf5aa4e2088e5b014780#diff-c1fc9a661fdf2247fd411e3e9d664ae5R34

**Comment by larsn7** [comment]
Will the fix for this be merged to the branch of 11.0? The issue still persists there.

**Comment by wpichler** [comment]
There is also an other tax related problem in this report. If you do use gross price in your system (tax included in price option) - then you will get the gross price + taxes applied again in the price_total ! in price_subtotal there is the gross price.

This two lines are only correct if using tax excluded prices: https://github.com/odoo/odoo/blob/418babf7af7b52ba3aef120de9be49dea9669b74/addons/pos_sale/report/sale_report.py#L32-L33

**Comment by wpichler** [comment]
Why is the calculation here so complex ? This does not seem to be necessary - because the calculation is already done - and the values are already in the database. So this calculation is only a point of failure !

in pos.order.line you do have price_subtotal and price_subtotal_incl - so simple using this:
`sum(l.price_subtotal_incl) / MIN(CASE COALESCE(pos.currency_rate, 0) WHEN 0 THEN 1.0 ELSE pos.currency_rate END) AS price_total,
sum(l.price_subtotal) / MIN(CASE COALESCE(pos.currency_rate, 0) WHEN 0 THEN 1.0 ELSE pos.currency_rate END) AS price_subtotal,
`
does solve the problem for me

**Comment by celm1990** [comment]
> There is also an other tax related problem in this report. If you do use gross price in your system (tax included in price option) - then you will get the gross price + taxes applied again in the price_total ! in price_subtotal there is the gross price.
> 
> This two lines are only correct if using tax excluded prices:
> 
> https://github.com/odoo/odoo/blob/418babf7af7b52ba3aef120de9be49dea9669b74/addons/pos_sale/report/sale_report.py#L32-L33

This changes are made in PR #33304

**Comment by wpichler** [comment]
Thanks - i've commented on the PR

**Comment by pedrobaeza** [comment]
As the referred PR was merged, I close this.
