### ISSUE TITLE
[ir.cron] invalidate all cache and load modules for each calls for ir.cron

### ISSUE THREAD

**Issue by moylop260** [odoo/odoo#25029]
Impacted versions:
9.0, 10.0, 11.0 (Maybe 8.0)
I don't know if it is really an expected behaviour for odoo but I like to expose it

Steps to reproduce:

1. Open an ir.cron record and change it to:
 - interval: minutes
 - next execution date: now + 1 minute

2. Open the odoo server log

Note: I'm using workers=3 but I don't know if there is possible to reproduce it without workers.

Current behavior:

You will see for each cron execution the following output
```txt
...
2018-06-01 16:18:33,432 20686 INFO 333561-11-0-42aff9-all odoo.modules.registry: Invalidating all model caches after database signaling.
...
2018-06-01 16:17:21,527 20687 INFO 333561-11-0-42aff9-all odoo.modules.loading: loading 1 modules...
2018-06-01 16:17:21,535 20687 INFO 333561-11-0-42aff9-all odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries
2018-06-01 16:17:21,594 20687 INFO 333561-11-0-42aff9-all odoo.modules.loading: loading 206 modules...
2018-06-01 16:17:21,718 20687 INFO 333561-11-0-42aff9-all odoo.modules.loading: 206 modules loaded in 0.12s, 0 queries
2018-06-01 16:17:21,989 20687 INFO 333561-11-0-42aff9-all odoo.modules.loading: Modules loaded.
```

Expected behavior:
 - Review if the method that run from the cron really requires a invalidate cache and delete all registries.
 - Disable "minutes" for cron interval because all cache are deleted then is not valid use them.

Video/Screenshot link (optional):

 - [![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Be4FIeQjgjk/0.jpg)](https://youtu.be/Be4FIeQjgjk)

**Comment by moylop260** [comment]
@odony 
Is an expected behaviour clean caches and registries after run a cron method?

**Comment by NothingCtrl** [comment]
My Odoo server stop record any activity to log file, and this line show up:
`2018-06-09 10:22:47,189 22273 INFO solarbk_erp openerp.modules.registry: Invalidating all model caches after database signaling.`

Restart Odoo fix problem but it's may cameback anytime.

![Uploading odoo_9_log_invalid_2018-06-06.png…]()
![odoo_9_log_invalid_2018-06-07](https://user-images.githubusercontent.com/5380820/41199969-2633d18a-6cc6-11e8-8365-13cd662b00f5.png)

**Comment by NothingCtrl** [comment]
My Odoo server stop record any activity to log file, and this line show up:
`2018-06-09 10:22:47,189 22273 INFO database_name openerp.modules.registry: Invalidating all model caches after database signaling.`

Restart Odoo fix problem but it's may cameback anytime.

![odoo_9_log_invalid_2018-06-06](https://user-images.githubusercontent.com/5380820/41199989-9f0a11a0-6cc6-11e8-9224-811660f4f2f0.png)
![odoo_9_log_invalid_2018-06-07](https://user-images.githubusercontent.com/5380820/41199990-9f417df2-6cc6-11e8-86d0-f4bc59264c47.png)

**Comment by odony** [comment]
Good point, not sure this is necessary... investigating.

**Comment by odony** [comment]
We've found the root cause for this, and @KangOl has proposed #25234 to fix it. Give it a shot and let us know if it seems to fix the symptoms :-)

**Comment by moylop260** [comment]
The symptoms were fixed Doctor @odony and @KangOl :-)

I just tested using the runbot from the PR:
 - [![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Cdc0XMx9Noc/0.jpg)](http://youtu.be/Cdc0XMx9Noc)

**Comment by JDSalcedo** [comment]
Hi @KangOl - This error is still repoducing on v12 I tested in runbot(CE), I didn't record it but I got a image. It is related to my open issue [https://github.com/odoo/odoo/issues/31830](url).

![image](https://user-images.githubusercontent.com/8197930/54317656-bfbeef00-45b1-11e9-8290-53583c767c32.png)

**Comment by mmotahar-ia** [comment]
I do see this in Odoo.sh too

**Comment by mmotahar-ia** [comment]
> Hi @KangOl - This error is still repoducing on v12 I tested in runbot(CE), I didn't record it but I got a image. It is related to my open issue [https://github.com/odoo/odoo/issues/31830](url).
> 
> ![image](https://user-images.githubusercontent.com/8197930/54317656-bfbeef00-45b1-11e9-8290-53583c767c32.png)

I do see this in Odoo.sh too
