### ISSUE TITLE
Wrong qty_received compute when multi steps inputs

### ISSUE THREAD

**Issue by carlosdauden** [odoo/odoo#25778]
Impacted versions:
11.0

Steps to reproduce:
- Go to warehouse
- Set Incoming Shipments: Unload in input location then go to stock (2 steps)
- Create new Purchase Order with some stockable product
- Confirm Purchase Order
- Go to Shipments
- Validate all pickings

Current behavior:
Received Qty is multiplied by the number of pickings

Expected behavior:
Received Qty on take in account moves from Vendors location

@Tecnativa

**Comment by pedrobaeza** [comment]
@jco-odoo can you please check this one?

**Comment by jco-odoo** [comment]
@simongoffin @sle-odoo, Carlos is right on this one.  As the push_apply method is copying, we can not just change purchase_line_id as copy True without some modifs.  It has never been the case before that when you copy a picking, it would be automatically linked to the same PO/SO.  (Cancelling and updating quantities could be good for that)  You can of course override in the purchase module and make sure the purchase_line_id is False when ding the push_apply.

**Comment by pedrobaeza** [comment]
I think we can change this line:

https://github.com/odoo/odoo/blob/f6b3247c31ee176944a060afb911021d071d8a32/addons/purchase/models/purchase.py#L581

to:
```python
elif move.location_dest_id.usage == "supplier":
```

**Comment by pedrobaeza** [comment]
My colleague has already proposed #25779 with this change.

**Comment by jco-odoo** [comment]
That is another option, but we are changing semantics.

**Comment by pedrobaeza** [comment]
I prefer to keep the link to all the reception pickings, but if you think there's any side effect...

Keep in mind another thing: patching the `push_apply` won't fix all the current purchase orders with 2 reception steps, as they have already the `purchase_line_id` copied.

**Comment by pimodoo** [comment]
Fixed in rev: https://github.com/odoo/odoo/commit/3869cdf7d8202c8157c1134d74549b3096758253

**Comment by pedrobaeza** [comment]
But the problem still exists for the already existing orders and it's a big behavior change: you move from seeing all the steps from purchase order to see only the first one.
