### ISSUE TITLE
Issue with Generate Missing Terms

### ISSUE THREAD

**Issue by Linekio** [odoo/odoo#26553]
Impacted versions:
10.0, 11.0, ...

Steps to reproduce:
I installed a language (french) and used "Generate Missing Terms" to fix some translations on PDF reports.

Current behavior:
BUT it's caused some fields are no longer translated, for example buttons Create and Edit. And my boss hit me on the head.
Reload the language didn't fix the issue. To fix it I removed all translatd terms then reloaded the language, but I got the issue on PDF reports again.

Expected behavior:
Works
Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
What has to do PDF reports with "Create" and "Edit" buttons?

**Comment by Linekio** [comment]
After using "Generate Missing Terms", fields on PDF reports have been restored correctly.
But Create and Edit buttons, on Odoo, are no translated.
![capture du 2018-08-23 17-04-56](https://user-images.githubusercontent.com/25034353/44533856-b4c86e00-a6f6-11e8-8315-a43e2e3603aa.png)

**Comment by pedrobaeza** [comment]
Have you checked if there are translation entries about that buttons?

**Comment by pedrobaeza** [comment]
@mart-e what do you think about this?

**Comment by Linekio** [comment]
Yes:
![capture du 2018-08-23 17-14-15](https://user-images.githubusercontent.com/25034353/44534424-0ae9e100-a6f8-11e8-9625-f5a38bd3bb92.png)

**Comment by Linekio** [comment]
It seems that I can translate manually, but it concerns a lot of fields (Look "is" or "Group By" on the filters)
![capture du 2018-08-23 17-51-20](https://user-images.githubusercontent.com/25034353/44536638-33280e80-a6fd-11e8-8d63-3d776eaccbd4.png)

**Comment by pedrobaeza** [comment]
Indeed is strange that your terms are overwritten. @mart-e I think you made some changes on the generate missing terms option recently, isn't it?

**Comment by mart-e** [comment]
Hi,

I agree with the report. I could reproduce the issue with the "Group By". I guess the create depends of the module that are installed.

I think it is related to b505ba9e0a6be1182b73e8930ed5b3d0c2f72925 (not recent then).
This one prevents duplicated code translation while "Generate Missing Terms" creates duplicates.
The generate should also avoid creating duplicated terms.

Could you try with fe8554d34ca if it solves your issue?

**Comment by Linekio** [comment]
No
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/wizard/base_update_translations.py", line 35, in act_update
    tools.trans_load_data(self._cr, buf, 'po', this.lang, lang_name=lang_name)
  File "/usr/lib/python3/dist-packages/odoo/tools/translate.py", line 1049, in trans_load_data
    if isinstance(fileobj.name, str) and fileobj.name.endswith('.po'):
AttributeError: '_io.BytesIO' object has no attribute 'name'
```

**Comment by mart-e** [comment]
Ok the one at #26614 should be working now

**Comment by Linekio** [comment]
Yes, seems OK. Thanks.

**Comment by Linekio** [comment]
There are still some untranslated fields, for example:
![capture du 2018-08-29 09-47-46](https://user-images.githubusercontent.com/25034353/44773413-d69b7800-ab70-11e8-9a29-0c8f4c38e366.png)
I caught the temporary po file created during the process "generate missing terms".
Here a part of the file:
```
#. module: web
#. openerp-web
#: code:addons/web/static/src/js/chrome/search_filters.js:167
#: code:addons/web/static/src/js/chrome/search_filters.js:186
#: code:addons/web/static/src/js/chrome/search_filters.js:274
#: code:addons/web/static/src/js/chrome/search_filters.js:303
#: code:addons/web/static/src/js/chrome/search_filters.js:328
#: code:addons/web/static/src/js/widgets/domain_selector.js:36
#, python-format
msgid "is set"
msgstr "est défini"
```

A test shows that some lines seem to be ignored:
```
>>> from odoo.tools.translate import PoFile
>>> fileobj = open('tmp.po', 'rb')
>>> reader = PoFile(fileobj)
>>> for row in reader:
...     if row[3] == 'is set':
...         print(row)
... 
('code', 'addons/web/static/src/js/chrome/search_filters.js', '167', 'is set', 'est défini', 'openerp-web')
>>> 

```

**Comment by mart-e** [comment]
Are you sure the translation you are showing in your screenshot is not an old translation from before the fix?
By the way, I have pushed another fix at 1566c0ab3b6465e60fb796393ed1650525110477 and added some tests.

**Comment by Linekio** [comment]
Yes, it's a translation that was broken before the fix.
After the fix, "Generate missing terms" no longer breaks translations, but doesn't fix the previously broken translations.
So I think it's OK.
