### ISSUE TITLE
Cannot Setup Bank Account

### ISSUE THREAD

**Issue by haconsult** [odoo/odoo#27423]
Impacted versions:
12

Steps to reproduce:
- Install Sales and Purchase App
- Go to "Invoicing"
- Try to "Add a bank" from the Setup Bar

Current behavior:
- Fails with the following error:

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/addons/account_bank_statement_import/wizard/setup_wizards.py", line 14, in validate
    self.linked_journal_id.bank_statements_source = 'file_import'
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/fields.py", line 992, in __set__
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3.6/site-packages/odoo-12.0.post20181004-py3.6.egg/odoo/fields.py", line 1944, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for account.journal.bank_statements_source: 'file_import'

Expected behavior:

Video/Screenshot link (optional):

**Comment by alexis-via** [comment]
I've been hit by the same bug.

Code analysis:
When you run this setup wizard, it will write "file_import" on the field 'bank_statements_source' cf https://github.com/odoo/odoo/blob/12.0/addons/account_bank_statement_import/wizard/setup_wizards.py#L14

The field 'bank_statements_source' is a selection field defined in the 'account' module with only 1 possible value "undefined". In the module "account_bank_statement_import", the possible values of the field "bank_statements_source" is updated with "file_import", but ONLY if additionnal account_bank_statement_import_xxx" modules are installed, cf https://github.com/odoo/odoo/blob/12.0/addons/account_bank_statement_import/account_journal.py#L17 So, if you only have the module "account_bank_statement_import" and no additionnal bank statement import modules, you get the crash.

@qdp-odoo An easy bug for you :)

**Comment by Yenthe666** [comment]
Hi guys,

It seems solved in the meanwhile! Can you guys double check and confirm please?

Regards,
Yenthe

**Comment by haconsult** [comment]
Hi,
The issue still persists in post 20181006.

Regards, Helge

**Comment by sswapnesh** [comment]
Hello @qdp-odoo 
I am able to Reproduce this on latest [Runbot Build](http://385490-12-0-6d3477.runbot16.odoo.com/web?debug#action=521&model=account.journal&view_type=kanban&menu_id=324) 

![screenshot 13](https://user-images.githubusercontent.com/16624719/47044579-3811b780-d1ae-11e8-9461-d50ad9ad30e7.png)
![screenshot 12](https://user-images.githubusercontent.com/16624719/47044582-3942e480-d1ae-11e8-9a85-aa71c536a01b.png)

**Comment by qdp-odoo** [comment]
sorry, I'm an idiot... wrong parenthesis just fixed and soon to be deployed by the mergebot

**Comment by sswapnesh** [comment]
Agree with @haconsult , That step is never done.
Cc: @qdp-odoo

**Comment by dtn-world** [comment]
Hello.
I am using Odoo 12 CE using the script of @Yenthe666 and having the same issue with two modules installed:
- account_bank_statement_import
-account_bank_statement_import_paypal

"bank_statements_source" is still not set to "file_import" and remains undefined. Tried the answer of @alexis-via but got no solution. 
How can I execute the wizards or solve my problem? Any ideas? Maybe I am doing this wrong. Is there any documentation?

Regards, Stefan
