### ISSUE TITLE
ERROR odoo odoo.modules.loading: Database odoo not initialized, you can force it with `-i base`

### ISSUE THREAD

**Issue by debianmaster** [odoo/odoo#27447]
Impacted versions:
12.0 

Steps to reproduce:
```sh
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo  --name db postgres:9.4
docker run -p 8069:8069 -d --link db:db --name=odoo  odoo:12.0
docker logs -f odoo
```
Current behavior:
```sh
2018-10-05 09:56:10,162 1 ERROR odoo odoo.modules.loading: Database odoo not initialized, you can force it with `-i base`
2018-10-05 09:56:10,165 1 INFO odoo werkzeug: 172.17.0.1 - - [05/Oct/2018 09:56:10] "GET / HTTP/1.1" 500 - 10 0.010 0.020
2018-10-05 09:56:10,171 1 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1470, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 176, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2018-10-05 09:56:46,672 1 ERROR odoo odoo.sql_db: bad query: b"SELECT latest_version FROM ir_module_module WHERE name='base'"
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
```
Expected behavior:
odoo should boot up

Video/Screenshot link (optional):

**Comment by damcar** [comment]
I have the same problem. Any idea ?

**Comment by onorua** [comment]
same here

**Comment by niulinlnc** [comment]
me too

**Comment by Yenthe666** [comment]
@d-fence could you have a look please?

**Comment by flachica** [comment]
Yes, me too. I have recently the git clone the master branch and I have same issue

**Comment by damcar** [comment]
With postgres 9.4 and postgres 10.5, I have the same issue. When I change with postgres 10.0, It works fine. Strange!

**Comment by Cayprol** [comment]
same issue, postgres:10.0 working with latest Odoo12.  Other than this version(including latest), all produce the problem.  Seems like something went wrong on postgresql, not odoo itself.

**Comment by nknganda** [comment]
Same issue.

**Comment by debianmaster** [comment]
if any anyone is looking for a temporary fix.    i was able to make 12.0 run by using this modifiled Dockerfile  on repo   https://github.com/odoo/docker


```sh
FROM debian:stretch
MAINTAINER Odoo S.A. <info@odoo.com>

# Generate locale C.UTF-8 for postgres and general locale data
ENV LANG C.UTF-8

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            node-less \
            python3-pip \
            python3-setuptools \
            python3-renderpm \
            libssl1.0-dev \
            xz-utils \
            python3-watchdog \
        && curl -o wkhtmltox.tar.xz -SL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz \
        && echo '3f923f425d345940089e44c1466f6408b9619562 wkhtmltox.tar.xz' | sha1sum -c - \
        && tar xvf wkhtmltox.tar.xz \
        && cp wkhtmltox/lib/* /usr/local/lib/ \
        && cp wkhtmltox/bin/* /usr/local/bin/ \
        && cp -r wkhtmltox/share/man/man1 /usr/local/share/man/

# Install Odoo
ENV ODOO_VERSION 12.0
ENV ODOO_RELEASE 20181006
RUN set -x; \
        curl -o odoo.deb -SL http://nightly.odoo.com/${ODOO_VERSION}/nightly/deb/odoo_${ODOO_VERSION}.${ODOO_RELEASE}_all.deb \
        && dpkg --force-depends -i odoo.deb \
        && apt-get update \
        && apt-get -y install -f --no-install-recommends \
        && rm -rf /var/lib/apt/lists/* odoo.deb

# Copy entrypoint script and Odoo configuration file
RUN pip3 install num2words xlwt
COPY ./entrypoint.sh /
COPY ./odoo.conf /etc/odoo/
RUN chown odoo /etc/odoo/odoo.conf

# Mount /var/lib/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN mkdir -p /mnt/extra-addons \
        && chown -R odoo /mnt/extra-addons
VOLUME ["/var/lib/odoo", "/mnt/extra-addons"]

# Expose Odoo services
EXPOSE 8069 8071

# Set the default config file
ENV ODOO_RC /etc/odoo/odoo.conf

# Set default user when running the container
USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
````

**Comment by d-fence** [comment]
The issue can be solved by adding this argument to the command line when starting the database container :

> -e POSTGRES_DB=postgres

I'm going to update the documentation accordingly. This problem was highlighted by [this change](https://github.com/docker-library/postgres/commit/3f585c58df93e93b730c09a13e8904b96fa20c58) in the postgres docker image.

Since the postgres 10.5 docker image, a db is created with the same name as the "POSTGRES_USER" and the POSTGRES_USER is the superuser.

So, the right way to start the postgres docker image is with the POSTGRES_DB as stated, even for the old version of odoo.

By the way, the "postgres 10" docker image is the 10.5 version.
Odoo will not work with postgres <= 9.4 because Odoo uses the "ON CONFLICT"  clause that was added in postgres 9.5.

**Comment by drewes** [comment]
@d-fence Any advice when connecting to an external Postgres service, i.e. not a container? 

I have the error trying to connect an AWS ECS container to RDS.

**Comment by BorjaRafols** [comment]
The docker-compose version ain't working too. I tried adding the environment variable @d-fence suggested:

 environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=propertista-crm

But no success, error is the same: Database X not initialized, you can force it with `-i base`

**Comment by abngal** [comment]
@BorjaRafols same thing happens to me.

error is triggered by volume:
`
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata # removing this volume removes the error
`

My full docker-compose.yml file
`
version: '2'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata # removing this volume removes the error
volumes:
  odoo-web-data:
  odoo-db-data:
`

**Comment by PaulDach** [comment]
> Error about db not initialized may still show up when using volume:
> 
> > volumes:
> > - odoo-db-data:/var/lib/postgresql/data/pgdata # removing this volume removes the error
> 
> Somehow got it to work by:
> 
> docker-compose exec web bash
> odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo
> ...
> re-up using docker-compose

This solved the issue for me, thanks a lot!

**Comment by mohamedelbahr** [comment]
@d-fence :  Thanks, You saved alot of work

**Comment by SalahAdDin** [comment]
I'm getting the same issue in a `Odoo 11.0` custom image, but i still can work with my database.

**Comment by byk0t** [comment]
> > Error about db not initialized may still show up when using volume:
> > > volumes:
> > > 
> > > * odoo-db-data:/var/lib/postgresql/data/pgdata # removing this volume removes the error
> > 
> > 
> > Somehow got it to work by:
> > docker-compose exec web bash
> > odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo
> > ...
> > re-up using docker-compose
> 
> I experienced no trouble when using volume, but it has to match the default directory for the postgresql version you're using (with pg 10.5, it should be odoo-db-data:/var/lib/postgresql/data).
> 
> However docker image of odoo v12 does not initilise the database ...
> 
> Many thanks to @abngal for the lead !

This fix works for me too.
BTW I found out that if we explicitly setup POSTGRES_DB=postgres in a docker-compose it starts working without this hack. For details see a gist with a working docker-compose.yml https://gist.github.com/byk0t/a9644fd2360a9662702568459df289fc

**Comment by quanwei132** [comment]
With postgres 11 , I have the same issue. When I change with odoo.conf "dbfilter=odoo12" It works well. Strange!

**Comment by unionx** [comment]
> With postgres 11 , I have the same issue. When I change with odoo.conf "dbfilter=odoo12" It works well. Strange!

But after initiation, I must remove odoo12 then I can log into the system.

**Comment by phatminh** [comment]
Be the same error!! How can fix it?

**Comment by SalahAdDin** [comment]
I have the same error too.

**Comment by litnimax** [comment]
Yes, confirming that adding POSTGRES_DB=postgres to docker-compose.yml from docker hub solved the init db issue.
I guess it should be added to the docker hub docker-compose.yml example as many new users fall at the first step that is very bad.

**Comment by drewes** [comment]
@dzenteno2 I managed to work around the issue by enabling the DB manager in Odoo (I had initially disabled it for security reasons), creating the database associated with the db_filter, and then disabled the DB manager.

**Comment by wbison3** [comment]
**In short**: creating the addons folder fixed this problem for me.
**Longer answer**. I have a custom docker file pointing to a local folder. It was working fine for me for a client and wanted to start working with another client that needs no custom addons so I negleted to create that folder. Once I created my special addons folder specified in odoo.conf the init routine works normally.
This is the error I got
```
ERROR: relation "ir_module_module" does not exist
LINE 1: UPDATE ir_module_module SET state='installed' WHERE state IN...
```
however little further there is actually what happened
`FileNotFoundError: [Errno 2] No such file or directory: '/home/dev/Pixkah/addons'`

**Comment by vpalvesalan** [comment]
> @d-fence Any advice when connecting to an external Postgres service, i.e. not a container?
> 
> I have the error trying to connect an AWS ECS container to RDS.

Did you manage to solve this problem? same problem here

**Comment by vpalvesalan** [comment]
> @dzenteno2 I managed to work around the issue by enabling the DB manager in Odoo (I had initially disabled it for security reasons), creating the database associated with the db_filter, and then disabled the DB manager.

Hi @drewes , I am very new to all this. I am trying to set up RDS to work with odoo12. Would you mind to give me a step by step on how you solved the problem?

**Comment by drewes** [comment]
> > @dzenteno2 I managed to work around the issue by enabling the DB manager in Odoo (I had initially disabled it for security reasons), creating the database associated with the db_filter, and then disabled the DB manager.
> 
> Hi @drewes , I am very new to all this. I am trying to set up RDS to work with odoo12. Would you mind to give me a step by step on how you solved the problem?

How far have you managed to get?

**Comment by vpalvesalan** [comment]
Only on setting up RDS, and pointing configuration file (odoo12.conf) to RDS. But then, odoo won't open, an show an Internal Server Error Message. On the log in the amazon RDS postgreSQL log event the message is :

`STATEMENT: SELECT latest_version FROM ir_module_module WHERE name='base'
:ERROR: relation "ir_module_module" does not exist at character 28`

This is how far I got

**Comment by vpalvesalan** [comment]
> > > @dzenteno2 I managed to work around the issue by enabling the DB manager in Odoo (I had initially disabled it for security reasons), creating the database associated with the db_filter, and then disabled the DB manager.
> > 
> > 
> > Hi @drewes , I am very new to all this. I am trying to set up RDS to work with odoo12. Would you mind to give me a step by step on how you solved the problem?
> 
> How far have you managed to get?

Only on setting up RDS, and pointing configuration file (odoo12.conf) to RDS. But then, odoo won't open, an show an Internal Server Error Message. On the log in the amazon RDS postgreSQL log event the message is :

`STATEMENT: SELECT latest_version FROM ir_module_module WHERE name='base' :ERROR: relation "ir_module_module" does not exist at character 28`

This is how far I got

**Comment by 120dev** [comment]
If it helps someone, here is the configuration I'm using with Rancher1

*docker-compose.yml*
```
version: '2'
services:
  odoo:
    image: odoo:12.0
    environment:
      USER: odoo
      PASSWORD: odoo
      HOST: <HOST>
      PORT: '5432'
      POSTGRES_DB: postgres
    stdin_open: true
    volumes:
    - /etc/oddo:/etc/odoo
    tty: true
    labels:
      io.rancher.container.pull_image: always
  odoo-lb:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
    - 8072:8072/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
```

*rancher-compose.yml*
```
version: '2'
services:
  odoo:
    scale: 1
    start_on_create: true
  odoo-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: odoo
        source_port: 8072
        target_port: 8069
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
```

Once initialized:  (thx @abngal )

`odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo`

**Comment by sheltonfreddy** [comment]
Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker

**Comment by debianmaster** [comment]
A simple fix with openshift is to add `-e DB_ENV_POSTGRES_USER=odoo`  on odoo:12 docker container. 

See how it works for openshift 3.x +

```
oc new-project erp
oc adm policy add-scc-to-user anyuid -z default
oc adm policy add-scc-to-user privileged -z default

oc new-app \
    -e POSTGRES_USER=odoo     \
    -e POSTGRES_PASSWORD=odoo  \
    -e POSTGRES_DB=postgres   \
    --name=db postgres:9.6 --name=db
oc new-app -e DB_ENV_POSTGRES_USER=odoo odoo:12 --name=web

oc expose svc web
oc get routes -l app=web```

**Comment by IlirBajrami** [comment]
> Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker

Did you find out how to fix this without Docker? thanks!

**Comment by IlirBajrami** [comment]
The same issue here on Odoo12, python3, MacOs Mojave. any help would be appreciated!

**Comment by StarV5s** [comment]
> > Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker
> 
> Did you find out how to fix this without Docker? thanks!

I'm runing it with ubuntu, and the same issue occur to me, if u get any idea, plz let me konw.

**Comment by IlirBajrami** [comment]
> > > Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker
> > 
> > 
> > Did you find out how to fix this without Docker? thanks!
> 
> I'm runing it with ubuntu, and the same issue occur to me, if u get any idea, plz let me konw.

I fixed it using PostgreSQL and pgAdmin. whatch this: https://www.youtube.com/watch?v=TUaN4rEpJDE

**Comment by StarV5s** [comment]
> > > > Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker
> > > 
> > > 
> > > Did you find out how to fix this without Docker? thanks!
> > 
> > 
> > I'm runing it with ubuntu, and the same issue occur to me, if u get any idea, plz let me konw.
> 
> I fixed it using PostgreSQL and pgAdmin. whatch this: https://www.youtube.com/watch?v=TUaN4rEpJDE

I did what the video said, but the bug still unsolved. Can u give me any idea how u fix the problem with pgadmin? thx a lot.

**Comment by dolfinus** [comment]
Add to docker-compose:
```yml
command: --database <your_db_name>
```
for example: `--database odoo`

Then odoo can properly init database already created by postgres, and everything will be ok.

**Comment by IlirBajrami** [comment]
> > > > > Having the same issue in Amazon EC2 with Odoo12 and ubuntu18.04 without docker
> > > > 
> > > > 
> > > > Did you find out how to fix this without Docker? thanks!
> > > 
> > > 
> > > I'm runing it with ubuntu, and the same issue occur to me, if u get any idea, plz let me konw.
> > 
> > 
> > I fixed it using PostgreSQL and pgAdmin. whatch this: https://www.youtube.com/watch?v=TUaN4rEpJDE
> 
> I did what the video said, but the bug still unsolved. Can u give me any idea how u fix the problem with pgadmin? thx a lot.

you have to install both PostgreSQL and pgAdmin. Postgres manages your server and pgAdmin the databases.
see the video how to create a database with pgAdmin. 
run Postgres then pgAdmin, then in terminal run ./odoo-bin and it should work. at least it worked for me.

**Comment by vpalvesalan** [comment]
A way around was to install odoo and database on my local machine, than
back up the database and upload it to amazon EC2. It worked for me, however
the connection was to slow.

Em seg, 29 de abr de 2019 às 11:54, Ilir Bajrami <notifications@github.com>
escreveu:

**Comment by eLvErDe** [comment]
Hello,

There's is clearly something broken in the startup script of the container, it does not bootstrap itself correctly.

I used this simple script to force database init based on replies above:

```bash
#!/bin/sh

docker exec \
  --interactive \
  --tty \
  odoo \
  /bin/bash -c "odoo -i base -d odoo --stop-after-init --db_host=127.0.0.1 -r odoo -w mypassword"
```

Imho messing up with environment variable does not make any sense, the only thing happening here is that odoo docker startup script does not try to apply database models update before starting the app, it's NOT related to some docker environment.

**Comment by kathpalrk** [comment]
> > > > @dzenteno2 I managed to work around the issue by enabling the DB manager in Odoo (I had initially disabled it for security reasons), creating the database associated with the db_filter, and then disabled the DB manager.
> > > 
> > > 
> > > Hi @drewes , I am very new to all this. I am trying to set up RDS to work with odoo12. Would you mind to give me a step by step on how you solved the problem?
> > 
> > 
> > How far have you managed to get?
> 
> Only on setting up RDS, and pointing configuration file (odoo12.conf) to RDS. But then, odoo won't open, and show an Internal Server Error Message. In the amazon RDS postgreSQL log event the message is :
> 
> `STATEMENT: SELECT latest_version FROM ir_module_module WHERE name='base' :ERROR: relation "ir_module_module" does not exist at character 28`
> 
> This is how far I got

HI, Are you able to access it from RDS, I am also facing an issue while conncting from RDS it says. 2019-10-25 09:56:21,093 733 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database odoo. 
2019-10-25 09:56:22,916 733 ERROR odoo odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2019-10-25 09:56:23,074 733 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database odoo.

**Comment by ppenguin** [comment]
> Hello,
> 
> There's is clearly something broken in the startup script of the container, it does not bootstrap itself correctly.
> 
> I used this simple script to force database init based on replies above:
> 
> ```shell
> #!/bin/sh
> 
> docker exec \
>   --interactive \
>   --tty \
>   odoo \
>   odoo \
>     -i base \
>     --stop-after-init \
>     --db_host=127.0.0.1 \
>     --db_user odoo \
>     --db_password dbpassword \
>     --database odoo \
>     --without-demo=all
> ```
> 
> Imho messing up with environment variable does not make any sense, the only thing happening here is that odoo docker startup script does not try to apply database models update before starting the app, it's NOT related to some docker environment.

I agree, this is the only recipe that actually works and makes sense.
The other workarounds only apply to postgres docker instances that are created in combination with the odoo instance, but as soon as you use an external postgres instance, all of them fail.
(Just be sure to update to the correct database host ip etc. Apparently '--without-demo=all' was quite necessary, I tried similar command lines without that option without success.

Thanks for the winning tip!

**Comment by The-macharia** [comment]
worked after forcing it with the -i init.
Also remember to start your postgresql database with the command  service postgresql start

**Comment by PrakashLakhara** [comment]
> -i base -d odoo

for me this worked :
./odoo-bin -i base -d odoodbname

Thanks

**Comment by abdounasser202** [comment]
> Error about db not initialized may still show up when using volume:
> 
> > volumes:
> > - odoo-db-data:/var/lib/postgresql/data/pgdata # removing this volume removes the error
> 
> Somehow got it to work by:
> 
> docker-compose exec web bash
> odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo
> ...
> re-up using docker-compose

This solution works well!!!!

**Comment by inialdan** [comment]
> With postgres 11 , I have the same issue. When I change with odoo.conf "dbfilter=odoo12" It works well. Strange!

Well i try in Odoo12 and it's work... strange!!

**Comment by qdforbetter** [comment]
> > With postgres 11 , I have the same issue. When I change with odoo.conf "dbfilter=odoo12" It works well. Strange!
> 
> But after initiation, I must remove odoo12 then I can log into the system.

exactly same error. I run local with Odoo12 on Mac by VSCode. add the dbfilter=odoo12 in my Odoo.conf. it works and later remove it to allow me login.. STRANG!

**Comment by juanboterotech** [comment]
> Add to docker-compose:
> 
> ```yaml
> entrypoint: odoo
> command: --db_host=${ODOO_DB_HOST} --database ${ODOO_DB_NAME} --db_user ${ODOO_DB_USER} --db_password ${ODOO_DB_PASSWORD} -i base
> ```
My Odoo Instane not working with Docker and this worked for me.
Stopped the Odoo service and then ran this command from odoo user.

**Comment by selim-b** [comment]
I am using Kubernetes Helm Chart to deploy Odoo & PostgreSql and I had the same problem each time restoring a database.

I just discovered that if I do create a database on Odoo before the restoration it succeeds, this seems to be related to the "-i base" solution.

Why do not add an initialization script to the odoo container (odoo -i base) ?

**Comment by relghazi** [comment]
Verify your right access to the filestore directory

**Comment by bernardo-martinez** [comment]
same here without docker, but with bitnami's GCP image. PostgreSQL (12.3) and Odoo (13.0.20200815)

**Comment by Minhtech-Odoo** [comment]
my solution is uninstall all version postgresql that doesn't relate to odoo_config file, on one machine.  By doing that, you can save a lot of time for 'suprising problem' is coming

**Comment by selim-b** [comment]
We have the same error because of the high latency between the database server and the odoo server as our customer has provisioned a cloud database service not in the same region as the Odoo server.

Hope that helps.

**Comment by mamiu** [comment]
@d-fence After days of debugging this Github issue seems like an odoo bug to me.

## Intention

In our kubernetes cluster odoo instances are setup automatically and a backup from a backup store is restored after creation. I'm trying to find a straightforward way to restore a database (let's call it `the-db-name` from now on) in these odoo instances with the following (simplified) config:

```ini
[options]
csv_internal_sep = ,
dbfilter = ^the-db-name$
proxy_mode = True
without_demo = all
workers = 0
```

(Even if all other config values remain the defaults the following behavior still applies.)

## Solution

Here a few observations I've made so far:
 1. if I want to restore a database in the odoo instance with the config above I'm getting the error described in this Github issue (`ERROR the-db-name odoo.modules.loading: Database the-db-name not initialized, you can force it with "-i base"`)
 2. as soon as I add `server_wide_modules = base` I'm getting a **404** on all pages (as long as I have no database with the `base` module installed in the system)
 3. if I add a database with the config option `db_name = the-db-name` this database will be created on startup and initialized with the `base` module (then no **404** status code anymore)
 4. now I'm able to access `/web/database/manager` to restore my database backup
 5. but now I have to delete the existing `the-db-name` database in order to restore the backup and of course after deleting the current one, I'm getting a **404** again
 6. then I use [the workaround](https://github.com/odoo/odoo/issues/27447#issuecomment-430709377) (suggested by @abngal) and initialize a temporary database with

```bash
odoo \
    --init=base \
    --database=odoo \
    --stop-after-init \
    --db_host=my-postgres-host \
    --db_user=my-user \
    --db_password=my-password
```
 
 7. now I'm able to delete the initial database (`the-db-name`) and restore my backup with the same database name without encountering any issues
 8. since I use a dbfilter (`dbfilter = ^the-db-name$`) I only see the `the-db-name` database and not the temporary `odoo` database
 9. that means I have to delete this temp db and its filestore with other separate commands

```bash
PGPASSWORD=my-password dropdb -h my-postgres-host -p 5432 -U my-user -w odoo
rm -rf "$HOME/filestore/odoo"
```

This is the only way I could find to restore a db on an "emtpy" odoo instance without getting errors. All the steps above are automated in a bash script with `curl` and took some time to figure out. Maybe this could be improved for other users in the future?!

## Questions

 1. Is this really intended to be like that?
 2. Is there a reason not to initialize ALL databases on creation or restore automatically with `base`?
 3. In case there is a reason for the question above, is there then a reason not to offer an option to specify the modules that should be initialized on restore (like the `--init` argument on the odoo cli)?

---

Or @Yenthe666, maybe you know whom I should talk to? I'm asking you, because you always knew it in my previous questions. 😉

**Comment by herohat** [comment]
I tried many of the above solutions but without success.  

My solution was update the odoo.conf file and set the data_dir value:

`data_dir = /var/lib/odoo
`

My environment: 

Docker 3.0.4
ODOO Image: 13
Postgres Image: 10

**Comment by sahilraj007** [comment]
> > -i base -d odoo
> 
> for me this worked :
> ./odoo-bin -i base -d odoodbname
> 
> Thanks

you are saviour thanks

**Comment by ticapix** [comment]
I managed to have it working with
```yaml
# Use postgres/example user/password credentials
version: "3.9"
services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo:
    image: odoo:14
    restart: always
    depends_on:
      - database
    ports:
      - 8069:8069
    links:
      - "database:db"
    volumes:
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo-web-data: {}
  odoo-db-data: {}
```

then
```shell
docker-compose run odoo bash
$ odoo --init base --database odoo --stop-after-init --db_host=database --db_user odoo --db_password strongpass
```
folowwed by 
```shell
docker-compose up -d
```

**Comment by arunsanna** [comment]
If you are using AWS RDS, Dont create any database with  matching regex `odoo`. I tested it will open-source code with base RHEL image.

**Comment by syaiful505** [comment]
> With postgres 11 , I have the same issue. When I change with odoo.conf "dbfilter=odoo12" It works well. Strange!

its work foe me thanks a lot

**Comment by syaiful505** [comment]
don't forget, if you've finished making and haven't moved
remove dbfilter=odoo-x
be dbfilter=

then reload the server

**Comment by o2bdev** [comment]
./odoo-bin -i base -d dbname

**Comment by smallw00d2211** [comment]
For those stuck in running with `docker`:

According to the source code in https://github.com/odoo/docker/blob/master/16.0/entrypoint.sh , I got it working by removing `HOST` environment variable and used `DB_PORT_5432_TCP_ADDR` instead.

Here is working ENVs
```
  DB_ENV_POSTGRES_USER: odoo
  PASSWORD: odoo
  DB: odoo
  DB_PORT_5432_TCP_ADDR: postgres
```

**Comment by OUSSAMA-EZZIOURI** [comment]
For me in Odoo 15 version, I've add the parameter in the end of the running configuration string as show in the screenshot.

Hope it helps some one :)

![image](https://github.com/odoo/odoo/assets/8103446/352117bc-bc0b-46ac-9782-81f8b9af4996)

**Comment by ggorajmp** [comment]
Solution:
linux: ./odoo-bin -d newdb

https://www.oreilly.com/library/view/odoo-12-development/9781789532470/cf024fed-889c-4890-a92e-dea930dfd6c2.xhtml

**Comment by ga344833** [comment]
i do this commit 

odoo -i base -d odoo --stop-after-init --db_host=postgres -r hero -w hero

but i have this error

psycopg2.OperationalError: connection to server at "postgres" (192.168.160.3), port 5432 failed: FATAL:  password authentication failed for user

**Comment by Bijitakc** [comment]
> [ga344833](/ga344833)

Your password seems to be wrong.

**Comment by Sarah-JJ** [comment]
> Solution: linux: ./odoo-bin -d newdb
> 
> https://www.oreilly.com/library/view/odoo-12-development/9781789532470/cf024fed-889c-4890-a92e-dea930dfd6c2.xhtml

Thank you!!! this solves my issue
The problem was that I followed the documentation and created a database before running odoo, and it seems that odoo can't access it or initalize it or something, so when I used a new database name that doesn't exist, it worked!

**Comment by afsuyadi** [comment]
Hi, just wanna say thank you. I solved this by also using -i base
