### ISSUE TITLE
Odoo 12.0-20181015 (Community Edition) Nightly Employees KeyError: 'name'

### ISSUE THREAD

**Issue by dhamedic** [odoo/odoo#27826]
Impacted versions:
12
Steps to reproduce:
Employees -> Create
Current behavior:

Odoo Server Error

Traceback (most recent call last):
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/localhost/Desktop/dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/home/localhost/Desktop/dev/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/base/models/res_partner.py", line 628, in name_get
    name = partner._get_name()
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/base/models/res_partner.py", line 611, in _get_name
    name = name + "\n" + partner._display_address(without_company=True)
  File "/home/localhost/Desktop/dev/odoo/odoo/addons/base/models/res_partner.py", line 843, in _display_address
    return address_format % args
KeyError: 'name'

Expected behavior:

Video/Screenshot link (optional):

**Comment by dhamedic** [comment]
![image](https://user-images.githubusercontent.com/40818338/46997049-d9662280-d148-11e8-9ecc-3999831f0f73.png)

**Comment by pedrobaeza** [comment]
Please try latest version, as it has been already solved in Vietnam country format.

Closing as solved.

**Comment by pedrobaeza** [comment]
Can you please try on runbot and indicate all the detailed steps to reproduce the problem?

**Comment by dhamedic** [comment]
@pedrobaeza 
![image](https://user-images.githubusercontent.com/40818338/47015356-ef8ad780-d176-11e8-942c-3e521308d320.png)

Employees -> Create
I still get this error.
So i have tested "Country : USA", i haven't gotten this error.
If i select "Country: Vietnam", i will get this error.
Please recheck it @pedrobaeza

**Comment by pedrobaeza** [comment]
@mart-e can you please link here the commit about Vietnam country format fix?

**Comment by dhamedic** [comment]
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/data/res_country_data.xml#L1737
I haven't found "%(name)s" in res.country and res.partner
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/res_country.py#L48
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/res_partner.py#L33

**Comment by dhamedic** [comment]
I have found duplicate address format - Colombia
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/data/res_country_data.xml#L352-L355
@pedrobaeza

**Comment by mart-e** [comment]
Thanks for the duplicate report, it was fixed in #27858

@KangOl is it possible cf30f35f3ec455f0b8ae689865d2b3bc4f787110 was missed in the forward port?

**Comment by KangOl** [comment]
Actually, not landed in master yet.

**Comment by pedrobaeza** [comment]
@dhamedic if you want to speed up things, you can:

- Propose directly a PR
- Hire enterprise contract and put an enterprise ticket
- Fix it on your branch meanwhile
- Make a takeover bid over Odoo and change how Odoo teams work

Last one is a joke, hehe, but you have to be more patient.
