### ISSUE TITLE
[saas-12.1] No Buttons Action and Print on sider bar

### ISSUE THREAD

**Issue by celm1990** [odoo/odoo#29546]
**Impacted versions:**
saas 12.1
**Steps to reproduce:**
Go to any menu(for example, purchase or Employee or any menu with  reports or binding actions) and select some records on tree view, no button to print
**Current behavior:**
*No buttons for Print
*No Actions on side Bar
![image](https://user-images.githubusercontent.com/7775116/50024037-044de500-ffd9-11e8-83fd-a431750803c0.png)

![image](https://user-images.githubusercontent.com/7775116/50024345-f5b3fd80-ffd9-11e8-9d91-986b25c30ab3.png)

![image](https://user-images.githubusercontent.com/7775116/50024500-90acd780-ffda-11e8-9495-be21c9f897fb.png)

**Expected behavior:**
Buttons for print and buttons on actions
![image](https://user-images.githubusercontent.com/7775116/50024066-1d569600-ffd9-11e8-9040-bf6723cdd486.png)

![image](https://user-images.githubusercontent.com/7775116/50024358-006e9280-ffda-11e8-9b2d-8c0a18c75aa6.png)

![image](https://user-images.githubusercontent.com/7775116/50024524-a1f5e400-ffda-11e8-951a-9c9e5dae6ae3.png)

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
@celm1990 is saas-12.1 already released? I remember that there are still pending PRs about the sidebar.

**Comment by celm1990** [comment]
@pedrobaeza  brach here https://github.com/odoo/odoo/tree/saas-12.1
released on commit https://github.com/odoo/odoo/commit/36870481f9b79a725b6a619ac4d1769266673949

**Comment by pedrobaeza** [comment]
I see...

@ThanhDodeurOdoo you were the one assigned to task related to this, isn't it? Can you please tell us?

**Comment by celm1990** [comment]
This PR can be posible solution #29389
@ged-odoo can confirm if your PR fixed this please?

**Comment by celm1990** [comment]
tested on master(without PR on mention because no forwardport yet) no buttons
![image](https://user-images.githubusercontent.com/7775116/50028909-159eed80-ffe9-11e8-9642-9eb403470dad.png)

![image](https://user-images.githubusercontent.com/7775116/50028945-3404e900-ffe9-11e8-8ac7-65f9bbb6fdf7.png)

So, PR already merge into saas-12.1 and now show buttons, but not fix this issue

**Comment by ged-odoo** [comment]
@celm1990 This bug is indeed fixed by PR #29389 in saas-12.1.  This should have been forward ported in master already, but it is not. I suppose that it will be done shortly...

**Comment by ged-odoo** [comment]
@celm1990 you are correct. This is fixed in 12.1 and should have been forward ported in master.  I assume this will be done shortly

**Comment by celm1990** [comment]
@ged-odoo your PR not fixed this issue, when I tested saas-12.1 PR already merge. Before PR no action buttons and not print buttons, after PR show action buttons, but not show print button and not load binding actions. Can you review again???

**Comment by ged-odoo** [comment]
@celm1990 you are right. I'll have a look

**Comment by ged-odoo** [comment]
this should be solved by https://github.com/odoo/odoo/pull/29633
