### ISSUE TITLE
Company logo doesn't want to change

### ISSUE THREAD

**Issue by oitsuki** [odoo/odoo#3035]
Hello,

I try to change my logo company inside Odoo. It doesn't work.

try : 
1 - I already have inserted a logo
## 2 - I click on modify and I insert my new logo : The old logo is always there.

1 - I already have inserted a logo
2 - I delete my old logo
## 3 - I try to change : the old logo come back

1 - I already have inserted a logo
2 - I delete my old logo
3 - I save my page
4 - I edit my page
5 - I  insert my new logo : the old logo come back

Maybe there is a cache ?

Thank you

**Comment by HarriL** [comment]
I had the same issue today. Multi-Company with two companies. None of the companied had a logo. Latest Odoo 8.0 / Ubuntu 14.04.1 / installed using apt-get = nightly version.

1. return from web shop to Odoo / admin
Set the first Company to have its own logo: as the Admin select  Settings/Company and add a logo there and save. 

2. Then return to web and do: edit and select your logo and save. This worked today for the same issue.

It seems that the 1. creates something into DB that is needed to save the another lo into the DB. It must be somekind of initilaization for company logos / pictures.

**Comment by setiaji** [comment]
I had solve today for this problem, here they are my steps :+1: 

1. Go to Settings > Companies
2. Click 'Edit' button and change the logo of your company
3. Click 'Save' and thats it :)

Hope this help :)

**Comment by Danisan** [comment]
This is an irritating issue, but fortunatedly can be solved with an addon from Yelizariev. It appends a unique url refference to each logo: (like  "?company_id=123") to avoid cached entry.
https://github.com/yelizariev/addons-yelizariev/tree/8.0/web_logo

**Comment by luisplanes** [comment]
@setiaji I agree. He has worked perfectly.

**Comment by jsh-odoo** [comment]
If we remove the logo, Odoo server will put it's default logo at the website. It is taking from image stored with source. Talking about width you are right. At website, Odoo server will apply the width and height constraint but not at the back end. @setiaji  suggested the proper way to change the company logo.

**Comment by l-arnold** [comment]
Not working here eihter, but it looks like the Web finally showed itself.  Will try edit next and make it PNG.

I can see how irritating this is for everyone.  Should be easier.

**Comment by icircletech** [comment]
I fixed my logo!

After looking at the "Sequences & Identifiers" in "Settings", I noticed the "Gamification" module had a listing for the "company_logo" with key #3 which got me to thinking about the awarded badge that would be enabled after completing the 3 tasks of setting up the company. I only completed the first one. (I never completed the other 2 tasks.) So the "Gamificiation" was locking the logo from being updated until the other 2 tasks are completed. So, I Killed "Gamifiaction" and my logo works after following the steps below. 

I tried the following:
- Removed "Gamification" Module,
- Turned off "Manage Multiple Companies" in "General Settings" (This step may not be needed).
- I changed the "Company Logo" to something else, then changed it back. (To refresh the image in the DB)
-Cleared the Cache on my browser (Chrome / Cookies and Images)
-Signed back in and Viola! had the logo I wanted!
-I went back and turned on the "Manage Multiple Companies" in "General Settings" and the logo remains fine.
 
 I like this method better than the workaround method listed above because it allows the logo to be changed anytime by using the traditional method in the company profile.

This may not apply to everyone, but it solved the problem for me! Hope this helps someone.

**Comment by Lindenk** [comment]
For me at least, the logo image references the file `http://example.com/web/binary/company_logo?db=testbug&company=1`, however, it should be referencing company 0 because I only have 1 company registered. Editing the HTML with chrome confirms this (the logo displays correctly if I change the number manually). Creating another company caused it to be registered as company 2 rather than 1, so I couldn't use a dummy company as a workaround.

When I was originally playing around with the settings, I selected the `multi-company` option, then disabled it. Apparently the `multi-company` module was still installed however, although, even after removing it and toggling the `multi-company` option, the logo image was still not fixed.

I'm using the docker image [here](https://registry.hub.docker.com/_/odoo/) as of its latest release.

**Comment by inyerade** [comment]
same as @Lindenk. Any solution?

**Comment by imjaypatel** [comment]
Follow ee304fa65f58ebf318f22cac97bf4f838f47414c commit that help you to change company logo.

After replace your logo need to clean browser cache.

This image will store as your company logo so don't forgot this, <a href="https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/static/img/main_partner-image.pngopenerp/addons/base/static/img/main_partner-image.png">View Company logo </a>

**Comment by ke-real** [comment]
just add after line
var img = this.session.url('/web/binary/company_logo' + '?db=' + this.session.db + (company ? '&company=' + company : ''));

this line:
        img += '&sid=' + this.session.session_id;

this will force company logo to be cached only during each session.

**Comment by ozarga** [comment]
@ke-real in which file (route) should we change/add the line? Thanks in advance

**Comment by ke-real** [comment]
@ozarga in odoo8 it is \addons\web\static\src\js\chrome.js
in odoo9 it is \addons\web\static\src\js\web_client.js

method name update_logo
this fixes updating of the logo. but it can still be referenced from user browser's cache in templates: web.menu_secondary and web.login_layout

I have it fixed via module extension:
/your_module/static/src/js/chrome.js: 
```javascript
var instance = openerp;
instance.web.WebClient.include({
    update_logo: function () {
        var company = this.session.company_id;
        var img = this.session.url('/web/binary/company_logo' + '?db=' + this.session.db + (company ? '&company=' + company : ''));
        img += '&sid=' + this.session.session_id;
        var d = new Date().toISOString().slice(0, 10);
        img += '&t=' + d;
        this.$('.oe_logo img').attr('src', '').attr('src', img);
        this.$('.oe_logo_edit').toggleClass('oe_logo_edit_admin', this.session.uid === 1);
    }
}
);
```

/your_module/webclient_templates.xml (needs to be referenced in your module's declaration data element):
```xml
<?xml version="1.0" encoding="utf-8"?>
<openerp>
  <data>
    <template id="login_layout" inherit_id="web.login_layout">
      <xpath expr="//div[@class='oe_single_form_logo']/img[1]" position="replace">
        <img t-attf-src="/web/binary/company_logo{{  ('?t=%s' % (20160229,) ) }}"/> //can be any random or date specific number here
      </xpath>
    </template>
    
    <template id="menu_secondary" inherit_id="web.menu_secondary">
      <xpath expr="//a[@class='oe_logo']/img[1]" position="replace">
        <img t-attf-src="/web/binary/company_logo{{  ('?t=%s' % (20160229,) )  }}"/> //can be any random number here
      </xpath>
    </template>

    <template id="assets_backend" name="your_module_assets" inherit_id="web.assets_backend">
      <xpath expr="." position="inside">
        <script type="text/javascript" src="/your_module/static/src/js/chrome.js"></script>
      </xpath>
    </template>
  </data>
</openerp>
```

HTH

**Comment by dreispt** [comment]
@oitsuki Is this still an Issue? Can it be closed?

**Comment by ozarga** [comment]
@dreispt Yes, it is still an issue, even in v9.0 ( #13169 #6756 )
@ke-real I was using Firefox but I will give it a try, thanks in advance. Will communicate results.

**Comment by ke-real** [comment]
@ozarga  it's not about particular browser, but browser cache in general. Odoo renders an image with src = url/web/binary/company_logo?db=odoo&company=1 so it will render an updated image only if:
1. you change db name used by odoo
2. you change company
3. you reset/refresh or disable browser cache

**Comment by pjmarquet** [comment]
Just create a Text Logo with InkScape
File > Export to .png > Select Zone > Export
You get a brand new right format Logo to insert in your Compagny (print a doc)...

**Comment by tibong** [comment]
clear cache

**Comment by Yenthe666** [comment]
Hi @oitsuki,

Thank you for the report.
Odoo 8 is no longer supported as a stable version (Odoo goes back three versions).
This problem is however fixed in the newest versions!

Regards,
Yenthe

**Comment by Netoperz** [comment]
it is not fixed, I have installed odoo 11 yesterday and the problem presists

**Comment by nurlanf** [comment]
Problem exists on odoo11 as well

**Comment by MafiaBoys** [comment]
<marquee style="font-family:Book Antiqua; color: #FFFFFF" bgcolor="#000080" scrolldelay="90">Thank for rever </marquee>

**Comment by Husam1985** [comment]
@AlanBell 

you are the champion of this page ...

but why this confusion happens !!
