### ISSUE TITLE
Translation terms for new API related fields are not exported

### ISSUE THREAD

**Issue by pedrobaeza** [odoo/odoo#3673]
When I have related fields in a custom module, and export translations for it, I don't get any of the strings of these fields (string nor help attributes).

Can you check it, @odony?

**Comment by yostashiro** [comment]
I've come across this issue as well.  Hope this gets fixed soon.

**Comment by pedrobaeza** [comment]
Any news on this issue?

**Comment by zaoral** [comment]
Hello, I present the same error. I created custom modules in [Vauxoo/addons-vauxoo](https://github.com/vauxoo/addons-vauxoo) repo. Have two PRs defined compute fields using api v8 and when export the translations template the fields defined were not added as a translation terms. 

I see that the PR #5684 seems to be a solution to this. What is missing to do the merge to core?.

Im aware that until this issue will be resolve I will add the missing translations terms manually to the translation template.

PD: here the two PR with the missing compute field terms translations:
- Vauxoo/addons-vauxoo#291 field [purchase_incoming_qty](https://github.com/Vauxoo/addons-vauxoo/pull/291/files#diff-f606b989083c6d655dc00761d4cda231R34).
- Vauxoo/addons-vauxoo#296 field [purchase_id](https://github.com/Vauxoo/addons-vauxoo/pull/296/files#diff-86b474b2d3c4e2d2941721686b503cddR34)

**Comment by lmignon** [comment]
A solution is provided in the PR https://github.com/odoo/odoo/pull/5618

**Comment by rco-odoo** [comment]
Fixed by #5618.

**Comment by ilexius** [comment]
Fro me this is still not working. #5618 puts all fields in ir_model_fields, but https://github.com/odoo/odoo/blob/8.0/openerp/tools/translate.py#L745 excludes all fields from export that are not in _columns. So calculated fields which are not stored are not exported.

**Comment by StefanRijnhart** [comment]
Thanks for the hint, @ilexius. Based on that, I created https://github.com/odoo/odoo/pull/9081. Could you give that a try?
