### ISSUE TITLE
[13.0] Export All Feature: Do not add "0" on blank m2o

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#37848]
Impacted versions: 13.0

Steps to reproduce:
Export List view with Blank m2o in Records
![Screenshot (3)](https://user-images.githubusercontent.com/16624719/66095497-5c2ff980-e5b5-11e9-9a23-fd2267bbd25d.png)

Current behavior: Blank M2o is replaced by 0 (Company Column)
![Screenshot from 2019-10-03 08-10-26](https://user-images.githubusercontent.com/16624719/66095606-ba5cdc80-e5b5-11e9-9595-74c8af726b79.png)

Expected behavior: Should be blank

Video/Screenshot link (optional):

**Comment by sswapnesh** [comment]
Sales Orders --> Taxes Column
![Screenshot](https://user-images.githubusercontent.com/16624719/66096465-acf52180-e5b8-11e9-9162-51c5b789ed88.png)

Here 0 should be there as it is float field
![Screenshot from 2019-10-03 08-34-18](https://user-images.githubusercontent.com/16624719/66096446-9bac1500-e5b8-11e9-9b06-54f6c0b74d11.png)

**Comment by msh-odoo** [comment]
@sswapnesh Should be fixed here: #36192

**Comment by sswapnesh** [comment]
Update:
Still is Adding **0** on Blank m2o
![Screenshot from 2019-12-28 23-40-16](https://user-images.githubusercontent.com/16624719/71547865-6b172400-29cb-11ea-9a70-0ad1836e03a8.png)

**Comment by pedrobaeza** [comment]
This should be fixed with #36192, so closing.

**Comment by sswapnesh** [comment]
> This should be fixed with #36192, so closing.

It is not fixed yet.
Tested again on latest Runbot http://1613011-13-0-7bd18f.runbot37.odoo.com/web?#action=825&model=sale.order&view_type=list&cids=&menu_id=585

![Screenshot from 2020-03-04 14-36-02](https://user-images.githubusercontent.com/16624719/75862945-b6174280-5e25-11ea-9c5e-2adfe12118b4.png)

**Comment by prakashjain** [comment]
Hello @pedrobaeza @Yenthe666 

The above issue (Odoo Export data Do not add "0" on blank m2o) still in odoo 14 latest git code.

the below code is fixing the issue:

**Odoo/models.py file (replaced False to '' in the below bold lines)**
 # in import_compat mode, m2m should always be exported as
                        # a comma-separated list of xids or names in a single cell
                        if import_compatible and field.type == 'many2many':
                            index = None
                            # find out which subfield the user wants & its
                            # location as we might not get it as the first
                            # column we encounter
                            for name in ['id', 'name', 'display_name']:
                                with contextlib.suppress(ValueError):
                                    index = fields2.index([name])
                                    break
                            if index is None:
                                # not found anything, assume we just want the
                                # name_get in the first column
                                name = None
                                index = i

                            if name == 'id':
                                xml_ids = [xid for _, xid in value.__ensure_xml_id()]
                                **current[index] = ','.join(xml_ids) or ''**
                            else:
                                **current[index] = field.convert_to_export(value, record) or ''**
                            continue

                        lines2 = value._export_rows(fields2, _is_toplevel_call=False)
                        if lines2:
                            # merge first line with record's main line
                            for j, val in enumerate(lines2[0]):
                                if val or isinstance(val, (int, float)):
                                    current[j] = val
                            # append the other lines at the end
                            lines += lines2[1:]
                        else:
                            **current[i] = ''**

In the odoo version 14 git official version can you please update the above  (Odoo Export data Do not add "0" on blank m2o) related fix?
