### ISSUE TITLE
Session Expired Exception

### ISSUE THREAD

**Issue by lekhnath** [odoo/odoo#37950]
Impacted versions: 13.0, Release: 20191003

Steps to reproduce: Go to /web/login and view std output

Current behavior: 
Following request results in OdooSessionExpired exception when user is logged out
POST http://localhost/web/dataset/call_kw/web_tour.tour/get_consumed_tours 

Expected behavior:
Should not get exception

Video/Screenshot link (optional):
![Screenshot_2019-10-04_09-49-34](https://user-images.githubusercontent.com/4231691/66180377-8accd380-e68c-11e9-8385-0132a8f7e8ec.png)
![Screenshot_2019-10-04_09-50-16](https://user-images.githubusercontent.com/4231691/66180383-90c2b480-e68c-11e9-9fe9-03c26acb450b.png)

**Comment by pedrobaeza** [comment]
Hi, thanks for reporting. Are you able to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by Yenthe666** [comment]
I think I saw @JKE-be responded somewhere that they found a similar issue and where checking it. Could you confirm @JKE-be?

**Comment by lekhnath** [comment]
@pedrobaeza Steps to reproduce this issue in runbot:

* Follow [this url](http://640479-13-0-fd0de2.runbot23.odoo.com) and select any database from the list [NOTE: select **640479-13-0-fd0de2-base** for faster page load]
* Reload your web browser as many times
* You'll get session expired notification. Image attached:
![Screenshot_2019-10-04_12-37-15](https://user-images.githubusercontent.com/4231691/66187124-c6bf6300-e6a3-11e9-9aa9-f9cf62e3d6bb.png)

**Comment by pedrobaeza** [comment]
OK, thanks for trying.

@odony maybe this is due to the rotating session strategy I have read about in other issue.

**Comment by sswapnesh** [comment]
Reload your web browser as many times

This is not needed, I can generate this without Refresh

Seems from  `/web/dataset/call_kw/web_tour.tour/get_consumed_tours`

**Comment by JKE-be** [comment]
Strange

I fixed the bug about get_consumed_tour 2 weeks ago...

Need to check thé fwdport probably...

kr 

Jeremy Kersten

**Comment by sswapnesh** [comment]
@JKE-be  I am also not sure about this

This is how I reproduced the Issue
![Screenshot (7)](https://user-images.githubusercontent.com/16624719/66238438-433e5a00-e715-11e9-95db-7468a393ca5e.png)
![Peek 2019-10-05 02-10](https://user-images.githubusercontent.com/16624719/66238503-5e10ce80-e715-11e9-9857-1585dd328d76.gif)

In log

```
"GET /my/invoices?model=account.move&res_id=9&access_token=a5171b35-b5e9-4390-a21e-c1c55ce0b3ed HTTP/1.1" 302 - 1 0.000 0.005
"GET /web/login?redirect=http%3A%2F%2Flocalhost%3A8069%2Fmy%2Finvoices%3Fmodel%3Daccount.move%26res_id%3D9%26access_token%3Da5171b35-b5e9-4390-a21e-c1c55ce0b3ed HTTP/1.1" 200 - 305 0.227 0.671
"POST /web/dataset/call_kw/web_tour.tour/get_consumed_tours HTTP/1.1" 200 - 1 0.001 0.004

```

**Comment by JKE-be** [comment]
oups strange, I don't see my code in v13...

https://github.com/odoo-dev/odoo/commit/fe523deec6ecbfe1005f8a19b3ee39209bc3a43b should fix it.

**Comment by Yenthe666** [comment]
@JKE-be can you manually port forward it into 13.0 please? It still present in todays builds and its bugging my newest customer 😆

**Comment by JKE-be** [comment]
wip here https://github.com/odoo/odoo/pull/38061

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/38061/commits/4c03b9939f19104d6e0edb5fa03afb7d7ba57aeb

**Comment by Yenthe666** [comment]
And at https://github.com/odoo/odoo/commit/fd7d9dc47bbce1819267e95c0f39ae69e477902f

**Comment by gustavovalverde** [comment]
Good, found my solution 😄

**Comment by gustavovalverde** [comment]
Good to know I'm not the only one doing this. https://github.com/odoo/odoo/issues/37950#issuecomment-538958210 

It's comforting hahahaha
