### ISSUE TITLE
[13.0] Couldn't Uninstall "CRM" module

### ISSUE THREAD

**Issue by sswapnesh** [odoo/odoo#38008]
Impacted versions: 13.0

Steps to reproduce: Uninstall CRM

Current behavior:
![Screenshot (9)](https://user-images.githubusercontent.com/16624719/66260896-3fc4d480-e7e2-11e9-8d78-6c53e0a20387.png)

```
2019-10-05 21:05:18,845 21909 INFO 13_sec odoo.addons.base.models.ir_model: Dropped FK CONSTRAINT calendar_event_opportunity_id_fkey@calendar.event 
2019-10-05 21:05:18,856 21909 INFO 13_sec odoo.models.unlink: User #1 deleted ir.model.constraint records with IDs: [393, 394, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433] 
2019-10-05 21:05:18,882 21909 WARNING 13_sec odoo.modules.loading: Transient module states were reset 
2019-10-05 21:05:18,885 21909 ERROR 13_sec odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 722, in get
    value = self._data[field][record._ids[0]]
KeyError: 3136

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/odoo/odoo/fields.py", line 1035, in __get__
    value = env.cache.get(record, self)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/api.py", line 728, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.model.fields(3136,).name', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sswapnesh/WorkSpace/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/modules/loading.py", line 476, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "<decorator-gen-60>", line 2, in module_uninstall
  File "/home/sswapnesh/WorkSpace/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/addons/base/models/ir_module.py", line 477, in module_uninstall
    self.env['ir.model.data']._module_data_uninstall(modules_to_remove)
  File "/home/sswapnesh/WorkSpace/odoo/odoo/addons/base/models/ir_model.py", line 1872, in _module_data_uninstall
    delete(self.env['ir.model.fields'].browse(field_ids))
  File "/home/sswapnesh/WorkSpace/odoo/odoo/addons/base/models/ir_model.py", line 1828, in delete
    records -= records.filtered(lambda f: f.name == 'id' or (
  File "/home/sswapnesh/WorkSpace/odoo/odoo/models.py", line 5083, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/sswapnesh/WorkSpace/odoo/odoo/models.py", line 5083, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/home/sswapnesh/WorkSpace/odoo/odoo/addons/base/models/ir_model.py", line 1828, in <lambda>
    records -= records.filtered(lambda f: f.name == 'id' or (
  File "/home/sswapnesh/WorkSpace/odoo/odoo/fields.py", line 1048, in __get__
    _("(Record: %s, User: %s)") % (record, env.uid),
odoo.exceptions.MissingError: ('Record does not exist or has been deleted.\n(Record: ir.model.fields(3136,), User: 1)', None)
2019-10-05 21:05:18,886 21909 WARNING 13_sec odoo.http: ('Record does not exist or has been deleted.\n(Record: ir.model.fields(3136,), User: 1)', None) 
```

Expected behavior: Successfully Uninstallation

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
I think this can be solved with #37957

**Comment by Feyensv** [comment]
Seems it has been solved by https://github.com/odoo/odoo/pull/37957 indeed.
@sswapnesh can you check and close the issue it if it works for you ? :)

**Comment by sswapnesh** [comment]
> can you check and close the issue it if it works for you ? :)

![Screenshot (24)](https://user-images.githubusercontent.com/16624719/66414473-1b057280-ea17-11e9-8976-58ac5f092d1e.png)

PS: You have to Follow this Steps twice
Install --> Uninstall--> Install --> Uninstall, Hee you will get Error.

I was not aware of this fact while posting this.

**Comment by Yenthe666** [comment]
Confirmed & still reproducable (after doing it twice):
![image](https://user-images.githubusercontent.com/6352350/68685278-2abe2c80-056a-11ea-816e-b5e2f98b8c6a.png)

**Comment by sswapnesh** [comment]
Fixed in https://github.com/odoo/odoo/pull/48658

**Comment by gustavovalverde** [comment]
Got here as this also happens with `studio_customization`, might have to create an enterprise issue for that one.
