### ISSUE TITLE
Method fields_view_get_address returns untranslated XML

### ISSUE THREAD

**Issue by Yajo** [odoo/odoo#4060]
In an empty database, with Spanish language, install module `contacts`, and then go to the screen of creating a new contact. It appears like this:

![captura de pantalla de 2014-12-05 10 40 14](https://cloud.githubusercontent.com/assets/973709/5313640/28c671d6-7c6b-11e4-8d18-15a47531f70e.png)

The `<div class="addres_format">` fields (highlighted in green) appear with **Spanish placeholders** (good!).

Now, edit your user's company's details and set country: Spain. Then again create a new partner. See the results:

![captura de pantalla de 2014-12-05 10 42 53](https://cloud.githubusercontent.com/assets/973709/5313669/80b849f0-7c6b-11e4-96fa-8a3dd6c4a5c0.png)

This time **those placeholders appear in English**. (Also, badly styled, but merge https://github.com/odoo/odoo/pull/4059 and that gets fixed).

I imagine [the function `fields_view_get_address`](https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/res/res_partner.py#L63) gets processed after the translation instead of before, and so the XML it injects is always in English.

**Comment by mart-e** [comment]
Fixed at 44d155d

**Comment by Yajo** [comment]
After updating, it still happens the same. Is it because the Spanish translation must be updated?

**Comment by mart-e** [comment]
It's already [in the translations](https://github.com/odoo/odoo/blob/8e03852fd4b9fcd6c18e2a6c78298be731d4df0c/openerp/addons/base/i18n/es.po#L9493) so you just need to update your translations.
