### ISSUE TITLE
[12.0] Error when updating all modules and the odoo studio is being used

### ISSUE THREAD

**Issue by CarmenMiranda** [odoo/odoo#43880]
**Impacted versions:**
12.0

**Steps to reproduce**

1. Do any change with Odoo Studio
2. Update all modules.

**Current behavior:**
After reproducing the steps above we got the following error:
`2020-01-23 22:21:13,212 3391 ERROR database odoo.modules.loading: Some module are not loaded, some dependency may be missing: ['studio_customization']`

The changes made with `odoo_studio` generate some external ids that have the module `studio_customization` for example `studio_customization.new_record`.  Odoo Studio installs the `studio_customization` module. 
![Studio Customization Module](https://user-images.githubusercontent.com/26889951/73026706-896c1600-3df7-11ea-9031-ae5602f8cb04.png)

This error comes after the following commit: https://github.com/odoo/odoo/commit/c5d6a3977de85fb974a4940fb11d54ef847e08e4

***Expected behavior***
Modules should be updated without causing any error.

**Comment by CarmenMiranda** [comment]
***OPW #2180885***

**Comment by Xavier-Do** [comment]
I take care of this

**Comment by Yenthe666** [comment]
Should be fixedin https://github.com/odoo/odoo/commit/4051ac83b5e7cc1cb91a264b51401ad5601ad4e2

**Comment by atchuthan** [comment]
I am using the latest commit from 13.0 and I am still getting Error for "studio_customization".
Also, I took a DB backup from production and restored it in my local and got the error after doing -u all for the restored DB.
Any info is much appreciated

2020-09-18 15:50:24,217 19 INFO Custdemo_V13_oca_avatax odoo.modules.loading: 139 modules loaded in 255.93s, 0 queries 
2020-09-18 15:50:24,289 19 INFO Custdemo_V13_oca_avatax odoo.modules.loading: loading 139 modules... 
2020-09-18 15:50:24,289 19 INFO Custdemo_V13_oca_avatax odoo.modules.loading: 139 modules loaded in 0.00s, 0 queries 
2020-09-18 15:50:24,347 19 INFO Custdemo_V13_oca_avatax odoo.modules.loading: loading 139 modules... 
2020-09-18 15:50:24,348 19 INFO Custdemo_V13_oca_avatax odoo.modules.loading: 139 modules loaded in 0.00s, 0 queries 
2020-09-18 15:50:24,349 19 ERROR Custdemo_V13_oca_avatax odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['studio_customization'] 
2020-09-18 15:50:25,123 19 INFO Custdemo_V13_oca_avatax odoo.addons.base.models.ir_model: Deleting 822@ir.model.access (website.access_website_visitor_system) 
2020-09-18 15:50:25,169 19 INFO Custdemo_V13_oca_avatax odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [695479]

**Comment by joseponzo** [comment]
same error in version 14, also the cron stops working
Steps to reproduce
Do any change with Odoo Studio
Update all modules.
Current behavior:
After reproducing the steps above we got the following error:
WARNING ? odoo.addons.base.models.ir_cron: Skipping database xyz because of modules to install/upgrade/remove.
ERROR xyz odoo.modules.loading: Some modules have inconsistent states, some dependencies may be missing: ['studio_customization']
to reactivate the cron I go to the module (studio_customization) and canceled its update by hand. 
the warning disappeared but the error persists in the log

**Comment by Xavier-Do** [comment]
@atchuthan @joseponzo 

This look similar but is not linked to this issue. 

A dependency on web_studio was added when creating studio_customization module since v13 causing studio_customization to be marked as to upgrade when updating base or web_studio. We will fix that soon.
