### ISSUE TITLE
[13.0] settings: Coupons & Promotions

### ISSUE THREAD

**Issue by florinmarica** [odoo/odoo#44713]
Impacted versions:
13 comunity
Steps to reproduce:
I don't know

Current behavior:
I have a database where I want to activate Coupons & Promotions from settings, in the settings this option have Enterprise tag on it. if I want to check it it behave like this is an Enterprise option, but if I install it from Apps, the checkbox is checked and everything seems to work well.

Expected behavior:
The Coupons & Promotions checkbox should not have the Enterprise tag.

Video/Screenshot link (optional):

![image](https://user-images.githubusercontent.com/8156735/73941383-d7077900-48f5-11ea-9ccb-b0b08daa5fd8.png)

**Comment by pedrobaeza** [comment]
@mart-e maybe a forgotten piece of its enterprise inheritance?

**Comment by florinmarica** [comment]
> @mart-e maybe a forgotten piece of its enterprise inheritance?

I create an other 2 databases and I can't reproduce this

**Comment by pedrobaeza** [comment]
Have you tried in runbot (https://runbot.odoo.com)?

**Comment by mart-e** [comment]
I don't have the problem on the runbot. Do you see this on Website or in Sale settings ?

**Comment by florinmarica** [comment]
> I don't have the problem on the runbot. Do you see this on Website or in Sale settings ?

Both

**Comment by mart-e** [comment]
From when was your database created? The issue seems fixed since 82465461387a2802cc8521ef22770edb753a8c05 and aca5feb6e06b0902d169aaabaa39e3af7d31534b

> I create an other 2 databases and I can't reproduce this

This would confirm it was already fixed.
Try updating the sale menu and it should be fine.

**Comment by florinmarica** [comment]
> From when was your database created? The issue seems fixed since [8246546](https://github.com/odoo/odoo/commit/82465461387a2802cc8521ef22770edb753a8c05) and [aca5feb](https://github.com/odoo/odoo/commit/aca5feb6e06b0902d169aaabaa39e3af7d31534b)
> 
> > I create an other 2 databases and I can't reproduce this
> 
> This would confirm it was already fixed.
> Try updating the sale menu and it should be fine.

All 3 databases are new databases created today with the same odoo files.
I updated the sale module and the problem persist

**Comment by mart-e** [comment]
I understood your message as you have the issue only in the latest version.
Is your source code [up to date](https://www.odoo.com/documentation/13.0/setup/update.html)?

**Comment by florinmarica** [comment]
> I understood your message as you have the issue only in the latest version.
> Is your source code [up to date](https://www.odoo.com/documentation/13.0/setup/update.html)?
I downloaded the version from 04.02.2020 from github. I'm just testing and I found this. Do you think was fixed from 04.02 ?

**Comment by mart-e** [comment]
It was fixed already long ago so this is very odd you still have this issue.

![Screenshot_2020-02-06 New - Odoo](https://user-images.githubusercontent.com/564822/73950475-47b19400-48fc-11ea-9c5f-873f508e1b9d.png)

Could you describe a bit more how you installed Odoo? Are you sure it is version 13.0? It is not possible you have leftovers from a previous installation?

**Comment by florinmarica** [comment]
> It was fixed already long ago so this is very odd you still have this issue.
> 
> ![Screenshot_2020-02-06 New - Odoo](https://user-images.githubusercontent.com/564822/73950475-47b19400-48fc-11ea-9c5f-873f508e1b9d.png)
> 
> Could you describe a bit more how you installed Odoo? Are you sure it is version 13.0? It is not possible you have leftovers from a previous installation?

I don't install it, I downloaded the zip from github, created a config file and start it in PyCharm, I checked everything and I don't think I have leftovers from a previous installation. This is first time using odoo 13, I'm using odoo 11 and I want to switch to 13, but I have some unexpected problems. Now if I create a new database everything looks ok. But I already add some products with variation on that database and I didn't find a good way to export/import them from one db to another.

**Comment by mart-e** [comment]
Sorry but I can't do much more if we do not have a way to reproduce it on a standard version (as Pedro said, test it on [a runbot](http://runbot.odoo.com/runbot)).
Check the content of the files you have downloaded to see if you indeed have the two fixes I gave.
You can also check in the database the content of the view (in Settings > Technical > Views) to make sure both these views do not have the upgrade_boolean flag.
