### ISSUE TITLE
[8.0] Client sends unmodified fields for write() due to rounding issues

### ISSUE THREAD

**Issue by adrienpeiffer** [odoo/odoo#4564]
Hi,

When the user modifies a record in the web client, only the modified fields are sent to the write() method on the server. However, in some cases, with float fields, fields that are not changed by the user are sent to the write() method on the server.

How to reproduce:
- go to runbot and open the chrome debugger to trace network calls
- create an account move with one line with name = / and debit = 10
- click save
- click edit and change the name fo the move line to /b
- click save
- notice in the chrome debugger that only the line name (/b) is sent to the write() call, this is ok
- now change the debit to 2608.7 (this value is important)
- click save
- notice in the chrome debugger that only the new debit value (2608.7) is sent to the write() call, this is ok
- now change the name of the line to /c
- click save
- notice in the chrome debugger that the new name (/c) is sent to the write() call, but also the debit value (2608.7) which we did not change -> this is not ok

We believe the comparison on the javascript side to decide if a value has changed or not should take the decimal accuracy into account. But we can't find where this comparison takes place in the javascript call.

This is blocking production issue due to some validation rules failing when writing values that should not change in some state.

Thanks in advance,

**Comment by adrienpeiffer** [comment]
Fix in #4565

**Comment by sbidoul** [comment]
OPW 621782

**Comment by sbidoul** [comment]
Here is a debugger screenshot illustrating the issue:

![image](https://cloud.githubusercontent.com/assets/692075/5643007/fd4ba164-9652-11e4-8a48-dff750546b36.png)

**Comment by ged-odoo** [comment]
@adrienpeiffer The fix #4565 does not solve the issue.  It only makes sure that the formatting in the graph view is correct.  This issue is different.

**Comment by adrienpeiffer** [comment]
@ged-odoo  Thanks for you answer ! 
However, the comparison problem appears to come from the error of formatting. see the screenshot of Chrome debugger on this issue. in this case, the formatting isn't applied on the field so it's concidered as different. With #4565, the field is formatted before comparison so it's not returned to the write method.

**Comment by sbidoul** [comment]
@ged-odoo we are not sure the fix #4565 is at the root cause, but it *does* fix the symptom.

**Comment by ged-odoo** [comment]
for some reason, i was talking about a different PR.  i was confused (too many tabs open I guess).

So, you're right, it does fix the problem.  However, I'm still investigating if this is the best way to proceed.

**Comment by sbidoul** [comment]
@ged-odoo I can understand the mistake :wink:

**Comment by adrienpeiffer** [comment]
@ged-odoo Any news about this issue

**Comment by ged-odoo** [comment]
will finish this issue this morning.  still on my list

**Comment by adrienpeiffer** [comment]
Thanks

**Comment by ged-odoo** [comment]
fixed in 37e85a1e3520317e5.  Thank you for your help

**Comment by adrienpeiffer** [comment]
@ged-odoo Currently, the problem presented in this issue isn't fixed. Can you reopen this one ?

**Comment by dhr-odoo** [comment]
Fixed in commit :  d17f22c
