### ISSUE TITLE
Updating stock on product with variants results in empty dialog with non-closeable buttons.

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#4842]
**Dialog and buttons do not load in correctly**

Impacted versions:
- 8.0 and above

Steps to reproduce:
1. create a new product.
2. Add some product variants to it.
3. Save everything
4. Go to quantity on hand and click on 'Update'.
5. You will get the following warning:
       Warning
       Please use the Product Variant view to update the product quantity.
6. Close this warning dialog and you'll see a second dialog behind this. It will look like this:
   <img src="http://i.imgur.com/gFdwe3m.png"/>

Current behavior:
- Warning dialog shows up with another screen behind it which does not work. The buttons do not load & you can not click on them either. The only way to close the dialog is through the 'x'.

Expected behavior:
- Screen behind the warning either loads and <b>does</b> allow updating the stock from here or the screen is not shown.

**Comment by gurneyalex** [comment]
@odony can odoo you consider a fix for this? It is fixed in v9 but annoying in v8...

**Comment by Yenthe666** [comment]
Hi @jco-odoo,

Could you please have a look at this one and fix it? Note that it is fixed in V9 so a backport might be available.
Thanks.

**Comment by Yenthe666** [comment]
Update: still present in 8.0, not in 9.0 and 10.0
@nim-odoo perhaps for you?

**Comment by Yenthe666** [comment]
Closing as Odoo 8.0 is no longer supported.
