### ISSUE TITLE
[12.0/13.0] Leave creation timezone issue

### ISSUE THREAD

**Issue by reinaldoramosarxi** [odoo/odoo#49234]
Hello,

A client of ours has a multi-company environment with companies in several different countries. 

They noticed an error whenever the leaves manager creates leaves for employees that belong to other companies not in the same timezone.

After analyzing the issue, we concluded that whenever leaves are being created they are using the timezone of the user, and not of the employee that has been selected. This means that on leave creation, a manager that has the GMT+1 TZ, for example, a "Day" type leave for an employee with the GMT TZ, the total time calculation will be incorrect (won't be a full day, in that case).

It would work correctly if when setting the "tz" variable that is then used for the time calculations, the employee's timezone would be used first and only use the user's timezone as a last resort (in case the employee's timezone isn't set):

v12.0: https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L315
v13.0: https://github.com/odoo/odoo/blob/13.0/addons/hr_holidays/models/hr_leave.py#L345

E.G.: tz = self.employee_id and self.employee_id.tz or self.env.user.tz if self.env.user.tz and not self.request_unit_custom else 'UTC'  # custom -> already in UTC

This was tested in runbot, local servers and staging servers.

Thank you.

**Comment by LucasLefevre** [comment]
Hello @reinaldoramosarxi 
Thanks for the feedback.
This issue was fixed in v13.1 with https://github.com/odoo/odoo/commit/4f59004a0f407e93cfed2126198208738ed47f9a
Could you check that it works as you expect in 13.1 or with this commit ?
If it does, we will consider backporting the fix.
Thanks

**Comment by reinaldoramosarxi** [comment]
Hello,

I tested it on demo.odoo.com and it still shows 0.88 days instead of a full day.

Since I wasn't sure that the demo.odoo.com had this update, I tried it on a 13.3 version on runbot, but there are now several errors relating to permissions, and most forms in the Time Off module aren't editable.

I hope this helps.

Thank you.

**Comment by tivisse** [comment]
Hi @reinaldoramosarxi 

Thanks for the feedback !

Internal task opened to investigate: https://www.odoo.com/web#id=2255865&action=333&active_id=1251&model=project.task&view_type=form&cids=1&menu_id=4720

We'll keep you updated ;)

Have a nice day,

Yannick.

**Comment by cah-link** [comment]
Hello There,
This issue is marked as closed. Is it solved?
How is its state? 

Thank you.

**Comment by Yenthe666** [comment]
@cah-link it was made an internal task. As long as there is no feedback it means it is most likely still in the todo list and nothing has happened yet.

**Comment by cah-link** [comment]
@Yenthe666  I see.
Thank you for that quick reply!

**Comment by tivisse** [comment]
After a long time, finally deployed in 12.0 at https://github.com/odoo/odoo/pull/57493

Thanks :)
