### ISSUE TITLE
Purchase Suggest Qty & Price Issue...

### ISSUE THREAD

**Issue by jaronemo** [odoo/odoo#52035]
Impacted versions: 12.0 13.0

Steps to reproduce:
1、Product configure
![image](https://user-images.githubusercontent.com/8476734/83108759-d720c400-a0f2-11ea-9a84-9915f5d85cd6.png)
2、Purchase rfq order ...use this product..it will bring 500 qty..and price $10.
![image](https://user-images.githubusercontent.com/8476734/83108901-0c2d1680-a0f3-11ea-898b-954339aba1af.png)
3、change this qty.. to 1200 ...
![image](https://user-images.githubusercontent.com/8476734/83108989-2ebf2f80-a0f3-11ea-8e8f-ce56e2a64000.png)

Current behavior:
1、change qty...price need change...
![image](https://user-images.githubusercontent.com/8476734/83109105-5ca47400-a0f3-11ea-9114-27643863579a.png)

**Comment by tanghulu0608** [comment]
I think this should be fixed.

**Comment by pedrobaeza** [comment]
Yes, this is working in latest source code version:

https://2839253-12-0-85fe44.runbot31.odoo.com/web#id=10&action=729&model=purchase.order&view_type=form&menu_id=494

Closing as fixed.

**Comment by jaronemo** [comment]
But..i pull 12 version code...try this functions...is still failed.

**Comment by pedrobaeza** [comment]
Yeah, but for v13 is fixed, so unless you have an enterprise contract, and put a ticket in odoo.com/help asking for a backport of the fix, this is considered fixed in the latest Odoo version.

**Comment by jaronemo** [comment]
Dear Sir:
follow your runbot link.. test it.
https://2839253-12-0-85fe44.runbot31.odoo.com/web#id=10&action=729&model=purchase.order&view_type=form&menu_id=494

if product , have 3 qty & price...
![image](https://user-images.githubusercontent.com/8476734/83137078-1d8a1900-a11b-11ea-92d5-895e7a47498e.png)

![image](https://user-images.githubusercontent.com/8476734/83137183-4f02e480-a11b-11ea-8e6c-e755e0a5eb46.png)

**Comment by pedrobaeza** [comment]
The order of the vendor items seems not correct.
