### ISSUE TITLE
Stripe "Server Error: We are not able to redirect you to the payment form. id"

### ISSUE THREAD

**Issue by dirceu3h** [odoo/odoo#52122]
Impacted versions: odoo 13 community

Steps to reproduce:
Enable and configure stripe payment method with a testing api keys from stripe.com
In the checkout screen when select "Credit Card (powered by Stripe)" as payment method and click on "Pay Now".

Current behavior:
it shows the Server Error: We are not able to redirect you to the payment form. id
This is the output from browser console:
uncaught exception: undefined
warning: Some modules could not be started web.assets_common_minimal_js.js:85:344
Missing dependencies:     
Array [ "website.customizeMenu" ]
web.assets_common_minimal_js.js:85:465
Rejected modules:         
Array [ "web_tour.tour" ]
web.assets_common_minimal_js.js:87:24
Non loaded modules:       
Array [ "website.set_view_track" ]
web.assets_common_minimal_js.js:89:24
Server application error
 Error code: 200 
 Error message: Odoo Server Error 
 Error data message:
 id 
 Error data debug:
 Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/website_sale/controllers/main.py", line 922, in payment_transaction
    return transaction.render_sale_button(order)
  File "/opt/odoo13/odoo/addons/sale/models/payment.py", line 179, in render_sale_button
    values=values,
  File "/opt/odoo13/odoo/addons/payment/models/payment_acquirer.py", line 466, in render
    values = method(values)
  File "/opt/odoo13/odoo/addons/payment_stripe/models/payment.py", line 55, in stripe_form_generate_values
    tx_values['session_id'] = self._create_stripe_session(stripe_session_data)
  File "/opt/odoo13/odoo/addons/payment_stripe/models/payment.py", line 88, in _create_stripe_session
    return resp['id']
KeyError: 'id'
web.assets_common_lazy.js:3726:309
uncaught exception: Object 3

Expected behavior:
It should show the stripe form to introduce credit card information

[odoo stripe error](https://user-images.githubusercontent.com/42354147/83161748-1389fb00-a0c6-11ea-91b9-f4dcb0a7bafe.png)

**Comment by pedrobaeza** [comment]
Are you using latest available source code?

**Comment by dirceu3h** [comment]
i am using source code from about a month ago. Should i update it?

**Comment by pedrobaeza** [comment]
Yes, there has been changes since then that might affect. You always need to make the test with latest code for being sure it's not fixed already.

**Comment by dirceu3h** [comment]
thanks, i hope it's not too much to ask. Could you point to a guide or instructions to update?
i am using odoo 13 community version on a ubuntu 18.04 server.
i used this guide to install it https://linuxize.com/post/how-to-install-odoo-13-on-ubuntu-18-04/

**Comment by pedrobaeza** [comment]
Sorry, but this is on your side. I see that you downloaded Odoo GitHub repository, so you have to do  `git pull` on that folder.

**Comment by dirceu3h** [comment]
thanks for all

**Comment by dirceu3h** [comment]
Hello Pedro,
just to let you know that updating source code worked perfectly.
thanks a lot

**Comment by unpluggit** [comment]
@pedrobaeza is this also sorted on Odoo online?

I'm getting the same issue with a south african payment acquirer payfast.

Server Error:
We are not able to redirect you to the payment form. Error when compiling AST

**Comment by pedrobaeza** [comment]
@unpluggit Each acquirer has its own code, so for that one, you should explicitly check the problem. If you are in Odoo online, you should have an enterprise license and you can put a ticket at odoo.com/help telling about the problem, but only if the module belongs to Odoo core addons (not third party).

**Comment by Yenthe666** [comment]
@pedrobaeza Odoo online cannot have third party apps remember? 😉

**Comment by pedrobaeza** [comment]
Yeah, I know, but I'm not sure that "Odoo online" is in fact "Odoo.sh", that is "online" too, as I don't remember payfast as core addon :wink:

**Comment by EsrefDurna** [comment]
this error exists on latest build as well.

**Comment by K-MeLeOn** [comment]
Yes.. We hope in you for resolve it 👍

**Comment by nrome-n** [comment]
i am having the same problem on odoo.sh odoo 13 has anyone manage to solve it

**Comment by dirceu3h** [comment]
I did, just updated my source code to the latest version

**Comment by EsrefDurna** [comment]
ok I fixed it.

You have to configure journal for your payment acquirer 

Payment Acquirers > paypal or whatever > 
configuration Tab
Payment Followup 
Payment Journal - < should not be null.

**Comment by tarbib** [comment]
Hello,

I still have the issue described by @dirceu3h. I did the git pull (I installed Odoo with @Yenthe666 's script => git pull in odoo/odoo-server) and I have a payment journal. I additionally rebooted the server and upgraded all the installed modules.
![image](https://user-images.githubusercontent.com/2255433/88466261-d033e900-ceca-11ea-8625-87d75ae37db2.png)

Any ideas where else could I look at?

**Comment by implementosk** [comment]
Hi,

Got the same error.

Changed amount to be paid via Stripe to be over 0,50 eur,-

**Comment by lavanya-v96** [comment]
Make sure that you have set an account or business name at https://dashboard.stripe.com/account.
