### ISSUE TITLE
[11.0] Odoo incompatible with Python 3.8.4

### ISSUE THREAD

**Issue by bhaveshselarka** [odoo/odoo#54622]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x10fb33700>, 1078, ('en_US', None, None, None, False, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/addons/base/ir/ir_qweb/qweb.py", line 330, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: 1078
Path: /templates/t/html/body/div[2]/main/t/t
Node: <t t-content="True"/>
                    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x10fb33700>, 1074, ('en_US', None, None, None, False, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bhaveshselarka/ws/odoo/odoo_v11/odoo/addons/base/ir/ir_qweb/qweb.py", line 330, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: 1074
Path: /templates/t/t/div/t/t
Node: <t t-content="True"/>

**Comment by pedrobaeza** [comment]
That's something expected, as that is an old version (almost deprecated - will be in October), and anyway the compatibility is not assured with latest Python versions even in the latest one. There's intention of so, but it's only a best effort one.

Run it with the recommended one (P3.5).

Closing as won't fix.

**Comment by RobertaBtt** [comment]
![image](https://user-images.githubusercontent.com/22592182/95840561-95f91b80-0d44-11eb-885d-daf082430170.png)
I have Odoo 12 in Ubuntu Server 20.0 with Python 3.8.5

Can you tell me please if alsdo Odoo 12.0 won't be fix?
Thank you

**Comment by bhaveshselarka** [comment]
https://github.com/odoo/odoo/issues/59703

**Comment by odony** [comment]
> Can you tell me please if also Odoo 12.0 won't be fix?

@RobertaBtt It's now fixed in 12.0 via #59630, so you can just update.

**Comment by manishkbohra** [comment]
Hello @Yenthe666 and @pedrobaeza, 

This issue still with odoo v11.
I've already updated code into my local machine. 
Python version - 3.8.5
![Uploading Screenshot from 2020-10-21 14-14-27.png…]()

**Comment by pedrobaeza** [comment]
Yes, Odoo 11.0 is not going to be update to be used with Python 3.8 as it's out of official support.

**Comment by Yenthe666** [comment]
Yep, one of the reasons to upgrade to a new(er) version :)
