### ISSUE TITLE
[12.0] Link in notification mail doesn't change user's company

### ISSUE THREAD

**Issue by sa3m** [odoo/odoo#55846]
Impacted versions: 12.0

Steps to reproduce: A user with access to 2 companies receives a notification mail with a link to a document from the company that is not his current company

Current behavior: The user is redirected to the discussion app without any answer

Expected behavior: The user should see the document with the correct company or at least be shown a message saying to change the company.

Video/Screenshot link (optional):
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/301632/90112594-ecc19380-dd9b-11ea-8b03-99feb5144341.png">

**Comment by pedrobaeza** [comment]
Well, this usually happens when the target document has been removed. I think the link to a document from other company gets you to an access error. In any case, it's a known limitation that fortunately has been solved in v13, but it's not possible to backport that change to lower versions.

Closing thus as fixed in upper versions.

**Comment by sa3m** [comment]
It really was a true example of an actual PO that still exists.
Thank you for the answer, I was surprised to be the alone is this case since I found no mention to this limitation.

**Comment by pedrobaeza** [comment]
For a little more information, in v13 there's a new argument in the URL called `cid`, that allows to force a company to be shown, and this ways, it doesn't matter where you are "logged", that will be changed following the link.
