### ISSUE TITLE
Odoo 13 Not compilable with Python 3.8.5

### ISSUE THREAD

**Issue by manishkbohra** [odoo/odoo#59565]
Impacted versions: Odoo13

Steps to reproduce: Run odoo using python 3.8

Current behavior:
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x7f8065d3fe50>, 219, (None, None, None, None, None, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/qweb.py", line 315, in compile
    unsafe_eval(compile(astmod, '<template>', 'exec'), ns)
ValueError: Name node can't be used with 'None' constant

Error when compiling AST
ValueError: Name node can't be used with 'None' constant
Template: web.styles_company_report
Path: /t/t/t[10]

Expected behavior:
Odoo works with the newest stable python release

Video/Screenshot link (optional):

**Comment by pedrobaeza** [comment]
Yesterday a patch was merged. Can you please try with latest code version?

**Comment by Yenthe666** [comment]
Fixed in https://github.com/odoo/odoo/pull/59480.
I've tested in on two instances and it solves the issues.

**Comment by manishkbohra** [comment]
Hello, @pedrobaeza and @Yenthe666. I've to install odoo13 in a new machine with Ubuntu 20.04 and Python 3.8.5. But it's still showing me this one issue. 

Let me check again in another machine.

**Comment by xpeco** [comment]
Verified. Tested on multiple instances with good results

**Comment by BibekLamichhane** [comment]
I even got the issue in my system once python was updateded to 3.8.5. I did apply the fixes of #59480 but this made by menu button unresponsive.

**Comment by manishkbohra** [comment]
Hello, @Yenthe666 and @pedrobaeza Issue is fixed thanks.
