### ISSUE TITLE
Odoo 12 - widget="priority" Does not respect the readonly attribute tag 

### ISSUE THREAD

**Issue by gustotc** [odoo/odoo#65240]
Fields with the = "priority" widget, the read-only attribute does not work, lets you change it, shows it on the screen and only in the refresh that returns to the previous content.

Impacted versions:12.0

Steps to reproduce: 
CRM "priority" field, with xpath

For example:
<xpath expr = "// field [@ name = 'priority']" position = "attributes">
                 <attribute name = "attrs"> {'readonly': [('priority_type', '! =', 'manual')]} </attribute>
             </xpath>

Current behavior: Let the field change and only return to the value recorded in the screen refresh.

Expected behavior: Don't let change

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by Yenthe666** [comment]
There was another report about this some years back in https://github.com/odoo/odoo/issues/40641.
It was fixed by @msh-odoo but seems to be back then. @msh-odoo can you have a look?

**Comment by gustotc** [comment]
> There was another report about this some years back in #40641.
> It was fixed by @msh-odoo but seems to be done for V13-master, not V12. @msh-odoo can you have a look?

I searched for the commit via git cherry-pick 53dbfc7a65a8eb2f41d6b2373cf628c4800d1f57 for version 12 of Odoo and it worked in the form, however in kanban the same problem is still good.
