### ISSUE TITLE
"No valid cursor found" when searching a number field in account.invoice

### ISSUE THREAD

**Issue by nafex** [odoo/odoo#6650]
after this pull https://github.com/odoo/odoo/pull/6609 it is no more possible to search for number fields in account.invoice if you group by something e.g. period...
you will get "No valid cursor found" error

tested on latest v8 on runbot

**Comment by nafex** [comment]
fixed with https://github.com/odoo/odoo/pull/6646

**Comment by nafex** [comment]
sorry, #6646 don't fixed my issue...

**Comment by LeartS** [comment]
Can confirm that the issue is still present when doing a search for a float field with a groupby active, just tested on latest runbot.
