### ISSUE TITLE
sales user cannot open pickings

### ISSUE THREAD

**Issue by mhabboush97** [odoo/odoo#69432]
Impacted versions:
14, maybe others
Steps to reproduce:
open runbot
create user with only sales access rights
open from that user
confirm SO
click pickings icon
Current behavior:
access right error on stock.scrap
Expected behavior:
sales user should be able to view his pickings
Video/Screenshot link (optional):
![image](https://user-images.githubusercontent.com/71262174/115142018-15dfa580-a048-11eb-875b-40e33eae2660.png)

** I tried to hide scrap button in picking form view using groups, but the error still appears
Support ticket number submitted via odoo.com/help (optional):

**Comment by sswapnesh** [comment]
Added fix on https://github.com/odoo/odoo/pull/69434

**Comment by mhabboush97** [comment]
@sswapnesh the sales user must be able to see the pickings and their status, he already have access to different actions on picking such as cancel and unreserve! He already have read/write access on picking and stock moves
I don't think this is how this should be solved

**Comment by sswapnesh** [comment]
@mhabboush97 

> he already have access to different actions on picking such as cancel and unreserve! He already have read/write access on picking and stock moves

Yes, You are right.

I have updated my Patch.

https://github.com/odoo/odoo/pull/69434/commits/f4a1d744a959f94d4c2132e2f155b04bc5c58d5f

**Comment by mhabboush97** [comment]
@sswapnesh This would fix it, but I don't think it is optimal
first, why the error still appear even after hiding the scrap button?
second, read access is enough,
third, since he cannot make scrap, nor he can make returns (no wizard access rights), both buttons should be hidden from his view using groups

**Comment by sswapnesh** [comment]
> since he cannot make scrap, nor he can make returns (no wizard access rights), both buttons should be hidden from his view using groups.

I know user cannot make Returns. (Need to add access rights for Return wiz and lines)

>  first, why the error still appear even after hiding the scrap button?

Not sure but seems like, it is trying to access scrap_ids from move. (Just a guess)

May be @amoyaux  can suggest a better fix

**Comment by mhabboush97** [comment]
@sswapnesh
I guess it is more logical to give him just read access to fix the issue, and hide scrap and return buttons
Sales user is not responsible for doing scraps or returns, I guess it is better to keep his picking view clean, right?
