### ISSUE TITLE
[ALL] HTML fields cause XMLRPC clients to crash

### ISSUE THREAD

**Issue by chrisandrewmann** [odoo/odoo#74884]
Impacted versions: 
Master, 14.0

Steps to reproduce: 
Using XMLRPC, retrieve any HTML field from any model and find that it's content is not escaped, causing the XMLRPC client to error due to illegal XML format. Particularly noticed on Master in calendar.event and res.partner as comments / notes fields are now HTML.

Current behavior:
XMLRPC client crashes. I'm using CookComputing.XmlRPCv2 in C# .NET

Expected behavior:
Should be possible to read HTML data in fields via XMLRPC, ideally the data should be escaped or encapsulated in CDATA tags?

Video/Screenshot link (optional):

Support ticket number submitted via odoo.com/help (optional):

**Comment by pedrobaeza** [comment]
@xmo-odoo is this a general problem, or something related to the used library/communication configuration on the other side?

**Comment by xmo-odoo** [comment]
@pedrobaeza it seems surprising that it would be broken in all of those versions, and indeed I can't repro this issue in 13 (e.g. trying to read user signatures works fine)

The one thing which does seem broken in master, it looks like #74678 was incomplete in a way the test I remembered to add didn't reveal because, err... I didn't think to put any markup in the test.

Checking locally, I simply forwarded the serialization of `Markup` objects (purportedly from HTML fields) to `dump_unicode` so those objects would be serialized instead of triggering errors, however while `Markup` objects are str subclasses and str-compatible operations are slightly different: method *parameters* are escaped before the operation is applied (which is usually desirable), so `xmlrpc.client.escape` does not apply (correctly) to `Markup` objects.

@chrisandrewmann have you actually confirmed this is broken in 12.0~14.0, or did you just test master and assume any version with HTML fields was broken?

**Comment by chrisandrewmann** [comment]
Thanks @xmo-odoo and @pedrobaeza 
Looks like much work has already gone into this, i'm not familiar with how HTML was normally made "safe" in Odoo via XMLRPC.

Can confirm that I just assumed it affected other versions but have only tested it with Master and latest revision of V14.0

**Comment by xmo-odoo** [comment]
> Looks like much work has already gone into this, i'm not familiar with how HTML was normally made "safe" in Odoo via XMLRPC.

Historically it was just transmitted as regular text, so would be escaped the normal way.

In 14.4 we (I) reworked large parts of the system to use `markupsafe.Markup` so we could mark values at the source instead of mark use sites at the sink, but this has a few side effects like the one you noticed here.

> I've just assumed that the answer would be to move away from XML and use JSON-RPC instead, which i've been looking into but quite a lot to change in my project.

Oh no, I mean if that's an option then go ahead but xmlrpc is supposed to keep working, even if we don't test it as much as we should #74678 came about because the issue was noticed internally. I did miss that my fix only handled the simplest of use cases.

**Comment by chrisandrewmann** [comment]
Update: I've just tested my XMLRPC client and you are right @xmo-odoo it does work fine in V13.0 still using latest Runbot.
So currently the issue only affects Master and V14.0

**Comment by xmo-odoo** [comment]
> So currently the issue only affects Master and V14.0

Hmmm I'd have expected the issue to start occurring in 14.4 not 14.0, I'll take a look it might be a different issue which was fixed in an intermediate revision before I broke things *again*.

**Comment by xmo-odoo** [comment]
@chrisandrewmann I tested on the latest 14.0 and it seems to work fine, on a brand new DB:
```python
>>> from xmlrpc.client import Server
>>> s = Server('http://localhost:8069/xmlrpc/2/object')
>>> s.execute_kw('test', 2, 'admin', 'res.users', 'search_read', [[], ['signature']])
[{'id': 7, 'signature': '<span data-o-mail-quote="1">-- <br data-o-mail-quote="1">Mr Demo Portal</span>'}, {'id': 6, 'signature': '<span data-o-mail-quote="1">-- <br data-o-mail-quote="1">+Mr Demo</span>'}, {'id': 2, 'signature': '<span data-o-mail-quote="1">-- <br data-o-mail-quote="1">\nAdministrator</span>'}]
```
and `signature` is indeed an HTML field on `res.users` in 14.0, it's been one essentially forever.

**Comment by chrisandrewmann** [comment]
Hmm, sorry I think I was too hasty and realised my test was not actually checking an HTML field last time.
Verified again and it's still failing on 12.0, 13.0, 14.0 and Master. 
The fields I've been testing are project.task > description, res.partner > comment (now HTML in Master but char perviously) and calendar.event > description (also now HTML in Master but char previously). Just in case it's model/field specific issue?

**Comment by xmo-odoo** [comment]
> Verified again and it's still failing on 12.0, 13.0, 14.0 and Master.
The fields I've been testing are project.task > description, res.partner > comment (now HTML in Master but char perviously) and calendar.event > description (also now HTML in Master but char previously).

How can they fail in 12.0 when they were not HTML fields back then? Could you try with e.g. the Python client?

> Just in case it's model/field specific issue?

That's possible but it seems doubtful.

**Comment by chrisandrewmann** [comment]
If this helps, the message I get from the XMLRPC client is similar to:
The 'br' start tag on line 13 position 20 does not match the end tag of 'p'. Line 13, position 25.
Error: "Response from server does not contain valid XML."

**Comment by xmo-odoo** [comment]
> @xmo-odoo When I mention 12.0, I mean specifically referencing any existing HTML field (i.e project.task > description) as a test that works across all versions where HTML fields have always been present.

So do I, that's why I tested with the `signature` field on `res.users`, which has content out of the box. But `project.task`'s description seems to work fine as well, here's 13.0 on a fresh demo db:
```python
>>> ids = s.execute_kw('test', 2, 'admin', 'project.task', 'search', [[]])
>>> s.execute_kw('test', 2, 'admin', 'project.task', 'write', [ids, {'description': '<br>'}])
True
>>> s.execute_kw('test', 2, 'admin', 'project.task', 'search_read', [[], ['description']])
[{'id': 24, 'description': '<br>'}, {'id': 23, 'description': '<br>'}, {'id': 22, 'description': '<br>'}, {'id': 21, 'description': '<br>'}, {'id': 19, 'description': '<br>'}, {'id': 18, 'description': '<br>'}, {'id': 29, 'description': '<br>'}, {'id': 28, 'description': '<br>'}, {'id': 27, 'description': '<br>'}, {'id': 26, 'description': '<br>'}, {'id': 25, 'description': '<br>'}, {'id': 20, 'description': '<br>'}, {'id': 17, 'description': '<br>'}, {'id': 16, 'description': '<br>'}, {'id': 15, 'description': '<br>'}, {'id': 14, 'description': '<br>'}, {'id': 13, 'description': '<br>'}, {'id': 31, 'description': '<br>'}, {'id': 30, 'description': '<br>'}]
```

**Comment by chrisandrewmann** [comment]
@xmo-odoo Thanks for that. Only comment i'd make is that your test appears to be using JSON-RPC not XML?
I'm not able to inspect the raw XML coming back into my program, but I suspect the problem lies in that it's confused between XML and HTML tags embedded. Any way you can some some raw XML?

**Comment by xmo-odoo** [comment]
> Thanks for that. Only comment i'd make is that your test appears to be returning JSON not XML?

That's the output of Python's client in the shell, so the xml-rpc payload has been deserialized to Python objects.

>  Any way you can produce some some raw XML?

Sure, here's the raw response if I enable verbose mode (and limit the resultset to 1 otherwise there is way too much crap):
```xml
<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><array><data>
<value><struct>
<member>
<name>id</name>
<value><int>24</int></value>
</member>
<member>
<name>description</name>
<value><string>&lt;br&gt;</string></value>
</member>
</struct></value>
</data></array></value>
</param>
</params>
</methodResponse>
```

**Comment by chrisandrewmann** [comment]
Looks perfect, thanks. So that shows Odoo DOES properly escape the HTML characters. I can only assume there is a bug in the XMLRPC client I use, maybe it tries to "re-encode" the escaped unicode characters beforehand.
Sorry to be of trouble, looks like it's possibly a coincidence that I reported this issue just as you were working on similar XMLRPC issues.

**Comment by xmo-odoo** [comment]
> Looks perfect, thanks. So that shows Odoo DOES properly escape the HTML characters. I can only assume there is a bug in the XMLRPC client I use, maybe it tries to "re-encode" the escaped unicode characters beforehand.
> Sorry to be of trouble, looks like it's possibly a coincidence that I reported this issue just as you were working on similar XMLRPC issues.

No worries, and good luck with your library.
