### ISSUE TITLE
[9.0] Display is messy when creating a new database

### ISSUE THREAD

**Issue by falinwa** [odoo/odoo#7951]
Hello Odoo,

I tried to make a test to install Odoo 9 alpha on windows,
I got the installation from here:
http://nightly.odoo.com/master/nightly/exe/odoo_9.0alpha1.20150730.exe

I have installed successfully, the server run well,
I created a new database, when I am inside on the new database, but the display is messy.

Here is the server log:
2015-08-07 10:42:47,687 2448 INFO Z_COBA_SLIDE werkzeug: 192.168.100.104 - - [07/Aug/2015 10:42:47] "GET /web/css/web.assets_backend/5f31e4e HTTP/1.0" 200 -
2015-08-07 10:42:49,875 2448 WARNING Z_COBA_SLIDE openerp.addons.base.ir.ir_qweb: 

C:\Documents and Settings\UserXP>"C:\Program Files\Odoo 9.0-20150730\thirdparty\\node.exe" "C:\Program Files\Odoo 9.0-20150730\thirdparty\\.\node_modules\less.js\bin\lessc" - --clean-css --no-js --no-color "--include-path=C:\Program Files\Odoo 9.0-20150730\server\openerp\addons\web\static\lib\bootstrap\less" 

Unable to interpret argument clean-css - if it is a plugin (less-plugin-clean-css), make sure that it is installed under or at the same level as less

usage: lessc [option option=parameter ...] <source> [destination]

If source is set to `-' (dash or hyphen-minus), input is read from stdin.

options:
  -h, --help               Prints help (this message) and exit.
  --include-path=PATHS     Sets include paths. Separated by `:'. Use `;' on Windows.
  -M, --depends            Outputs a makefile import dependency list to stdout.
  --no-color               Disables colorized output.
  --no-ie-compat           Disables IE compatibility checks.
  --no-js                  Disables JavaScript in less files
  -l, --lint               Syntax check only (lint).
  -s, --silent             Suppresses output of error messages.
  --strict-imports         Forces evaluation of imports.
  --insecure               Allows imports from insecure https hosts.
  -v, --version            Prints version number and exit.
  -x, --compress           Compresses output by removing some whitespaces.
  --source-map[=FILENAME]  Outputs a v3 sourcemap to the filename (or output filename.map).
  --source-map-rootpath=X  Adds this path onto the sourcemap filename and less file paths.
  --source-map-basepath=X  Sets sourcemap base path, defaults to current working directory.
  --source-map-less-inline Puts the less files into the map instead of referencing them.
  --source-map-map-inline  Puts the map (and any less files) into the output css file.
  --source-map-url=URL     Sets a custom URL to map file, for sourceMappingURL comment
                           in generated CSS file.
  -rp, --rootpath=URL      Sets rootpath for url rewriting in relative imports and urls
                           Works with or without the relative-urls option.
  -ru, --relative-urls     Re-writes relative urls to the base less file.
  -sm=on|off               Turns on or off strict math, where in strict mode, math.
  --strict-math=on|off     Requires brackets. This option may default to on and then
                           be removed in the future.
  -su=on|off               Allows mixed units, e.g. 1px+1em or 1px*1px which have units
  --strict-units=on|off    that cannot be represented.
  --global-var='VAR=VALUE' Defines a variable that can be referenced by the file.
  --modify-var='VAR=VALUE' Modifies a variable already declared in the file.
  --url-args='QUERYSTRING' Adds params into url tokens (e.g. 42, cb=42 or 'a=1&b=2')
  --plugin=PLUGIN=OPTIONS  Loads a plugin. You can also omit the --plugin= if the plugin begins
                           less-plugin. E.g. the clean css plugin is called less-plugin-clean-css
                           once installed (npm install less-plugin-clean-css), use either with
                           --plugin=less-plugin-clean-css or just --clean-css
                           specify options afterwards e.g. --plugin=less-plugin-clean-css="advanced"
                           or --clean-css="advanced"

-------------------------- Deprecated ----------------
  --line-numbers=TYPE      Outputs filename and line numbers.
                           TYPE can be either 'comments', which will output
                           the debug info within comments, 'mediaquery'
                           that will output the information within a fake
                           media query which is compatible with the SASS
                           format, and 'all' which will do both.
  --verbose                Be verbose.

Report bugs to: http://github.com/less/less.js/issues
Home page: <http://lesscss.org/>
This error occured while compiling the bundle 'web.assets_backend' containing:
    - /website/static/src/less/import_bootstrap.less
    - /web/static/src/less/enterprise_compatibility.less
    - /web/static/src/less/utils.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/notification.less
    - /web_calendar/static/src/less/web_calendar.less
    - /web_kanban/static/src/less/kanban_dashboard.less
    - /web_kanban/static/src/less/kanban_view.less

**Comment by sle-odoo** [comment]
well that's strange. It is correctly using the node we bundled and the clean css modules is correctly packaged too

**Comment by sle-odoo** [comment]
should be fixed, please upgrade

**Comment by falinwa** [comment]
hello,

Is this already merge?
I tried to install again from this link:
http://nightly.odoo.com/master/nightly/exe/odoo_9.0alpha1.20150810.exe

and the problem still exists.

**Comment by sle-odoo** [comment]
i tested it friday and it was fixed, are you sure that you correctly uninstalled the previous odoo installation?

**Comment by falinwa** [comment]
yes, I have uninstalled it,
I clean my cache, clean my registry, and drop the old database.
I installed again from the link in here:
http://nightly.odoo.com/master/nightly/exe/odoo_9.0alpha1.20150810.exe

I installed it again, everything is alright until I success create a new database,
when I login, the problem still exists, and the error log still the same.

**Comment by sle-odoo** [comment]
i'll have another look, thanks for your feedback

**Comment by jasjitchopra** [comment]
I tried a lot of builds and clean installed odoo 9 on windows even tried 8/24 build and still the same issue. Please see screenshots.
![odoo1](https://cloud.githubusercontent.com/assets/11431799/9442048/31f2c778-4a97-11e5-9e5f-fc287c712c28.JPG)
![odoo2](https://cloud.githubusercontent.com/assets/11431799/9442051/372e843e-4a97-11e5-8feb-9381d4398f4c.JPG)

**Comment by aliencrash** [comment]
I can say that the same problem in fedora 22 with build. But I solved the problem by installing npm from website instead from distribution package.
![snapshot1](https://cloud.githubusercontent.com/assets/10322162/9455629/2e7db6f6-4ac5-11e5-8092-a527f83d1832.png)

**Comment by jasjitchopra** [comment]
No luck I tried downloading nodejs from website and replaced the necessary files in thirdparty - it still gives the same issue.

**Comment by jasjitchopra** [comment]
FYI - it works without issues if I download source and follow the source install instructions on windows located here: https://www.odoo.com/documentation/8.0/setup/install.html#source-install

So something is wrong the nightly pre-packaged exe build here.

**Comment by falinwa** [comment]
yes, for version 8 its work normal, there's no problem, but for version 9 alpha it still have a bug on display.

**Comment by mateusclopes** [comment]
I try, and the problem still exists

**Comment by sle-odoo** [comment]
Hey,
Could you try again with [the latest build](http://nightly.odoo.com/master/nightly/exe/odoo_9.0alpha1.latest.exe)? 

I tested it on my side and it's working. Actually the rev 7c05b7965d89d7b9deb8ef98682962fb020e296c fixed the issue but was not applied on our nightly server...

**Comment by hannwong** [comment]
@sle-odoo On Mac El Capitano. Same problem. I did `sudo npm install -g less'.

**Comment by eronlloyd** [comment]
I'm confirming that I have the same errors in #10215 on Fedora 23. Also, someone just posted similar problems with Ubuntu in #12365. Am I hearing correctly that building from source is the only way around this? I'm setting up the enterprise version for a client on RHEL this week and really hope this is fixed ASAP.

**Comment by sle-odoo** [comment]
@eronlloyd hi, i just tested on Fedora 23 with the latest build and everything is working as expected, even the less compilation. what i did:
```
dnf install postgresql-server postgresql-contrib
postgresql-setup --initdb --unit postgresql
systemctl start postgresql
dnf config-manager --add-repo https://nightly.odoo.com/9.0/nightly/rpm/odoo.repo
dnf update
dnf install odoo
systemctl start odoo
```

**Comment by eronlloyd** [comment]
I removed `/bin/lessc` and then called `sudo npm install -g less less-plugin-clean-css` and it worked. I followed nearly exact instructions, as well, but ran into those less issues (along with `wkhtmltopdf`). I'll assemble my notes for further follow up if necessary. The good news is I had no issues installing on RHEL 7.3 today, so perhaps there's discrepancies between that and Fedora that I'm missing...
