### ISSUE TITLE
"Could not serialize access due to concurrent update" during long-running batch transactions on PG 9.3/9.4

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#8585]
Versions affected: 8.0, 9.0 (did not test on 7.0 but probably is also affected)

Steps to reproduce:
1. create a csv files, with 2 columns id and name, containing respectively numbers from 1 to 500 and 'partner1' to partner500, save it as res.partner.csv
2. connect on an instance on http://runbot.odoo.com, and open a second browser tab on the same instance
3. in the first tab:
   - display a list view of partners and click on the "import" link
   - upload res.partner.csv
   - click on the Validate or on the Import button
4. switch to the second tab, and hit Ctrl-R or F5

Expected: the import runs fine, and the second tab forks fine too

Actual: the import fails with an error message such as:

```
could not serialize access due to concurrent update CONTEXT: 
SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" 
OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x" at row 46 (467 more) 
```

**Comment by gurneyalex** [comment]
ping @odony

**Comment by odony** [comment]
@gurneyalex Thanks!

**Comment by odony** [comment]
@gurneyalex Would you mind re-testing with the latest 9.0 to verify that it is fixed after 94a0bbe, which puts the login date info outside the `res.users` table? Thanks!

The KEY SHARE/NO KEY UPDATE locks in PG 9.3+ do behave as expected in the sense that they do not block each other. However it turns out that PostgreSQL's heuristics for detection non-serializable patterns can still trigger when a long-running transaction repeatedly acquires the same KEY SHARE lock on a record that was concurrently updated. This makes the whole thing less useful than we hoped. We're still checking whether PG workarounds are possible in 7.0/8.0, but for 9.0 the easiest course is to move the field outside `res.users`.

**Comment by odony** [comment]
After discussing this with the PostgreSQL developers, it appears to be a behavior change/regression  [introduced in 9.3](http://www.postgresql.org/message-id/flat/20131121200517.GM7240@alap2.anarazel.de#20131121200517.GM7240@alap2.anarazel.de), and [fixed in upcoming 9.5](http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=05315498012530d44cd89a209242a243374e274d). So 9.3 brings many performance improvements for concurrent transactions, but actually makes this case worse.

The problem has to do with one transaction repeatedly acquiring the same (share) lock, with another transaction altering the locked record in the mean time.
This particular configuration occurs when a batch-based transaction T1 performs a series of inserts/updates (typically a background job or mass import) and a small update transaction T2 (typically a login) comes in the middle and updates a record used by T1 via a FK.

Prior to version 9.3, T2 would have had to wait (so the FOR UPDATE NOWAIT guard would have stopped it and prevented any trouble), and after the bugfix (in 9.5), neither wait nor error occurs.

There does not seem to be any workaround for this, but there is a chance the 9.5 fix could be backported to 9.4/9.3, although there was some concern with backwards-compatibility.

**Comment by wtaferner** [comment]
Great to hear that this issue got tackled and watched and even PostgreSQL will be improved...

**Comment by spadae22** [comment]
So, what happens for v8 running 9.3....

**Comment by harkx** [comment]
@spadae22 , nothing much I think.
I suppose you might want to (test) upgrade to PostgreSQL 9.5 when it's released.

**Comment by gurneyalex** [comment]
On 06/10/2015 19:36, E.R. Spada II wrote:
> So, what happens for v8 running 9.3....

You can install base_concurrency from github.com/OCA/server-tools which
works around this.


-- 
Alexandre Fayolle
Chef de Projet
Tel : +33 4 58 48 20 30

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac Cedex
http://www.camptocamp.com

**Comment by odony** [comment]
If anyone cares about getting this fixed upstream in PostgreSQL 9.3 and 9.4, here is the [bug report](http://www.postgresql.org/message-id/20151014164844.3019.25750@wrigleys.postgresql.org). If you have a contract support with PG or 2ndQuadrant, feel free to use it ;-)

**Comment by spadae22** [comment]
Hello I did use  base_concurrency but the real fix for us was the revert commit: https://github.com/odoo/odoo/commit/8209368b020a620e4f7287091cbe46cb70b6701e

All errors are gone. The issue is resolved here. But i push for the update also for psql

**Comment by lukebranch** [comment]
@odony ,

I'm still experiencing this issue quite regularly on an Odoo 9.0 instance with PostgreSQL 9.5 when upgrading modules like mail and base.

For example:
```
ParseError: "could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."ir_model" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
" while parsing /odoo/odoo-server/addons/crm/crm_lead_view.xml:698, near
<record id="action_mark_as_lost" model="ir.actions.server">
            <field name="name">Mark As Lost</field>
            <field name="model_id" ref="model_crm_lead"/>
            <field name="state">code</field>
            <field name="code">
                if context.get('active_model') == 'crm.lead' and context.get('active_ids'):
                    self.case_mark_lost(cr, uid, context['active_ids'], context=context)
            </field>
        </record>
```

**Comment by odony** [comment]
@lukebranch that's correct, you're facing a different kind of issue: a real conflict when 2 transactions are updating the *same record*. The table causing the conflict is a hint: `ir_model`, not `res_users`. There is no other way to resolve such a conflict than to replay one of the two transaction, which is what the system will be doing.
This issue (#8585) is about a long-running transaction being interrupted by a small transaction that updates a *different record* (linked via FK), which is a more frequent problem caused by the upstream PG bug.

**Comment by lukebranch** [comment]
@odony ,

Thanks for taking the time to explain that to me, I appreciate it.

I'll keep an eye out for anything strange in the logs, but from my experience so far it looks like Odoo 9 + PostgreSQL 9.5 seem to work quite well together.

**Comment by odony** [comment]
Now that we have started to deploy 9.5 on several development/testing environments (such as [runbot](https://twitter.com/odony/status/692651360366563329)), we noticed that the upstream bug seems to be only partially fixed. Apparently the concurrent update conflict does not occur anymore when the FK is one of the updated values (read: when the transaction writes on the `create_uid` column), but it has started to happen when the FK is not updated but other columns are. This did not happen in 9.4, so it would be a new bug that is very similar to the previous one, and partially defeats the benefit of the other fix :-( It should occur less often but will give similar symptoms.
To be confirmed via another upstream bug report...

**Comment by gurneyalex** [comment]
@odony thanks for giving this issue the care it deserves.

**Comment by spadae22** [comment]
@odony Thanks for the update.

**Comment by cmsalmeida** [comment]
@odony Thanks for your update about pg 9.5.
I was waiting 9.5 in expectation it will fix this once and for all, but it seems not.
So the question is, what postgres version will work better? Was this also an issue in 9.2 version (I don't remember to get it then), do any one tried to run Odoo 8.0 in pg 9.2?

**Comment by bluestingray** [comment]
@odony Has there been any fixes introduced for this? I'm running Ubuntu 14.04, Odoo 9 Enterprise, and Postgres 9.5 and experiencing the same issue.

**Comment by odony** [comment]
@bluestingray nope, no news on the PG side yet. However many different issues can produce similar symptoms. It is often worth examining carefully the transactions being rolled back and the error message to determine exactly the sequence of events leading to a transaction rollback (see e.g. luke's comment above, which is a true transaction conflict that cannot be avoided).

BTW simply seeing occasional transaction rollbacks in the server logs in not a problem (auto retry) unless the users frequently complain about error messages related to transaction rollbacks.

@cmsalmeida 9.2 did not have the serialization errors in this case, but instead caused the second transaction to block until the first was complete - possibly for quite a long time. This may not be a preferred outcome: long-running transactions like CSV imports or cron jobs would block interactive user requests. 9.3, 9.4 and 9.5 are probably better alternatives, but your mileage may vary depending on the actual transaction patterns. :-/

**Comment by lukebranch** [comment]
@odony ,

Thanks for the update on this. Hopefully PG gets back to you soon. I think this is the only problem I have really encountered with using PG 9.5 with Odoo 9, and I I usually only encounter this when doing updates on base modules like base, web, mail, etc.

**Comment by yucer** [comment]
We got this error also with a long running transaction that uses a similar import mechanism. 
I have tested yesterday and our error doesn't happen with the lastest postgres docker image https://hub.docker.com/_/postgres/ (version 9.5.3).

We need to try your test case.

**Comment by lukebranch** [comment]
@yucer ,

It looks like PG 9.5.3 has just been pushed to Xenial stable. I'll update and run some tests tomorrow. Thanks for the heads up.

**Comment by mattisx** [comment]
@odony @lukebranch @yucer Thanks for giving this issue some love, having troubles too.

**Comment by diegomor** [comment]
@odony 

Hi, I currently got the same error, during UPDATE, it only happens with non-admin user.

2016-09-01 16:13:46,811 22684 ERROR Pepes_prueba openerp.sql_db: bad query: UPDATE "account_invoice" SET "no_certificado"='20001000000
200000293',"cadena_original"='||3.2|2016-09-01T11:13:33|ingreso|Pago en una sola exhibicion|680.00|0|1.0|MXN|773.79|No Identificado|TU
LANCINGO Hidalgo, Mexico|No identificado|AAD990814BP7|CORPORATIVO PEPE''SS SA DE CV|Boulevard Quetzalcoatl|1201|N/A|COL. SANTA MARIA E
L CHICO|TULANCINGO|Hidalgo|Mexico|43709|Boulevard Quetzalcoatl|1201|N/A|COL. SANTA MARIA EL CHICO|TULANCINGO|Hidalgo|Mexico|43709|Pers
onas morales del regimen general|SOSJ890401PI2|PUBLICO GENERAL|calle|121|N/A|centro|qq|Aguascalientes|Mexico|55000|1.00|Unit(s)|00002|
[00002] ALERON CHEVROLET LUV 97-01,DEL IZQ,NEG|680.00|680.00|IVA|14.00|93.79|IEPS|0.00|0.00|93.79||',"certificado"='MIIE2jCCA8KgAwIBAg
IUMjAwMDEwMDAwMDAyMDAwMDAyOTMwDQYJKoZIhvcNAQEFBQAwggFcMRowGAYDVQQDDBFBLkMuIDIgZGUgcHJ1ZWJhczEvMC0GA1UECgwmU2VydmljaW8gZGUgQWRtaW5pc3Ry
YWNpw7NuIFRyaWJ1dGFyaWExODA2BgNVBAsML0FkbWluaXN0cmFjacOzbiBkZSBTZWd1cmlkYWQgZGUgbGEgSW5mb3JtYWNpw7NuMSkwJwYJKoZIhvcNAQkBFhphc2lzbmV0QH
BydWViYXMuc2F0LmdvYi5teDEmMCQGA1UECQwdQXYuIEhpZGFsZ28gNzcsIENvbC4gR3VlcnJlcm8xDjAMBgNVBBEMBTA2MzAwMQswCQYDVQQGEwJNWDEZMBcGA1UECAwQRGlz
dHJpdG8gRmVkZXJhbDESMBAGA1UEBwwJQ295b2Fjw6FuMTQwMgYJKoZIhvcNAQkCDCVSZXNwb25zYWJsZTogQXJhY2VsaSBHYW5kYXJhIEJhdXRpc3RhMB4XDTEyMTAyNjE5Mj
I0M1oXDTE2MTAyNjE5MjI0M1owggFTMUkwRwYDVQQDE0BBU09DSUFDSU9OIERFIEFHUklDVUxUT1JFUyBERUwgRElTVFJJVE8gREUgUklFR08gMDA0IERPTiBNQVJUSU4gMWEw
XwYDVQQpE1hBU09DSUFDSU9OIERFIEFHUklDVUxUT1JFUyBERUwgRElTVFJJVE8gREUgUklFR08gMDA0IERPTiBNQVJUSU4gQ09BSFVJTEEgWSBOVUVWTyBMRU9OIEFDMUkwRw
YDVQQKE0BBU09DSUFDSU9OIERFIEFHUklDVUxUT1JFUyBERUwgRElTVFJJVE8gREUgUklFR08gMDA0IERPTiBNQVJUSU4gMSUwIwYDVQQtExxBQUQ5OTA4MTRCUDcgLyBIRUdU
NzYxMDAzNFMyMR4wHAYDVQQFExUgLyBIRUdUNzYxMDAzTURGUk5OMDkxETAPBgNVBAsTCFNlcnZpZG9yMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlrI9loozd+UcW7Y
HtqJimQjzX9wHIUcc1KZyBBB8/5fZsgZ/smWS4Sd6HnPs9GSTtnTmM4bEgx28N3ulUshaaBEtZo3tsjwkBV/yVQ3SRyMDkqBA2NEjbcum+e/MdCMHiPI1eSGHEpdESt55a0S6N
24PW732Xm3ZbGgOp1tht1wIDAQABox0wGzAMBgNVHRMBAf8EAjAAMAsGA1UdDwQEAwIGwDANBgkqhkiG9w0BAQUFAAOCAQEAuoPXe+BBIrmJn+IGeI+m97OlP3RC4Ct3amjGmZ
ICbvhI9BTBLCL/PzQjjWBwU0MG8uK6e/gcB9f+klPiXhQTeI1YKzFtWrzctpNEJYo0KXMgvDiputKphQ324dP0nzkKUfXlRIzScJJCSgRw9ZifKWN0D9qTdkNkjk83ToPgwnld
g5lzU62woXo4AKbcuabAYOVoC7owM5bfNuWJe566UzD6i5PFY15jYMzi1+ICriDItCv3S+JdqyrBrX3RloZhdyXqs2Htxfw4b1OcYboPCu4+9qM3OV02wyGKlGQMhfrXNwYyj8
huxS1pHghEROM2Zs0paZUOy+6ajM+Xh0LX2w==',"sello"='YC/eLlxYqrGthK2lfxep9b15irrOe51DPGiJVQ/iTjhSDdjeE63fSWVqFyu8BAaCgrTzV9Yx/BKOCtKy//1NE
EHuavNT+v46tbjvkRgQiUmSGv1S2wMuShxDkmqVaHtNvjBQ5UHi3kUHvOrdqJ5U+BrBMcbHB5sVr2HPO9B1+W0=',"write_uid"=1,"write_date"=(now() at time zon
e 'UTC') WHERE id IN (9)
Traceback (most recent call last):
  File "/opt/odoopepess/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

2016-09-01 16:13:46,813 22684 ERROR Pepes_prueba openerp.sql_db: bad query:  SELECT "res_users"."id","res_users"."partner_id" FROM "re
s_users"
                        WHERE "res_users".id IN (1)  ORDER BY "res_users"."id"  

Has to do with security issues?

**Comment by odony** [comment]
@sapdenny What version of PostgreSQL 9.3 are you running? [Version 9.3.14](https://www.postgresql.org/docs/9.3/static/release-9-3-14.html) is [available in Ubuntu 14.04](http://packages.ubuntu.com/trusty/database/postgresql-9.3) and includes the patch for this issue.

For the record, the patch is also available in the 9.4 series as of version [9.4.9](https://www.postgresql.org/docs/9.4/static/release-9-4-9.html). Look for "could not serialize access" in the release notes.

I'm keeping this issue open because there is still a bug in 9.5 that will produce the same symptoms but occurs with a slightly different scenario (and I suspect this issue may now be present in 9.3.14 and 9.4.9 as well)

**Comment by sapdenny** [comment]
@odony use 9.3.10 and aha I read about this fix too on 9.3.14 

_"Avoid unnecessary "could not serialize access" errors when acquiring FOR KEY SHARE row locks in serializable mode (Álvaro Herrera)"_

Well I should go for upgrade. 
If there is any relevant documentation about how to upgrade version, I would apreciate :)

**Comment by odony** [comment]
I believe this issue can be closed now, as the original bug has been fixed upstream as of releases [9.3.14](https://github.com/postgres/postgres/commit/6c243f90ab6904f27fa990f1f3261e1d09a11853) and [9.4.9](https://github.com/postgres/postgres/commit/166873dd0c3083884ed16ce17f29f67ac8a64641), and [9.5.4](https://github.com/postgres/postgres/commit/649dd1b58b90754c67be86e99bd3af1bc3ab2c99).

Although the [upstream bug report](https://www.postgresql.org/message-id/20151014164844.3019.25750@wrigleys.postgresql.org) was originally reported to work in version 9.5, a slightly modified version of the reproduction scenario was still failing up to 9.5.3, as follows:
```
              T1                                T2
|--------------------------------|----------------------------------|
    BEGIN ISOLATION LEVEL
          REPEATABLE READ;

    -- Do not touch the FK yet!
    UPDATE orders
    SET name = 'order of foo'
    WHERE id = 1;

                                      BEGIN ISOLATION LEVEL
                                            REPEATABLE READ;

                                      UPDATE users
                                      SET date = now()
                                      WHERE id = 1;

                                      COMMIT;

    -- Now update the FK!
    UPDATE orders
    SET name = 'order of foo (2)',
        user_id = 1
    WHERE id = 1;

T1 fails with:
ERROR:  could not serialize access due to concurrent update
CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."users" x WHERE "id"
OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"
```
Notice that in this version the **first** UPDATE performed by T1 did **not** modify the FK `user_id`.

Version 9.5.4 now includes the bugfix from v9.3, and both scenarios are now working fine in all supported versions of PostgreSQL supported by Odoo 9 and later: 9.3, 9.4, 9.5, 9.6.

Just make sure you're using the latest minor version!

**Comment by lukebranch** [comment]
@odony ,

Thank you!

**Comment by spadae22** [comment]
@odony +1

**Comment by lushgreen** [comment]
@odony Thank you

**Comment by rwngallego** [comment]
I've got the same issue even when using PostgreSQL version **9.6.10** and **Odoo 11** with the latest changes from 2019-01-31. Apparently it's a bug with very bad consequences:

1. I created a new Database with the DB web interface
2. While in the creation process I accessed the site with another browser (/web/login) to check if the website still responds (I'm using 3 workers for multiprocess)
3. I got an Internal server error and the following logs
4. The DB got corrupted and the site completely unaccessible

```
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,326 25213 INFO mysite odoo.modules.registry: module auth_crypt: creating or updating database tables
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,348 25213 INFO mysite odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,473 25213 ERROR mysite odoo.sql_db: bad query: b"UPDATE ir_model SET state='base',transient=false,info=' User class. A res.users record models an OpenERP user and is different\n        from an employee.\n\n        res.users class now inherits from res.partner. The partner model is\n        used to store the data related to the partner: lang, name, address,\n        avatar, ... The user model is now dedicated to technical data.\n    ',name='Users' WHERE model='res.users' RETURNING id"
Feb 02 17:58:12 webserver01 odoo_srv[25207]: ERROR: could not serialize access due to concurrent update
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,499 25213 WARNING mysite odoo.modules.loading: Transient module states were reset
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,501 25213 ERROR mysite odoo.modules.registry: Failed to load registry
Feb 02 17:58:12 webserver01 odoo_srv[25207]: Traceback (most recent call last):
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/registry.py", line 85, in new
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 380, in load_modules
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     loaded_modules, update_module, models_to_check)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 274, in load_marked_modules
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     perform_checks=perform_checks, models_to_check=models_to_check
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 153, in load_module_graph
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     registry.init_models(cr, model_names, {'module': package.name})
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/registry.py", line 311, in init_models
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     func()
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/models.py", line 274, in _reflect
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     self.env['ir.model']._reflect_model(self)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/addons/base/ir/ir_model.py", line 247, in _reflect_model
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     query_update(cr, self._table, params, ['model'])
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/addons/base/ir/ir_model.py", line 54, in query_update
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     cr.execute(query, values)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/sql_db.py", line 155, in wrapper
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     return f(self, *args, **kwargs)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/sql_db.py", line 232, in execute
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     res = self._obj.execute(query, params)
Feb 02 17:58:12 webserver01 odoo_srv[25207]: psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,503 25213 ERROR mysite odoo.service.db: CREATE DATABASE failed:
Feb 02 17:58:12 webserver01 odoo_srv[25207]: Traceback (most recent call last):
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/service/db.py", line 62, in _initialize_db
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     registry = odoo.modules.registry.Registry.new(db_name, demo, None, update_module=True)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/registry.py", line 85, in new
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 380, in load_modules
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     loaded_modules, update_module, models_to_check)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 274, in load_marked_modules
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     perform_checks=perform_checks, models_to_check=models_to_check
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/loading.py", line 153, in load_module_graph
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     registry.init_models(cr, model_names, {'module': package.name})
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/modules/registry.py", line 311, in init_models
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     func()
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/models.py", line 274, in _reflect
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     self.env['ir.model']._reflect_model(self)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/addons/base/ir/ir_model.py", line 247, in _reflect_model
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     query_update(cr, self._table, params, ['model'])
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/addons/base/ir/ir_model.py", line 54, in query_update
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     cr.execute(query, values)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/sql_db.py", line 155, in wrapper
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     return f(self, *args, **kwargs)
Feb 02 17:58:12 webserver01 odoo_srv[25207]:   File "/opt/odoo/odoo_srv/odoo/sql_db.py", line 232, in execute
Feb 02 17:58:12 webserver01 odoo_srv[25207]:     res = self._obj.execute(query, params)
Feb 02 17:58:12 webserver01 odoo_srv[25207]: psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,529 25213 INFO mysite odoo.modules.loading: loading 1 modules...
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,568 25213 INFO mysite odoo.modules.loading: 1 modules loaded in 0.04s, 0 queries
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,661 25213 INFO mysite odoo.modules.loading: Modules loaded.
Feb 02 17:58:12 webserver01 odoo_srv[25207]: 2019-02-02 17:58:12,673 25213 INFO mysite odoo.addons.base.res.res_users: Login failed for db:mysite login:info@mysite.com from 81.251.65.228
```

I would say it's related to a bad design in the **last login** feature reported here: https://bitbucket.org/xcg/base_res_users_streamline/overview

After that the server was completely unaccessible (always returning 500 errors):

```
ValueError: External ID not found in the system: web.login
```

I had to delete the DB and start again as pointed here: https://github.com/odoo/odoo/issues/22985

**Comment by bnisevic** [comment]
This is still present in v12?

**Comment by volodymyrrudyi** [comment]
We are having the same issue on Odoo 12, hosted on Odoo.sh, almost clean install, minimum configuration (email servers).

**Comment by volodymyrrudyi** [comment]
```
2019-07-07 05:09:41,304 7 WARNING ? odoo.addons.base.models.ir_cron: Exception in cron: 
Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 258, in _acquire_job
cls._process_jobs(db_name)
File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 212, in _process_jobs
(job['id'],), log_exceptions=False)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 148, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 225, in execute
res = self._obj.execute(query, params)
psycopg2.extensions.TransactionRollbackError: could not serialize access due to concurrent update
```

**Comment by bnisevic** [comment]
@volodymyrrudyi
Checkout odony's explanations here under my comment https://github.com/odoo/odoo/issues/23086#issuecomment-507613444

I ended up changing default Postgres transaction isolation level. Something like here: https://github.com/ham2qur/odoo_change_db_isolation_mode/blob/master/__init__.py

**Comment by volodymyrrudyi** [comment]
@bnisevic  Thanks!

**Comment by bnisevic** [comment]
@volodymyrrudyi No problem. ;)

**Comment by khalyomede** [comment]
For people that came across this error like me, and wondered if we can update the isolation level programmatically, the answer is yes, and here is how you can do it:

```python
from odoo import models, api
from psycopg2.extensions import ISOLATION_LEVEL_READ_COMMITTED

class AccountPayment(models.Model):
    _inherit = "account.payment"

    @api.multi
    def post(self):
        """
        In this method, I simply override the native "confirm" button
        behavior to set the transaction isolation level.
        """
        old_isolation_level = self.env.cr._cnx.isolation_level

        self.env.cr._cnx.set_isolation_level(ISOLATION_LEVEL_READ_COMMITTED)

        self.some_long_blocking_process() # Does not exist, this is your custom method

        res = super(AccountPayment, self).post()

        self.env.cr._cnx.set_isolation_level(old_isolation_level)

        return res
```

I found that setting the isolation level to `READ COMMITTED` would prevent any error of type: 

> could not serialize access due to concurrent update odoo

It seems one method in the `ir.sequence` method, `next_by_code`, is performing underlyingly a PostgreSQL command `nextval()`:

```python
def _select_nextval(cr, seq_name):
    """
    Underlyingly called under "next_by_code" ir.sequence method
    """
    cr.execute("SELECT nextval('%s')" % seq_name)
    return cr.fetchone()
```
Which would probably be the cause of numerous concurrent update errors due to the fact that the ORM is using this command in SERIALIZABLE transaction isolation level (which seems to not cause any errors under `READ COMMITTED` transaction isolation level). Plus, that query was involved in my error 100% of the time. I also found out that some people seems to have some bad time with this `nextval` PostgreSQL command under `SERIALIZABLE` transaction isolation level (see: [https://www.odoo.com/fr_FR/groups/community-59/community-13952883](https://www.odoo.com/fr_FR/groups/community-59/community-13952883), I quote:

>To reproduce:
>- launch a big import of products using the import csv native wizard
>- login through XML-RPC in parallel
>
> 2015-09-18 04:06:55,161 533 ERROR v8 openerp.sql_db: bad query: INSERT INTO "product_template" ("id", "track_all", "list_price", "mes_type", "uom_id", "expense_pdt", "uos_coeff", "sale_ok", "categ_id", "track_outgoing", "company_id", "income_pdt", "uom_po_id", "type", "track_incoming", "active", "rental", "sale_delay", "name", "available_in_pos", "to_weight", "create_uid", "write_uid", "create_date", "write_date") VALUES(**nextval('product_template_id_seq')**, false, '1.00', 'fixed', 1, false, '1.000', true, 1, false, 1, false, 1, 'consu', false, true, false, 7.0, 'product_465', true, false, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
> Traceback (most recent call last):
>   File "/opt/openerp/code/8.0/odoo/openerp/sql_db.py", line 234, in execute
>     res = self._obj.execute(query, params)
> TransactionRollbackError: could not serialize access due to concurrent update
> CONTEXT:  SQL statement "SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x"

The `next_by_code` was called in this native `post()` method like below:

```python
rec.name = self.env['ir.sequence'].with_context(ir_sequence_date=rec.payment_date).next_by_code(sequence_code)
```

I do not master very well those PostgreSQL concept, but since I had the issue, and was able to fix it using the code above, I wanted to add my testimonial on this problem that many could encouter in some high concurrency context.

**Context at my company**

In the method I mentionned above as an example, we was making a request for a payment (to a service similar to paypal). The fact that Odoo was retrying the whole process has the consequence to make a second payment request to our service (which the distant payment service would refuse because our transaction reference was the same, we made it not dependant of a temporal variable and be predictible for this exact purpose, to avoid double payments). 

The problem was that in case our service returns this error (because of an attempt to pay an already purchased payment), the code that handles the error would pass the payment in "cancelled" state. So the algorithm would go:

1. Request for payment
2. Payment accepted, returning success
3. Calling native `post()`
4. Native `post()` throws concurrent update error
5. Retry 1
6. Request for payment
7. Payment **refused**
8. Payment cancelled
9. Calling native `post()`
10. Native end
11. End

So you we would end up with an accounted payment in our service server, but canceled because Odoo's native post method throwed a concurrent update error and retried the payment.

I hope it helps someone passing by with the same issue... Had an hard time with that, if it can save you some time on that would be fantastic!

**Comment by odony** [comment]
@khalyomede The solution you have chosen is dangerous. The "read committed" level is not appropriate for Odoo transactions, and that this the reason why we use "repeatable read" by default. It allows "phantom reads" and worse, it disabled PG heuristics for detecting concurrent updated. You can read more about that in the [PostgreSQL doc](https://www.postgresql.org/docs/9.6/transaction-iso.html).

By changing the default serialization level you are possibly corrupting your transaction (and perhaps other transactions) in unforeseen ways. Your warranty is entirely void, so please don't complain ever about corrupted data ;-)

----

For the record, the `nextval()` call is **definitely not** the cause for the concurrent update errors. PostgreSQL sequences are non-transactional and cannot cause the effect you see. Quoting [the documentation](https://www.postgresql.org/docs/9.6/functions-sequence.html):
> Important: To avoid blocking concurrent transactions that obtain numbers from the same sequence, a nextval operation is never rolled back; that is, once a value has been fetched it is considered used and will not be returned again. This is true even if the surrounding transaction later aborts, or if the calling query ends up not using the value. (...) Thus, PostgreSQL sequence objects cannot be used to obtain "gapless" sequences.

In your example, the cause for the transaction rollback is clearly shown in the error trace:  
> TransactionRollbackError: could not serialize access due to concurrent update
> CONTEXT: SQL statement "**SELECT 1 FROM ONLY "public"."res_users" x WHERE "id" OPERATOR(pg_catalog.=) $1 FOR KEY SHARE OF x**"

What happens here is that `INSERT` on `product_template` needs to obtain a "KEY SHARE" lock on the `res_users` table, because of the foreign key of the `create_uid` field.
If you *login via RPC* at the same time there is a chance you will cause another transaction to write on `res_users` to UPDATE the "last login date", which will cause a [transaction conflict](https://www.postgresql.org/docs/9.6/explicit-locking.html#ROW-LOCK-COMPATIBILITY). Note that this should only happen if you are using a very old version, as this issue was fixed in [version 9.0](https://github.com/odoo/odoo/commit/94a0bbed0a94e4bd34965c1466615d225ac8e509) (version 10.0 just reached end-of-life!)

Note: most developers don't know that RPC calls do not need to login first, as the password is provided for each call anyway. If you skip the login call you will remove a lot of useless updates on `res_users` too.

----

Now, in order to solve your duplicate payment problem without creating unpredictable corruptions you could **first** post() the payment in Odoo, **then** request the payment to the payment service on the other side, and if the payment is refused, `rollback()` the transaction (just raise an exception, rollback is automatic). If the payment succeeds, `commit()` immediately. There is no problem in posting the payment in Odoo before doing it on the remote service, because it's part of a _transaction_! It will not be for real until you `commit()` the transaction. That's what transactions are made for in RDMS, and how they are supposed to be used with Odoo.

Transactional problems arise when business logic needs to use non-transactional systems **outside of** the database, like email service, payment services or filesystems. For these special cases we need to make sure we will be able to `commit()` the transaction before we "permanently alter the rest of the world". This is usually done by decoupling the transaction and the "outside world effect". Here are examples of how we do it in Odoo:
- Emails are put in a queue by default, and will be sent later by a mailqueue cron job. So an email won't be sent if the transaction that created it was rolled back for whatever reason.
- Files deleted in the Odoo filestore are put in a special queue that is processed later, and will only be physically deleted on disk if the file deletion was successfully committed in the database.

**Comment by odony** [comment]
I think it's best to close this thread now because it's attracting confusing  comments. People are not reading the explanations, and jumping to the wrong conclusions, which will hurt them in the long run. Sorry about that.
