### ISSUE TITLE
Error after deleting "Direct Sales" team

### ISSUE THREAD

**Issue by jonvargas** [odoo/odoo#8624]
I just installed a clean 9.0 branch and I added a couple of sales teams, and then deleted the "Direct Sales" that comes by default. Once done that, every page on the Sales menu displays this error message.

Maybe something is tied to the "Direct Sales" team? How to clean it up?

```
Odoo Server Error
Traceback (most recent call last):
  File "/srv/odoo/odoo9/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/odoo/odoo9/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/srv/odoo/odoo9/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/srv/odoo/odoo9/openerp/http.py", line 828, in __call__
    return self.method(*args, **kw)
  File "/srv/odoo/odoo9/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/srv/odoo/odoo9/addons/web/controllers/main.py", line 973, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/srv/odoo/odoo9/addons/web/controllers/main.py", line 965, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/api.py", line 318, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/odoo/odoo9/addons/web_planner/models/web_planner.py", line 44, in render
    values.update(getattr(self, planner_find_method_name)()) # update the default value
  File "/srv/odoo/odoo9/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/odoo9/addons/crm/web_planner.py", line 18, in _prepare_planner_crm_data
    sales_team = self.sudo().env.ref('sales_team.team_sales_department')
  File "/srv/odoo/odoo9/openerp/api.py", line 737, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/srv/odoo/odoo9/openerp/api.py", line 221, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/api.py", line 445, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/addons/base/ir/ir_model.py", line 978, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/srv/odoo/odoo9/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/odoo/odoo9/openerp/addons/base/ir/ir_model.py", line 964, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/srv/odoo/odoo9/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/srv/odoo/odoo9/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/srv/odoo/odoo9/openerp/addons/base/ir/ir_model.py", line 954, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: sales_team.team_sales_department
```

**Comment by mart-e** [comment]
Hello,

Fixed at b15775c73127b8a765f054019f3adb7d2506c746, thanks

**Comment by satriani-vai** [comment]
I get the same error during the installation of the eCommerce app on a clean 9.0
The installation fails with this error.

**Comment by Karsten-77** [comment]
Please can you fix that error in all branches? Still exist in saas-6

**Comment by mart-e** [comment]
@Karsten-77 the crm planner doesn't exists in saas-6 so your issue must be different. Please open a new report.

**Comment by jprodriguez12** [comment]
I had the same problem with Odoo 9 community version. This was preventing me to update CRM module. Moreover, since the update was activated in ir_module_module table, this was preventing the whole ERP from working.
I have solved the problem in my installation, so may be my solution can help you.
The file sales_team_data.xml (and many other) references to the model crm.team using id="team_sales_department". This Id is searched in the table ir_model_data.
In my case, after deleting the "Direct Sales" team, the corresponding register in ir_model_data was also erased, and this was the source of the problem.
I have created again the record in ir_model_data table using the following data:
+ id: The next one in the table
+ Create_uid: The one corresponding to admin (1 in my case)
+ Create_date: 2016-01-01
+ Write_date: 2016-01-01
+ Write_uid:  The one corresponding to admin (1 in my case)
+ noupdate: true
+ name: team_sales_department
+ date_init:  2016-01-01
+ date_update:  2016-01-01
+ module: sales_team
+ model: crm.team
+ res_id: The ID of the sales team I want to use. It refers to the id column in crm_team table. You have to check the ID you want to use in the crm_table.

Please backup your database before changing directly any data in the database just in case.
