### ISSUE TITLE
[9.0] error when access Point of Sale > Configuration > Settings﻿

### ISSUE THREAD

**Issue by busel7** [odoo/odoo#8658]
```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 828, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 973, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 965, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/res/res_config.py", line 536, in default_get
    res[name] = int(res[name])
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by mart-e** [comment]
Fixed at 07dac79ddbef6c8221fbac1e0f8bb2e47e5fa285

**Comment by busel7** [comment]
Thanks for your info.

**Comment by busel7** [comment]
I already use 
$ git pull origin 9.0
But not fixed yet, then I edit manually but it's getting same error, how to apply that fix?

**Comment by mart-e** [comment]
It was reintroduced at 70dac31fea2bdedd5aebf6615eb929f762326456 as workign on a different fix
Re-reported at #8731
