### ISSUE TITLE
[9.0] crash when adding a follower

### ISSUE THREAD

**Issue by gurneyalex** [odoo/odoo#8756]
2 different crashes when trying to add a follower to a sale order (one server side, the other client side)

steps to reproduce:

1. connect on runbot, community edition 
2. display a sale order
3. click  on "One follower" -> "Add followers"
4. in the mail composition box, add "Asus Tech, Arthur Gomez"

I get the following stack trace:

    Traceback (most recent call last):
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 546, in _handle_exception
        return super(JsonRequest, self)._handle_exception(exception)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 583, in dispatch
        result = self._call_function(**self.params)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 316, in _call_function
        return checked_call(self.db, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/service/model.py", line 113, in wrapper
        return f(dbname, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 309, in checked_call
        result = self.endpoint(*a, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 828, in __call__
        return self.method(*args, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/http.py", line 412, in response_wrap
        response = f(*args, **kw)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/web/controllers/main.py", line 977, in call_kw
        return self._call_kw(model, method, args, kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/web/controllers/main.py", line 969, in _call_kw
        return checked_call(request.db, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/service/model.py", line 113, in wrapper
        return f(dbname, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/web/controllers/main.py", line 968, in checked_call
        return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3167, in read
        result = BaseModel.read(records, fields, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3202, in read
        self._read_from_database(stored, inherited)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3382, in _read_from_database
        res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/osv/fields.py", line 613, in get
        result[att.res_id] = att.datas
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/fields.py", line 816, in __get__
        self.determine_value(record)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/fields.py", line 911, in determine_value
        record._prefetch_field(self)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3261, in _prefetch_field
        result = records.read([f.name for f in fs], load='_classic_write')
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 538, in new_api
        result = method(self._model, cr, uid, self.ids, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/base/ir/ir_attachment.py", line 420, in read
        return super(ir_attachment, self).read(cr, uid, ids, fields_to_read, context=context, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3167, in read
        result = BaseModel.read(records, fields, load=load)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3202, in read
        self._read_from_database(stored, inherited)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 221, in wrapper
        return new_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/models.py", line 3382, in _read_from_database
        res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/osv/fields.py", line 1488, in get
        result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/base/ir/ir_attachment.py", line 188, in _data_get
        result[attach.id] = self._file_read(cr, uid, attach.store_fname, bin_size)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/api.py", line 223, in wrapper
        return old_api(self, *args, **kwargs)
      File "/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/openerp/addons/base/ir/ir_attachment.py", line 149, in _file_read
        r = os.path.getsize(full_path)
      File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 2] No such file or directory: '/home/odoo/runbot/extra/runbot/static/build/104118-9-0-d45935/datadir/filestore/104118-9-0-d45935-all/01/01ffc93194ea57412f56165615bb72c97264a9d7'

5. Try to add "Asus Teck, James Miller" and you'll get a different stack trace:

```
    Error: Unknown field type in domain [["type","=","contact"]]
    
    http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3157
    Traceback:
    compute_domain@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3157:1
    FormView<.compute_domain@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3526:339
    FormWidget<.process_modifiers@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3567:41
    Events<.trigger@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:2610:166
    EventDispatcherMixin<.trigger@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:2612:636
    FormView<.on_form_changed@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3478:68
    FormView<.load_record/<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3475:1
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:678
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.add@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:645:467
    .Deferred/promise.then/</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:631
    .each@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:473:758
    .Deferred/promise.then/<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:553
    .Deferred@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:651:189
    .Deferred/promise.then@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:518
    FormView<.load_record@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3474:328
    Events<.trigger@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:2610:166
    EventDispatcherMixin<.trigger@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:2612:636
    FormView<.do_show/shown</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2400-cb47797/web.assets_backend.js:3472:185
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:678
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:849
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:849
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    .Deferred/</deferred[tuple[0]]@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:651:31
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:849
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    .Deferred/promise.then/</</<@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:650:849
    jQuery.Callbacks/fire@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:644:281
    jQuery.Callbacks/self.fireWith@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:649:198
    done@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:1040:86
    .send/callback@http://104118-9-0-d45935.runbot6.odoo.com/web/content/2420-b4406b1/web.assets_common.js:1060:15
```

**Comment by antonylesuisse** [comment]
Fixed in 9.0 since the mail refactor merge.

**Comment by gurneyalex** [comment]
@antonylesuisse I confirm James Miller now works, but there is still an issue with Arthur Gomez. I opened another issue for that one (#8848)
