### ISSUE TITLE
[9.0 Enterprise]  ooo_9.0.latest.tar.gz can't contain checkbox.svg file

### ISSUE THREAD

**Issue by sum1201** [odoo/odoo#9118]
checkbox can't checked,
i found ooo_9.0.latest.tar.gz file can't contain checkbox.svg file. 
i download from runbot.odoo.com ,it's ok.

**Comment by mart-e** [comment]
What do you mean checkbox can't be checked ? Which checkbox.svg file are you referring to ? Where did you get the file ooo_9.0.latest.tar.gz ?
Please check [contributing guidelines](https://github.com/odoo/odoo/wiki/Contributing) for proper report format

**Comment by o2030** [comment]
Actually, I'm having the same problem as sum1201. Here is a more full explanation:

1) Installed Odoo 9 (Enterprise) version via the odoo_9.0.latest_all.deb debian package that is available on https://www.odoo.com/page/download (downloadable with an Enterprise contract in your account). OS: Debian 8.

2) After full installation and successfully connecting to Odoo on port 8069, all checkboxes in the Odoo interface display as unchecked even after clicking them. However, they do seem to take on checked status even though they don't show it.

3) This happens both on Firefox and Safari on OS X. Looking in Javascript inspector, error shown is:
Failed to load resource: the server responded with a status of 404 (NOT FOUND): /web/static/src/img/checked.svg

Is the file missing? Why is this happening?

Thanks

**Comment by mart-e** [comment]
Thank you for these explanations. Indeed there were a bug with missing svg files in the packaging. I have fixed it in 8.0 at 2fa8b99e15bd67be2d0dd0df6afe3eecc7867901
I will now port it to 9 and it should be present in tomorrow packages.

To fix your issue today, you can download the missing file [here](https://framadrop.org/r/uRym7Clwtw#YhmCkMn7mPtFDYIoVUjNdTriZ/6FwBikjUANktvU7nk=) and put it inside the `web/static/src/img` folder of your odoo software. (but I advise  you to redownload anyway)

**Comment by callco** [comment]
I have been fighting this same problem for a couple of days now. The checked.svg file is present, but the check still does not appear on the "checked" boxes. What am I missing?

Vitals:
 - Windows Server 2008
 - Odoo 9.0 Enterprise
 - Build date(s): 20151218; 20151219
 - Installed using executable (All-In-One)

**Comment by JKE-be** [comment]
@callco 
Related & Fixed Issue #12150
