### ISSUE TITLE
Impossible to upload image from my computer

### ISSUE THREAD

**Issue by laetitia-gangloff** [odoo/odoo#9538]
**In mail template, impossible to upload image from my computer**

Impacted versions:

 - 9.0

Steps to reproduce:

 1. in a mail templates, change image
 2. choose "Upload an image from your computer"

Current behavior:

 - Nothing happens !
![image](https://cloud.githubusercontent.com/assets/7602419/11118048/4eb3f102-893f-11e5-910b-16b3e6b3a065.png)

Expected behavior:

 - Image loaded

**Comment by fbrisa** [comment]
Same problem here, odoo 9.0 (from nigthly deb 9.0.20151113)  , Ubuntu 14.04.3 LTS.

This is what /var/log/odoo/odoo-server.log   says:
werkzeug: 79.58.121.111 - - [13/Nov/2015 09:44:39] "POST /web_editor/attachment/add HTTP/1.1" 400 -

meanwhile in firefox: "NetworkError: 400 BAD REQUEST - http:// ..... ..... .. . ..  /web_editor/attachment/add"

**Comment by ol8vil** [comment]
I have the same problem (issue #9093).

**Comment by mveodoo** [comment]
We will fix it asap this week !

**Comment by nle-odoo** [comment]
Hello,

It should be solved in 9.0 with this commit https://github.com/odoo/odoo/commit/21a8c76

Thanks for reporting.

**Comment by ramashishb** [comment]
Hi,

I have installed odoo on Ubuntu 14.04. The odoo version is 9.0c.20160313. I am still getting this error. What needs to be done?

Thanks,
Ramashish

**Comment by ramashishb** [comment]
I did some changes in the 'main layout' by editing the html code and adding some css, after which i was unable to upload images. 

Thanks,
Ramashish

**Comment by nle-odoo** [comment]
Hello @ramashishb 

In this issue the issue seemed to occured in mail templates, I think you are speaking about the website ?

I guess since the issue is closed since so long, it would be better to open a new issue with your detailed scenario to get the issue (what you modify and how), if you want to reproduce without reinstalling instances are available for testing there: http://runbot.odoo.com/ (credential of administrator: login=admin password=admin (if nobody changed them))

Thanks.
